Repository IBM/ibm-common-service-operator, pull requests merged in 2020-11, with the labels that each got.

#279 update error logs
  controllers/bootstrap/init.go
  controllers/check/check_iam.go
  controllers/commonservice_controller.go
  controllers/commonservice_controller_test.go
  controllers/deploy/manager.go
  main.go
Labels: approved, lgtm, size/M

#278 create operatorgroup
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/XS

#173 Push image to quay
  Makefile
  common/scripts/quay_config_docker.sh
Labels: approved, lgtm, size/M

#280 delete existing ODLM
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#281 update secretshare digest
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#282 don't deploy policy controller by default
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#284 add shortname for NamespaceScope
  controllers/constant/namespace.go
Labels: approved, lgtm, size/XS

#283 Adding navconfiguration to operandrequess
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#286 remove iam-policy-controller
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/check/check_iam.go
Labels: approved, lgtm, size/XS

#285 add nss operator and optimize the code logics
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  common/scripts/lint-csv.sh
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/constant/namespace.go
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/operator.ibm.com_commonservices_crd.yaml
  main.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/XL

#287 update test rbac
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
  testdata/deploy/role.yaml
Labels: approved, lgtm, size/S

#289 add some error handlings in check IAM logic
  controllers/check/check_iam.go
Labels: approved, lgtm, size/S

#288 fix race condition issue and remove RBAC for NSS operator
  controllers/bootstrap/init.go
  controllers/constant/constant.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
Labels: approved, lgtm, size/S

#290 Deploy IAM Policy Controller
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/check/check_iam.go
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#291 add nss managed by odlm
  controllers/constant/namespace.go
Labels: approved, lgtm, size/S

#293 remove policy controller
  controllers/check/check_iam.go
Labels: approved, lgtm, size/XS

#292 sync with bedrock-size-yaml repo
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/L

#294 Remove quay push to avoid overwriting CICD push
  Makefile
Labels: approved, lgtm, size/XS

#295 42346: remove deprecated helm and catalog-ui operators
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
  docs/install-cli.md
  docs/install.md
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/L

#296 we don't need package manifest anymore
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  docs/cloudpak-integration.md
Labels: approved, lgtm, size/XL

#298 bump version to 3.6.1
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#299 update digest of secretshare and webhook
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#297 arrange rbac to reduce duplicate roles
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/L

#300 bump version to 3.6.2
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#301 remove catalog-ui from size
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/L

#302 Check common service health status
  common/scripts/health-check.sh
Labels: approved, lgtm, size/L

#306 bump version to 4.0
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#307 Bump version to 4.0
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#304 enhance force uninstall script
  common/scripts/force-uninstall.sh
Labels: approved, lgtm, size/L

#308 Fix upgrade backward compatible issue
  Makefile
  controllers/bootstrap/init.go
  controllers/constant/namespace.go
Labels: approved, lgtm, size/S

#303 update small amd64 profile
  controllers/size/large_amd64.go
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/L

#305 Fix health check issue
  common/scripts/health-check.sh
Labels: approved, size/L

#309 Add cluster info for health check
  common/scripts/health-check.sh
Labels: approved, size/XS
