Repository IBM/ibm-common-service-operator, pull requests merged in 2020-07, with the labels that each got.

#124 Enhance iam status check
  cmd/manager/main.go
  go.mod
  pkg/check/check_iam.go
Labels: approved, lgtm, size/S

#125 Enhance logic for delete old ODLM
  Makefile
  cmd/manager/main.go
  pkg/bootstrap/init.go
Labels: approved, lgtm, size/M

#126 Return nil when ibm-common-services-status configmap does not exist
  pkg/check/check_iam.go
Labels: approved, lgtm, size/XS

#128 Fix cannot get iam subscription issue
  pkg/check/check_iam.go
Labels: approved, lgtm, size/M

#132 using digest to replace image tag of the ibm-cs-webhook
  deploy/olm-catalog/ibm-common-service-operator/3.4.3/ibm-common-service-operator.v3.4.3.clusterserviceversion.yaml
Labels: approved, size/XS

#134 add sizing support for individual operators
  deploy/crds/operator.ibm.com_commonservices_crd.yaml
  deploy/crds/operator.ibm.com_v3_commonservice_cr.yaml
  pkg/apis/operator/v3/commonservice_types.go
  pkg/apis/operator/v3/zz_generated.deepcopy.go
  pkg/controller/add_commonservice.go
  pkg/controller/commonservice/commonservice_controller.go
  pkg/size/large_amd64.go
  pkg/size/large_ppc64le.go
  pkg/size/large_s390x.go
  pkg/size/medium_amd64.go
  pkg/size/medium_ppc64le.go
  pkg/size/medium_s390x.go
  pkg/size/small_amd64.go
  pkg/size/small_ppc64le.go
  pkg/size/small_s390x.go
Labels: approved, lgtm, size/XXL

#138 Use version 3.5.0 as development
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#136 adjust sizing by common service CR
  common/config/.golangci.yml
  controllers/commonservice_controller.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/L

#139 pick changes for common service 3.5.0
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#140 using image version 3.4 for cs 3.4
  deploy/olm-catalog/ibm-common-service-operator/3.4.4/ibm-common-service-operator.v3.4.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.5/ibm-common-service-operator.v3.4.5.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
