Repository IBM/ibm-common-service-operator, pull requests merged in 2020-09, with the labels that each got.

#215 update memory limit from latest x86 measurement
  controllers/size/large_amd64.go
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/S

#216 init and update size for Z
  controllers/size/large_s390x.go
  controllers/size/medium_s390x.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/XXL

#217 init power sizing
  controllers/size/large_ppc64le.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_ppc64le.go
Labels: approved, lgtm, size/XXL

#218 update operand config for Licensing Operator
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#220 Update install document
  docs/install-cli.md
  docs/install.md
Labels: approved, lgtm, size/M

#222 Update resource size and Enable HA of management ingress and nginx ingress
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/M

#224 Add labels for ibm certification
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/kustomization.yaml
  config/crd/patches/label_in_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.1/operator.ibm.com_commonservices_crd.yaml
Labels: approved, lgtm, size/M

#225 Update webhook image and update size
  controllers/size/medium_amd64.go
  deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#226 sync replicas for IAM in M and L
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
Labels: approved, lgtm, size/M

#227 requests are less than limits of size in P and Z
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/S

#228 update image digest
  deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#229 update profile for power and nginx-ingress
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_ppc64le.go
Labels: approved, lgtm, size/L

#230 fix request is over limit for nginxIngress
  controllers/size/small_ppc64le.go
Labels: approved, lgtm, size/XS

#231 update commonui replicas
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
Labels: approved, lgtm, size/S

#232 increase IAM and ingress resource requests and limits
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
Labels: approved, lgtm, size/M

#235 Update size
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/S

#236 Update size
  controllers/size/large_amd64.go
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/L

#239 update sizing
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
Labels: approved, lgtm, size/XL

#241 update secretshare digest
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.4/ibm-common-service-operator.v3.5.4.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#242 update iam sizing
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
Labels: approved, lgtm, size/L

#243 missed large & small profile updates for IAM
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/L

#245 cert-manager cainjector memory limit update
  controllers/size/large_amd64.go
  controllers/size/medium_amd64.go
Labels: approved, lgtm, size/XS

#244 update oidcclientwatcher memory limits
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/S

#246 remove manager from gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#248 update manager.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#249 Add missing replaces
  deploy/olm-catalog/ibm-common-service-operator/3.5.4/ibm-common-service-operator.v3.5.4.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
