Repository IBM/ibm-common-service-operator, pull requests merged in 2020-06, with the labels that each got.

#105 Update skip range
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#106 refresh the cs operator image
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#104 remove ODLM csv in ibm-common-services namespace
  pkg/bootstrap/init.go
Labels: approved, lgtm, size/S

#102 Add a force delete script for uninstall common service
  common/scripts/force-uninstall.sh
Labels: approved, enhancement, size/L

#111 update install doc to use CatalogSource
  docs/install.md
Labels: approved, lgtm, size/M

#116 update to dev-latest tag
  docs/cloudpak-integration.md
  docs/install-cli.md
  docs/install.md
Labels: approved, size/M

#117 add product info to make metering report better
  deploy/olm-catalog/ibm-common-service-operator/3.4.3/ibm-common-service-operator.v3.4.3.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#118 update version to fix upgrade issue
  deploy/olm-catalog/ibm-common-service-operator/3.4.2/ibm-common-service-operator.v3.4.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.3/ibm-common-service-operator.v3.4.3.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#119 Remove nginx-ingress RBAC
  common/scripts/force-uninstall.sh
Labels: approved, lgtm, size/S

#120 Enhance lint-csv to support yq and jq existed
  common/scripts/lint-csv.sh
Labels: approved, lgtm, size/S

#115 Update catalogsource image
  cs3.4-restore.yaml
Labels: lgtm, size/XS

#121 use custom registry server for ocp 4.3
  docs/install.md
Labels: approved, lgtm, size/S

#113 Update documents for CatalogSource
  docs/cloudpak-integration.md
  docs/images/create-catalog-source.png
  docs/images/create-operator-source.png
  docs/install-cli.md
  docs/install.md
Labels: approved, lgtm, size/M
