Repository IBM/ibm-common-service-operator, pull requests merged in 2020-05, with the labels that each got.

#30 onboard ibm cs webhook
  build/resources/extra/webhook_deploy.yaml
Labels: approved, size/XXL

#31 revert version to v1alpha1
  build/resources/cs-operandconfig.yaml
  build/resources/cs-operandregistry.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  docs/cloudpak-integration.md
  docs/install.md
Labels: approved

#33 Seperator webhook yaml file
  build/resources/extra/webhook_crd.yaml
  build/resources/extra/webhook_deploy.yaml
Labels: approved

#34 add metering report server cr to operand config
  build/resources/cs-operandconfig.yaml
Labels: approved, lgtm, size/XS

#36 creating a separate registry and config for the dev channel
  build/resources/cs-operandconfig.yaml
  build/resources/cs-operandregistry.yaml
  docs/cloudpak-integration.md
Labels: approved, size/L

#37 remove operandrequest from ingress nginx
  build/resources/cs-operandconfig.yaml
Labels: approved, size/XS

#40 Moved Secretshare operator to quay.io/opencloudio
  build/resources/extra/secretshare_deploy.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#39 Add uninstall docs
  docs/uninstall.md
Labels: approved, size/M

#43 Add a stable channel
  build/resources/cs-operandconfig.yaml
  build/resources/cs-operandregistry.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  docs/cloudpak-integration.md
  docs/images/install-operator.png
  docs/install.md
Labels: approved, size/XL

#45 Update api version to v3
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#42 Create a release branch for release-3.3
  Makefile
  build/resources/cs-operandconfig.yaml
  build/resources/cs-operandregistry.yaml
  common/Makefile.common.mk
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/ibm-common-service-operator.v3.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  deploy/operator.yaml
  docs/cloudpak-integration.md
  version/version.go
Labels: approved, lgtm, size/L

#46 enable all namespaces install mode
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
Labels: approved, size/XS

#47 add operandBindinfo
  build/resources/cs-operandconfig.yaml
Labels: approved

#48 add bindinfo and request for the logging
  build/resources/cs-operandconfig.yaml
Labels: approved

#49 Add operandbindinfo and update operator scope
  build/resources/cs-operandconfig.yaml
  build/resources/cs-operandregistry.yaml
Labels: approved, lgtm, size/XS

#50 Set two operators to public
  build/resources/cs-operandregistry.yaml
Labels: approved, lgtm, size/XS

#51 Remove ibm-cloud-info cm from SecretShare CR
  build/resources/extra/secretshare_deploy.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#52 Update the install doc
  docs/install.md
Labels: approved, lgtm, size/XS

#57 remove bindinfo in the common ui
  build/resources/cs-operandconfig.yaml
Labels: approved, lgtm, size/XS

#56 Add resource limit to cs operator
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/M

#58 Fix cv lint error
  README.md
  deploy/crds/operator.ibm.com_commonservices_crd.yaml
  deploy/crds/operator.ibm.com_v3_commonservice_cr.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/operator.ibm.com_commonservices_crd.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#59 Update cs operator display icon
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#61 update image tag to digest
  build/resources/extra/secretshare_deploy.yaml
  build/resources/extra/webhook_deploy.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#60 Update README.md
  README.md
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#63 remove the unnecessary copies
  build/resources/extra/secretshare_deploy.yaml
Labels: approved, lgtm, size/S

#65 Revert "update image tag to digest (#61)"
  build/resources/extra/secretshare_deploy.yaml
  build/resources/extra/webhook_deploy.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#67 Fix case bundle issue
  deploy/role_binding.yaml
Labels: approved, lgtm, size/XS

#66 Add lablel for dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/S

#54 Add document for installing with cli
  docs/design.md
  docs/install-cli.md
  docs/uninstall.md
Labels: approved, lgtm, size/L

#62 remove existing 3.3 ODLM subscription and csv
  pkg/bootstrap/init.go
Labels: approved, size/S

#69 update config used for 3.3
  build/resources/cs-operandconfig.yaml
  build/resources/odlm-subscription.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/ibm-common-service-operator.v3.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#68 Add install in cluster scope by cli
  docs/install-cli.md
Labels: approved, lgtm, size/S

#72 remove version: 1 in release 3.3
  build/resources/cs-operandconfig.yaml
  build/resources/cs-operandregistry.yaml
Labels: approved, lgtm, size/XS

#73 Add license file in docker image to fix image certify issue
  build/Dockerfile
Labels: approved, lgtm, size/S

#74 Update README.md
  README.md
Labels: approved, lgtm, size/S

#70 Add skiprange for upgrade from 3.3
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#71 Update 3.3.0 csv
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/ibm-common-service-operator.v3.3.0.clusterserviceversion.yaml
Labels: approved, size/L

#75 Add rbac to kube-public
  build/resources/extra/rbac_cluster_info.yaml
  docs/uninstall.md
Labels: approved, size/M

#76 update readme to pass the cv-lint
  README.md
Labels: approved

#78 add a NOTE to readme
  README.md
Labels: approved, size/XS

#79 don't build latest tag for multiarch image on release branch
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/XS

#80 create a beta channel and use image digest
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
Labels: approved, lgtm, size/S

#81 Update secretshare digest
  build/resources/extra/secretshare_deploy.yaml
Labels: approved, size/XS

#82 update image digest
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#84 bump version to 3.4.1 in dev channel
  Makefile
  README.md
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  version/version.go
Labels: approved, lgtm, size/L

#77 generate odlm in the ibm-common-services namespace
  build/resources/odlm-subscription.yaml
  build/resources/operatorGroup.yaml
  pkg/bootstrap/init.go
Labels: approved, lgtm, size/M

#90 update file name to match the code
  build/resources/operatorgroup.yaml
Labels: approved

#92 remove odlm csv v1.2.0
  pkg/bootstrap/init.go
Labels: approved, lgtm, size/S

#93 Update csv file name
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Labels: approved, size/XS

#91 Move CS resources extra resources to the CSV annotations
  build/Dockerfile
  build/resources/cs-operandconfig.yaml
  build/resources/cs-operandregistry.yaml
  build/resources/extra/rbac_cluster_info.yaml
  build/resources/extra/secretshare_deploy.yaml
  build/resources/extra/webhook_crd.yaml
  build/resources/extra/webhook_deploy.yaml
  build/resources/namespace.yaml
  build/resources/odlm-subscription.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  go.mod
  go.sum
  pkg/bootstrap/init.go
Labels: approved, do-not-merge/hold, enhancement, size/XXL

#89 inject vcs info to docker image
  Makefile
Labels: approved, lgtm, size/XS

#95 Add required RBAC for ibmcloud-cluster-ca-cert
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M

#96 add lint CSV code
  Makefile
  common/scripts/lint-csv.sh
Labels: approved, lgtm, size/M

#98 Check the old common services if installed
  cmd/manager/main.go
  pkg/check/check.go
Labels: approved, lgtm, size/M

#97 Update SecretShare resource to support IBM MCM
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#94 Add resource limit for the secretshare operator deployment
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#100 Check iam status
  cmd/manager/main.go
  pkg/check/check_iam.go
Labels: approved, lgtm, size/L

#101 increase ansible operator cpu/memorty
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
