Repository IBM/ibm-common-service-operator, pull requests merged in 2020-08, with the labels that each got.

#143 add 3.5.0 into package
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
Labels: approved, lgtm, size/XXL

#145 integrate with IBM artifactory
  Makefile
  common/scripts/config_docker.sh
  version/version.go
Labels: approved, lgtm, size/M

#144 update secretshare operator and cs webhook
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#147 supports the user doesn't set the sizing template in the CR
  Makefile
  controllers/commonservice_controller.go
Labels: approved, lgtm, size/XS

#148 Only reconcile namespacedname ibm-common-services/common-servcie
  controllers/commonservice_controller.go
Labels: approved, lgtm, size/M

#150 Remove productVersion metering annotations
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#149 Create cs operator subscription when cs operator doesn't exist in nam…
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/L

#151 use ubi as the base image
  Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#152 Enhance check cs sub logic
  controllers/bootstrap/init.go
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
  main.go
Labels: approved, lgtm, size/L

#146 integrate the services size
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XL

#153 add subscription rbac for secretshare
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#154 using the original deployment name
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#155 replace the CR used for the audit-logging operator
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XS

#156 update csv to use digest for secretshare and webhook
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#158 Create ibm-common-services ns at first
  main.go
Labels: approved, lgtm, size/S

#159 support configuring IBM Common Services
  docs/install.md
Labels: approved, lgtm, size/M

#161 fix indent issue
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XL

#160 Fix build multi arch issue
  Makefile
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/S

#162 Fix docker command not found issue
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/XS

#157 Refact makefile
  Dockerfile
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/Makefile.common.mk
  common/scripts/artifactory_config_docker.sh
  common/scripts/lint-csv.sh
  common/scripts/quay_config_docker.sh
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/operator.ibm.com_commonservices.yaml
Labels: approved, lgtm, size/L

#163 add rbac for the secretshare operator
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#164 Update generate-all
  Makefile
  common/scripts/lint-csv.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/operator.ibm.com_commonservices_crd.yaml
Labels: approved, lgtm, size/S

#165 bump CSV 3.5.0 to the beta channel
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
Labels: approved, lgtm, size/L

#166 Update secretshare image digest
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#169 update small and add medium profile
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XL

#168 Delete ibm-common-service webhook
  common/scripts/force-uninstall.sh
Labels: approved, lgtm, size/XS

#170 remove stanza for metering
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XS

#167 create CommonService CR with default small size
  controllers/bootstrap/init.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  docs/install.md
  main.go
Labels: approved, lgtm, size/XL

#171 standardize CR format - DO NOT MERGE
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/M

#172 update small profile
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/L

#174 update new small values
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/S

#175 update memory for the commonui
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XS

#176 Update secretshare image digest
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#177 upgrade golang version to avoid vulnerability issue
  Dockerfile
Labels: approved, lgtm, size/XS

#179 Update cs webhook image digest
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#180 Update sizing for iam
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/S

#181 update cpu sizings for nginx-ingress
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XS

#182 add license
  Dockerfile
Labels: approved, lgtm, size/XS

#183 Update digest for secretshare and cs webhook
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#186 Update secretshare digest and licensing sizing
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#188 update sizing for the common ui
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XS

#178 Add displayname
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#195 Update secretshare image digest
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#196 revert CR format
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/M

#197 removing size for logging
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/M

#198 update monitoring size format
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/L

#199 Update secretshare container name
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#200 increase limits based on experiment
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/M

#202 sync medium size values(audit-logging)
  controllers/size/medium_amd64.go
Labels: approved, lgtm, size/XS

#187 Refactor common service operator conntroller
  Makefile
  common/Makefile.common.mk
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/commonservice_controller_test.go
  controllers/constant/constant.go
  controllers/deploy/manager.go
  controllers/suite_test.go
  go.sum
  main.go
Labels: approved, lgtm, size/XXL

#201 adding switcheritem to commonui
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#203 don't set size during upgrade
  controllers/bootstrap/init.go
  controllers/constant/constant.go
Labels: approved, lgtm, size/M

#204 sync size values(monitor/mongodb)
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XS

#205 update sizing based new unlimited usage test
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/S

#206 update size for medium(mcmMonitor/configmap watcher)
  controllers/size/medium_amd64.go
Labels: approved, lgtm, size/XS

#207 Update memory limit for oidcclient-watcher
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XS

#209 Use medium as the default sizing profile
  controllers/constant/constant.go
Labels: approved, lgtm, size/XS

#210 update medium sizing profile
  controllers/size/medium_amd64.go
Labels: approved, lgtm, size/M

#211 Update pdp cpu limits small and medium
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XS

#208 init large size profile and sync the latest sizing data
  controllers/size/large_amd64.go
Labels: approved, lgtm, size/L

#214 Removing the overestimated values in small size
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/S

#212 Add labels to support power and s390x
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S
