Repository IBM/ibm-common-service-operator, pull requests merged in 2020-10, with the labels that each got.

#251 remove configmap-watcher
  controllers/check/check_iam.go
Labels: approved, lgtm, size/XS

#253 add new common UI collector resource
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/M

#256 add eventstream into operatoregistry
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#257 Events Operator should be added to common services 3.6, not 3.5.5
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#258 Update webhook digest
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#260 update odlm package name
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#261 Fix lint error
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#262 update odlm package name
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#259 disable leader election to avoid pod restarting
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#263 push 3.5.5 to stable channel
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
Labels: approved, lgtm, size/M

#267 Creating ODLM depending on install mode
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  controllers/bootstrap/init.go
  controllers/check/check.go
  controllers/commonservice_controller.go
  controllers/deploy/manager.go
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
  main.go
Labels: approved, lgtm, size/XL

#268 update clusterrole for webhook
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#269 refactor the code logic
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller_test.go
  controllers/constant/constant.go
  controllers/constant/yaml.go
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
  main.go
Labels: approved, lgtm, size/XL

#272 refactor code of boostrap resources
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/constant.go
  controllers/constant/namespace.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
  testdata/README.md
  testdata/deploy/cluster_rbac.yaml
  testdata/deploy/deploy.yaml
  testdata/deploy/role.yaml
  testdata/deploy/role.yaml.bak
  testdata/deploy/role_binding.yaml
  testdata/deploy/sa.yaml
Labels: approved, size/XXL

#274 update rbac
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/config/.golangci.yml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
  testdata/README.md
  testdata/deploy/deploy.yaml
  testdata/deploy/role.yaml
Labels: approved, lgtm, size/XXL

#275 revert image name
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/XS

#276 update odlm subscription
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  deploy/olm-catalog/ibm-common-service-operator/3.6.0/ibm-common-service-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#277 update test data
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S
