Repository IBM/ibm-common-service-operator, pull requests merged in 2020-12, with the labels that each got.

#311 update the memory limit for receiverContainer
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/S

#313 push 3.6.2 to stable-v1
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#317 bump version to 4.0.0
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/L

#318 bump version to 3.6.3 for release-3.6
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/L

#319 bump to 3.6.3 and update version
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#314 workaround for upgrade from 3.4.3
  controllers/bootstrap/init.go
  main.go
Labels: approved, lgtm, size/S

#321 using the stable channel
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#322 Using stable chanel for 3.6
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#310 Use lable kubernetes.io
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.2/ibm-common-service-operator.v3.4.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.3/ibm-common-service-operator.v3.4.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.4/ibm-common-service-operator.v3.4.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.5/ibm-common-service-operator.v3.4.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.2/ibm-common-service-operator.v3.5.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.3/ibm-common-service-operator.v3.5.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.4/ibm-common-service-operator.v3.5.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
  deploy/operator.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm

#312 Update uninstall and health check script
  common/scripts/force-uninstall.sh
  common/scripts/health-check.sh
Labels: approved, lgtm, size/M

#324 Support reconciling the common service CR from other namespaces
  controllers/commonservice_controller.go
  controllers/rules/rules.go
Labels: approved, lgtm, size/XL

#327 Add status phase
  api/v3/commonservice_types.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/commonservice_controller.go
Labels: approved, lgtm, size/M

#326 Resource comparison
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/rules/resource_comparison.go
  controllers/rules/resource_comparison_test.go
  controllers/rules/rules_suite_test.go
Labels: approved, lgtm, size/L

#328 add redhat marketplace operator to operand registry
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#329 update rbac and add error logs
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/commonservice_controller.go
Labels: approved, lgtm, size/S

#332 Adding operandBindInfo
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#331 add selection UI for size in cs CR
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#333 onboard zen operator
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#334 update power and z sizing
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
Labels: approved, lgtm, size/XL

#335 Shrink size
  controllers/commonservice_controller.go
  controllers/rules/resource_comparison.go
  controllers/rules/resource_comparison_test.go
  main.go
Labels: approved, lgtm, size/L

#336 update mongodb CPU request size
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/S

#337 Enable the default rules
  controllers/commonservice_controller.go
  controllers/operandconfig.go
  controllers/render_template.go
  go.mod
  main.go
Labels: approved, lgtm, size/XL

#338 update secretshare deployment
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#339 get masterNs to replace hardcoded ns
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/check/check_iam.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/operandconfig.go
  go.sum
  main.go
Labels: approved, lgtm, size/L

#341 update webhook digest
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#340 avoid direct to ibm-common-service in masterNs
  controllers/common/util.go
Labels: approved, lgtm, size/XS
