Repository IBM/ibm-common-service-operator, pull requests merged in 2020-04, with the labels that each got.

#1 onboard ibm-common-service-operator
  .gitignore
  Makefile
  README.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/.githooks/pre-commit
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/create_bundle.sh
  common/scripts/gobuild.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_commonservices_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_commonservice_cr.yaml
  deploy/olm-catalog/ibm-common-service-operator/0.0.1/ibm-common-service-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/0.0.1/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/operator/group.go
  pkg/apis/operator/v1alpha1/commonservice_types.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/bootstrap/constant.go
  pkg/bootstrap/init.go
  pkg/controller/controller.go
  tools.go
  version/version.go
Labels: lgtm, size/XXL

#2 build and push image
  Makefile
Labels: size/S

#3 fix image repo
  Makefile
Labels: size/XS

#4 docker login before pushing
  Makefile
Labels: size/S

#5 update olm-catalog
  Makefile
  deploy/olm-catalog/ibm-common-service-operator/1.2.0/ibm-common-service-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/1.2.0/operator.ibm.com_commonservices_crd.yaml
  deploy/operator.yaml
  pkg/bootstrap/constant.go
  pkg/bootstrap/init.go
Labels: size/S

#6 fix the operator package csv version
  deploy/olm-catalog/ibm-common-service-operator/1.2.0/ibm-common-service-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
Labels: size/S

#9 Update operandconfig instance
  pkg/bootstrap/constant.go
Labels: lgtm, size/XS

#12 add OWNERS file
  OWNERS
Labels: size/S

#14 Update operator channel to dev
  Makefile
  pkg/bootstrap/constant.go
Labels: approved, lgtm, size/M

#15 Update operator channel to dev
  pkg/bootstrap/constant.go
Labels: approved, lgtm, size/S

#13 add operandbindinfo, and dependency request for IBM Licensing
  pkg/bootstrap/constant.go
Labels: approved, lgtm, size/XS

#16 Update csv channel to dev
  pkg/bootstrap/constant.go
Labels: approved, lgtm, size/XS

#17 Add describe for csv
  deploy/olm-catalog/ibm-common-service-operator/1.2.0/ibm-common-service-operator.v1.2.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/commonservice_types.go
Labels: approved, lgtm, size/M

#19 Update OperandRrgistry and OperandConfig
  pkg/bootstrap/constant.go
Labels: approved, size/M

#18 update operator version and apiversion
  Makefile
  deploy/crds/operator.ibm.com_commonservices_crd.yaml
  deploy/crds/operator.ibm.com_v3_commonservice_cr.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  docs/cloudpak-integration.md
  pkg/apis/addtoscheme_operator_v3.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v3/commonservice_types.go
  pkg/apis/operator/v3/doc.go
  pkg/apis/operator/v3/register.go
  pkg/apis/operator/v3/zz_generated.deepcopy.go
Labels: approved, size/L

#20 move resources to yaml file
  build/Dockerfile
  build/resources/cs-operandconfig.yaml
  build/resources/cs-operandregistry.yaml
  build/resources/namespace.yaml
  build/resources/odlm-subscription.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  pkg/bootstrap/constant.go
  pkg/bootstrap/init.go
Labels: approved, size/XL

#21 fix dockerfile error
  build/Dockerfile
Labels: approved

#22 create extra yaml resources
  build/resources/extra/example-sa.yaml
  pkg/bootstrap/init.go
Labels: approved, size/M

#23 fix updating resource issue when it already exists
  pkg/bootstrap/init.go
Labels: approved, size/XS

#24 add more fields to CSV file
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
Labels: approved, size/XS

#26 Update config and registry api version to v1
  build/resources/cs-operandconfig.yaml
  build/resources/cs-operandregistry.yaml
Labels: approved, lgtm, size/XS

#25 add metering annotations
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#27 add design doc
  README.md
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  docs/cloudpak-integration.md
  docs/design.md
  docs/install.md
Labels: approved, size/M

#28 added yaml file for deployment secretshare_deploy.yaml
  build/resources/extra/example-sa.yaml
  build/resources/extra/secretshare_deploy.yaml
Labels: needs-ok-to-test, size/L
