Repository IBM/ibm-common-service-operator, pull requests merged in 2021-01, with the labels that each got.

#344 add ns suffix for clusterrole binding
  controllers/constant/constant.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
Labels: approved, lgtm, size/XS

#346 add permission for webhook to fetch configmap
  controllers/constant/webhook.go
Labels: approved, lgtm, size/XS

#349 update copyright for 2021
  Makefile
  api/v3/commonservice_types.go
  api/v3/groupversion_info.go
  api/v3/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/.githooks/pre-commit
  common/scripts/artifactory_config_docker.sh
  common/scripts/codecov.sh
  common/scripts/force-uninstall.sh
  common/scripts/gobuild.sh
  common/scripts/health-check.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint-csv.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/quay_config_docker.sh
  controllers/bootstrap/init.go
  controllers/check/check_iam.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/commonservice_controller_test.go
  controllers/constant/constant.go
  controllers/constant/namespace.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  controllers/constant/yaml.go
  controllers/deploy/manager.go
  controllers/operandconfig.go
  controllers/render_template.go
  controllers/rules/resource_comparison.go
  controllers/rules/resource_comparison_test.go
  controllers/rules/rules.go
  controllers/rules/rules_suite_test.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
  version/version.go
Labels: approved, lgtm, size/M

#348 Add master namespace name into logs
  controllers/bootstrap/init.go
  controllers/common/util.go
  go.sum
  main.go
Labels: approved, lgtm, size/S

#350 added bitscuit to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#351 cover the case configmap doesn't exist
  controllers/common/util.go
Labels: approved, lgtm, size/M

#352 add csWebhookOperatorEnableOpreqWebhook into csv
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/lint-csv.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/L

#355 update secretshare digest
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/XS

#353 onboard redis operator
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#356 Update the pathes for the upgrade
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/M

#354 Add tests for sizing
  testdata/README.md
  testdata/deploy/deploy.yaml
  testdata/sizing/large_mongodb.yaml
  testdata/sizing/large_size.yaml
  testdata/sizing/operandrequest.yaml
  testdata/sizing/small_size.yaml
  testdata/sizing/storage_class.yaml
Labels: approved, lgtm, size/L

#358 Convert digitals to string, then compare their size
  controllers/rules/resource_comparison.go
Labels: approved, lgtm, size/S

#360 Update image digest for secretshare and cs webhook
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#361 update redis packagename
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#362 remove deprecated logging and metering
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#363 bump common service operator version back to 3.7.0
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#364 revert the csv version to 3.7.0
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#365 update cs mapping configmap structure
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/common/util.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#367 remove deprecated size
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/L

#370 switch 3.7 to v3 channel
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#369 added test to change custom profiles
  Makefile
  testdata/actual.yaml
  testdata/expected.yaml
  testdata/sizing/medium_size.yaml
  testdata/test_profile.sh
Labels: approved, lgtm, size/XXL

#368 expose images as environmental variables
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/XL

#371 Set the default size to small
  controllers/constant/constant.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/XS

#372 updated gogo/protobuf module to v1.3.2 to fix CVE-2021-3121
  Makefile
  common/scripts/update_catalogsource.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#374 update catalog for zen operator
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  docs/install-cli.md
  docs/install.md
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#373 porting protobuf vulnerability fix to EUS
  Makefile
  OWNERS
  common/scripts/update_catalogsource.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#376 update structure of configmap
  controllers/common/util.go
Labels: approved, lgtm, size/XS

#378 feat: update the nss CR from the common service mapping configmap
  controllers/bootstrap/init.go
  controllers/common/util.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/L

#380 using beta channel
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#381 update the name of zen operator
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#379 added storageClass to CRD
  Makefile
  api/v3/commonservice_types.go
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/operandconfig.go
  controllers/render_template.go
  controllers/storageClass/storageClass.go
Labels: approved, lgtm, size/M

#382 onboard db2
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#383 update size for MongoDB
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/S

#385 feat: Remove secret sharing for metering
  controllers/constant/secretshare.go
Labels: approved, lgtm, size/XS

#384 add script for moving to ibm-catalogsource
  common/scripts/migrate-to-ibm-catalog.sh
  common/scripts/utils.sh
Labels: approved, lgtm, size/L

#386 update size for MongoDB (#383)
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/S

#388 update name of redis operator
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#377 add event to remind no update although CR changed
  controllers/commonservice_controller.go
  controllers/operandconfig.go
  controllers/rules/resource_comparison.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/L

#375 update channel to v3
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/L
