Repository IBM/ibm-common-service-operator, pull requests merged in 2021-11, with the labels that each got.

#695 bump version to 3.14.0
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#699 update golang to 1.17.3 for EUS
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#700 run go mod tidy for golang 1.17
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#697 check dev image for individual operator package
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: lgtm, approved, size/M

#701 provide msg when installedCSV is empty
  controllers/goroutines/operator_status.go
Labels: lgtm, size/XS, approved

#698 increase cert manager resources for EUS
  controllers/size/large_amd64.go
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: lgtm, size/S, approved

#702 update compare resource string version logic
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: lgtm, approved, size/M

#705 onboard redis service
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#704 compare catalogsource priority
  controllers/common/util.go
  controllers/constant/constant.go
Labels: lgtm, size/S, approved

#706 make sure cpp config exist in cncf cluster
  controllers/bootstrap/init.go
Labels: lgtm, approved, size/M

#708 update redis channel to v1.4
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#707 adopt EDB licensing multiarch image
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved
