Repository IBM/ibm-common-service-operator, pull requests merged in 2021-03, with the labels that each got.

#426 update IAM config when there is saas configmap
  controllers/common/util.go
  controllers/constant/constant.go
  controllers/iam/iam.go
  controllers/render_template.go
Labels: approved, lgtm, size/M

#427 Update the display name of common service CR
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#429 update size for amd64
  controllers/size/large_amd64.go
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/M

#430 scale up power and z limits
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/L

#435 bump version to 3.7.2
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#436 uncomment RLEASE_VERSION to avoid overwriting
  Makefile
Labels: approved, lgtm, size/XS

#433 fix: Keep both storageclass and size info
  controllers/operandconfig.go
Labels: approved, lgtm, size/XS

#439 uninstall in arbitrary ns
  common/scripts/force-uninstall.sh
Labels: approved, lgtm, size/S

#440 solve the mismatch for three size profile
  controllers/size/large_amd64.go
  controllers/size/medium_amd64.go
Labels: approved, lgtm, size/XS

#442 updated to version 3.8.0
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#438 updated ibm-iam-operator OperandBindInfo in CSV's OperandConfig template
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#444 use beta channel for dev
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#431 added more automation to make testing and version updates easier
  .github/workflows/ocp.yaml
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/tests/clear_ocp.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/test_profile.sh
  testing.md
Labels: approved, lgtm, size/XL

#445 remove channel check in operator check
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/XS

#448 Workflow
  .github/workflows/ocp.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#452 fixed error checking out code in workflow
  .github/workflows/ocp.yaml
Labels: approved, lgtm, size/XS

#451 bump crd version to v1
  PROJECT
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  common/Makefile.common.mk
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/crd/patches/cainjection_in_commonservices.yaml
  config/crd/patches/label_in_commonservices.yaml
  config/crd/patches/webhook_in_commonservices.yaml
  go.sum
Labels: approved, lgtm, size/L

#455 update crd version
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/config/.golangci.yml
  config/manager/manager.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  deploy/crds/operator.ibm.com_commonservices_crd.yaml
  deploy/crds/operator.ibm.com_v3_commonservice_cr.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/ibm-common-service-operator.v3.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.3.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/ibm-common-service-operator.v3.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/ibm-common-service-operator.v3.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.1/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.2/ibm-common-service-operator.v3.4.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.2/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.3/ibm-common-service-operator.v3.4.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.3/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.4/ibm-common-service-operator.v3.4.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.4/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.5/ibm-common-service-operator.v3.4.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.4.5/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/ibm-common-service-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.0/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.1/ibm-common-service-operator.v3.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.1/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.2/ibm-common-service-operator.v3.5.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.2/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.3/ibm-common-service-operator.v3.5.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.3/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.4/ibm-common-service-operator.v3.5.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.4/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/ibm-common-service-operator.v3.5.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-common-service-operator/3.5.5/operator.ibm.com_commonservices_crd.yaml
  deploy/olm-catalog/ibm-common-service-operator/ibm-common-service-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, ok-to-test, size/XXL
