Repository IBM/ibm-common-service-operator, pull requests merged in 2021-02, with the labels that each got.

#390 feat(tmp): Add openshift-redhat-marketplace in nss CR.
  controllers/constant/namespace.go
  controllers/constant/webhook.go
  controllers/operandconfig.go
  go.mod
Labels: approved, lgtm, size/XS

#391 updated go to version 1.15.7 to fix CVE-2021-3114 and CVE-2021-3115
  Dockerfile
  go.mod
Labels: approved, lgtm, size/XS

#393 update migration to ibm-catalog script
  common/scripts/migrate-to-ibm-catalog.sh
  common/scripts/utils.sh
Labels: approved, lgtm, size/L

#394 remove redis from the OperandRegistry
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#396 remove deprecated clusterissuer cs-ca-clusterissuer
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  docs/cloudpak-integration.md
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/XS

#397 Check the status of operator before upgrading
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/M

#398 fix size for z
  controllers/size/large_s390x.go
  controllers/size/medium_s390x.go
Labels: approved, lgtm, size/S

#399 Using reader to get CSV
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  testdata/deploy/role.yaml
Labels: approved, lgtm, size/XS

#400 feat: expose images as environmental variables
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, release-3.6, size/L

#401 enhance operator status check
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/XS

#402 support multiple ns for upgrading to 3.7
  common/scripts/upgrade_to_continuous_delivery.sh
Labels: approved, lgtm, size/M

#403 updated channel switch messages
  common/scripts/upgrade_to_continuous_delivery.sh
Labels: approved, lgtm, size/S

#404 fix sizes for z for 3.6
  controllers/size/large_s390x.go
  controllers/size/medium_s390x.go
Labels: approved, lgtm, size/S

#405 Waiting for cert-manager upgrade then update the operandconfig
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/L

#406 pin version to 3.4.3
  cs3.4-restore.yaml
Labels: lgtm, size/XS

#408 update permission
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/S

#407 Update namespaced permission
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/S

#409 add upgrade pathes
  cs3.5-restore.yaml
  cs3.6-restore.yaml
  cslatest-restore.yaml
Labels: lgtm, size/L

#410 bump version to 3.7.1
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  version/version.go
Labels: approved, lgtm, size/S

#413 Update admin role
  controllers/bootstrap/init.go
  controllers/constant/constant.go
  testdata/deploy/role.yaml
  testdata/deploy/role.yaml.bak
Labels: approved, lgtm, size/M

#414 rename yaml files for OperandConfig and OperandRegistry
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/lint-csv.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#412 hold to switch channel until upgrading to eus
  common/scripts/upgrade_to_continuous_delivery.sh
Labels: approved, lgtm, size/M

#415 add upgrade script for airgap
  common/scripts/upgrade_to_continuous_delivery.sh
  common/scripts/upgrade_to_continuous_delivery_airgap.sh
Labels: approved, lgtm, size/L

#416 update upgrade script
  common/scripts/upgrade_to_continuous_delivery_airgap.sh
Labels: approved, lgtm, size/M

#417 update iam policy controller size
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/XS

#418 update grafana limit
  controllers/size/small_amd64.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/XS

#421 update admin role for 3.6 release
  controllers/constant/constant.go
  testdata/deploy/role.yaml
  testdata/deploy/role.yaml.bak
Labels: approved, lgtm, size/S

#422 update ibm-common-services-cluster-admin during upgrade
  controllers/constant/constant.go
Labels: approved, lgtm, size/XS

#423 update script to be compatible with bash 3
  common/scripts/upgrade_to_continuous_delivery.sh
Labels: approved, lgtm, size/M

#424 Enhance iam status check
  controllers/check/check_iam.go
Labels: approved, lgtm, size/S

#425 rename operator name in the CSV
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M
