Repository IBM/ibm-common-service-operator, pull requests merged in 2021-09, with the labels that each got.

#622 UDS : fixing the operator name and packageName
  controllers/constant/odlm.go
Labels: lgtm, size/XS, needs-ok-to-test, approved

#624 require the operator-sdk v1 and yq version 4
  Makefile
Labels: lgtm, size/XS, approved, ¯\_(ツ)_/¯

#625 Remove UDS for September release
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#629 bump version to 1.11.0 & bump related webhook secretshare version
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/certmanager.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#631 onboarding UDS to Common services operator
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved, ok-to-test

#626 api-onboarding and slice comparison
  controllers/constant/odlm.go
  controllers/rules/resource_comparison.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, approved, size/M

#609 onboard and add size comparison for api-catalog
  controllers/constant/odlm.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, approved, size/M

#628 support coexistence of SaaS and all namespace mode
  controllers/common/util.go
Labels: lgtm, size/XS, approved

#627 add comparison for slices
  controllers/rules/resource_comparison.go
Labels: lgtm, size/S, approved

#632 bump version to 4.0.0+k
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/certmanager.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#634 customize api catalog storageclass in CS CR
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/constant/apicatalog.go
  controllers/render_template.go
Labels: lgtm, approved, size/M

#633 get operator list from OperandRegistry
  controllers/bootstrap/init.go
  controllers/goroutines/operator_status.go
Labels: lgtm, approved, size/M

#635 display cs cr status in ocp console
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/goroutines/operator_status.go
Labels: lgtm, approved, size/M

#636 wait for OperandRegistry be ready before fetch it
  controllers/goroutines/certmanager.go
  controllers/goroutines/operator_status.go
Labels: lgtm, size/XS, approved

#638 update installer doc
  docs/images/install-operator.png
  docs/images/installed-operators.png
  docs/images/search-operator.png
  docs/install.md
Labels: lgtm, size/XS, approved

#639 Continue when error
  api/v3/zz_generated.deepcopy.go
  controllers/goroutines/operator_status.go
Labels: lgtm, size/S, approved

#641 update log info
  controllers/goroutines/operator_status.go
Labels: lgtm, size/XS, approved

#643 Update project k version
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: lgtm, size/S, approved

#637 update certmanager APIGroup version to v1
  controllers/constant/certmanager.go
  controllers/goroutines/variables.go
Labels: lgtm, size/XS, approved

#644 crossplane configuration from env var
  controllers/constant/crossplane.go
Labels: lgtm, size/XS, approved

#645 Onboard CPP operator
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#646 Add permission to list storageclass
  api/v3/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: lgtm, approved, size/M

#647 Revert "update certmanager APIGroup version to v1 (#637)" so that CICD
  controllers/constant/certmanager.go
  controllers/goroutines/variables.go
Labels: lgtm, size/XS, approved

#649 add storageclass permission
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: lgtm, size/S, approved

#652 onboard spark
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved
