Repository IBM/ibm-common-service-operator, pull requests merged in 2021-08, with the labels that each got.

#591 opt-in of ubi base image automated builds
  Dockerfile
  Makefile
  base-images.json
  common/scripts/artifactory_config_docker.sh
Labels: approved, lgtm, size/XS

#593 revert #580
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
Labels: lgtm, size/S, approved

#592 Enrich cs cr status
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/goroutines/operator_status.go
  main.go
Labels: lgtm, size/L, approved

#583 patch cs and odlm image
  common/scripts/patch_image.sh
Labels: size/L, approved

#598 bump to CS 3.11.0
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/certmanager.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#597 Change Licensing logLevel in saas
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#595 add relatedImages to operator CSV
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#596 Enrich cs cr status - display subscription status & installplan
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/goroutines/operator_status.go
Labels: lgtm, size/L, approved

#604 bump webhook and secretshare version for CS 3.11
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: lgtm, size/S, approved

#605 Update force-uninstall.sh
  common/scripts/force-uninstall.sh
Labels: lgtm, approved, size/M

#602 onboard postgresql
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#607 use default path for two probes
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  main.go
Labels: lgtm, size/S, approved

#587 Uds onboarding
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved, ok-to-test

#611 Reduce cluster permission in common service operator
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: lgtm, approved, size/M

#610 set priority for catalogsource
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/constant.go
Labels: lgtm, size/L, approved

#612 Update apiVersions in crossplane.go
  controllers/constant/crossplane.go
Labels: lgtm, size/XS, approved

#613 update permission
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#615 Update OperandRegistry for UDS
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#614 enable size string comparison
  controllers/bootstrap/init.go
  controllers/operandconfig.go
  controllers/rules/resource_comparison.go
Labels: lgtm, size/S, approved

#616 update permission
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: lgtm, size/L, approved

#620 opt-in of ubi base image automated builds (#591)
  Dockerfile
  Makefile
  base_images.json
  common/scripts/artifactory_config_docker.sh
Labels: lgtm, size/XS, approved

#621 add permissions for SaaS
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: lgtm, approved, size/M
