Repository IBM/ibm-common-service-operator, pull requests merged in 2021-05, with the labels that each got.

#505 update more info log in upgrade script
  common/scripts/upgrade_to_continuous_delivery.sh
Labels: approved, lgtm, size/XS

#501 add iamstatus with cloud pak prefix
  controllers/check/check_iam.go
  controllers/common/util.go
  main.go
Labels: approved, lgtm, ok-to-test, size/L

#504 Add pre-check of whether storageClass existing
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: approved, lgtm, size/M

#507 interate all the subscription to find operator
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/S

#508 bump version to 3.6.5
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#509 add routeEnabled for SaaS
  controllers/constant/odlm.go
Labels: approved, lgtm, size/XS

#512 updated ubi8 image for vascan
  Dockerfile
Labels: approved, lgtm, size/XS

#510 reconcile cluster scope resource
  controllers/commonservice_controller.go
  controllers/operandconfig.go
  controllers/render_template.go
Labels: approved, lgtm, ok-to-test, size/M

#513 Add service_account.yaml under config
  config/rbac/service_account.yaml
Labels: approved, lgtm, size/XS

#514 feat: bootstrap cs operator in the manual approval mode
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/commonservice.go
  controllers/constant/constant.go
  controllers/constant/odlm.go
  main.go
Labels: approved, lgtm, ok-to-test, size/L

#515 feat: 1. bootstrap fail will exist operator. 2. remove registry from …
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/odlm.go
  controllers/suite_test.go
  main.go
Labels: approved, lgtm, size/M

#517 secret watcher is optional, removing it from the check list
  controllers/check/check_iam.go
Labels: approved, lgtm, size/XS

#518 set two iam deployment list for SaaS deployment and on-prem software
  controllers/check/check_iam.go
Labels: approved, lgtm, size/S
