Repository IBM/ibm-common-service-operator, pull requests merged in 2021-07, with the labels that each got.

#559 remove checking installedcsv with currentcsv for manual approval strategy
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/XS

#560 Update csv document
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#561 add probes
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  main.go
Labels: approved, lgtm, size/M

#562 create crossplane CR
  controllers/bootstrap/init.go
  controllers/constant/crossplane.go
Labels: approved, lgtm, size/M

#563 config IAM with OnPremMultiEnable
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: approved, lgtm, size/XS

#564 update force-uninstall script
  common/scripts/force-uninstall.sh
Labels: approved, lgtm, size/XS

#558 uninstall cert-manager after channel switch
  common/scripts/upgrade_to_continuous_delivery_airgap.sh
Labels: approved, lgtm, size/S

#566 increase CAinjector CPU limit and request
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/S

#567 revert resource requests of certManagerCAInjector
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, size/S

#568 Update description in owned CRDs in CSV to pass IBM certification.
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/M

#572 bump version to v3.9.1
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/certmanager/cert_cr.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: approved, lgtm, size/M

#576 Make probe more loose
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/S

#570 refactor constant template and additional routines
  controllers/constant/certmanager.go
  controllers/constant/multipleInstancesEnabled.go
  controllers/constant/routeHost.go
  controllers/constant/storageclass.go
  controllers/goroutines/certmanager.go
  controllers/goroutines/check_iam.go
  controllers/goroutines/namespacescope.go
  controllers/goroutines/variables.go
  controllers/render_template.go
  main.go
Labels: approved, lgtm, ok-to-test, size/L

#578 allow all cs cr in any namespaces can enable crossplane operator
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: approved, lgtm, size/M

#579 check whether the channel switch is completed
  common/scripts/upgrade_to_continuous_delivery.sh
  common/scripts/upgrade_to_continuous_delivery_airgap.sh
Labels: approved, lgtm, size/M

#581 fix nil interface bug
  controllers/operandconfig.go
Labels: approved, lgtm, size/XS

#574 Add Configuration as new type of Crossplane CR
  controllers/bootstrap/init.go
  controllers/constant/crossplane.go
Labels: approved, lgtm, size/M

#584 remove checking installedcsv with currentcsv (#559)
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/XS

#585 remove odlm subscription during the airgap upgrade
  common/scripts/upgrade_to_continuous_delivery_airgap.sh
Labels: approved, lgtm, size/M

#586 update readness probe
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#580 Reduce subscription update
  controllers/bootstrap/init.go
  controllers/constant/commonservice.go
  controllers/constant/namespace.go
  controllers/constant/odlm.go
Labels: approved, lgtm, size/M

#590 Add custer role for crossplane CR
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/S
