Repository IBM/ibm-common-service-operator, pull requests merged in 2021-06, with the labels that each got.

#523 filter the template size when the CR is out of scope
  controllers/operandconfig.go
  controllers/render_template.go
Labels: approved, lgtm, size/S

#522 add routeHost as new parameter in cr
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/render_template.go
  controllers/routeHost/routeHost.go
Labels: approved, lgtm, size/M

#519 [WIP] sync up NSS CR for common service and ODLM
  controllers/bootstrap/init.go
  controllers/certmanager/certmanager.go
  controllers/namespacescope/namespacescope.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, ok-to-test, size/L

#520 fetch the namespace from namespace-scope ConfigMap for iam status
  controllers/check/check_iam.go
  controllers/common/util.go
  controllers/constant/constant.go
Labels: approved, lgtm, size/M

#525 add additinal parameter for MultiInstancesEnable
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: approved, lgtm, size/M

#524 update the channel of the db2u operator
  controllers/constant/odlm.go
Labels: approved, lgtm, size/XS

#526 enable `multipleInstancesEnabled` in the management-ingress & ingress-nginx CR
  controllers/multipleInstancesEnabled/multipleInstancesEnabled.go
  controllers/render_template.go
Labels: approved, lgtm, size/M

#527 optimize the wait process for deploying cert CR
  controllers/certmanager/certmanager.go
Labels: approved, lgtm, size/S

#528 update comments and add Dependabot to update base image
  .github/dependabot.yml
  controllers/certmanager/certmanager.go
Labels: approved, lgtm, size/M

#530 find nssConfigMap in masterNs instead of operatorNs
  controllers/check/check_iam.go
  controllers/common/util.go
Labels: approved, lgtm, size/S

#533 bump version to 3.8.1
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/certmanager/cert_cr.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: approved, lgtm, size/M

#532 pre-check storage class, if nothing exists, give warning messages
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: approved, lgtm, size/S

#534 update operator-sdk to 1.8.0
  PROJECT
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#535 using klog.Waring for waring msg
  controllers/common/util.go
Labels: approved, lgtm, size/XS

#536 iam-status enhancement
  common/scripts/force-uninstall.sh
  controllers/check/check_iam.go
Labels: approved, lgtm, size/L

#537 handle interface {} is nil
  controllers/operandconfig.go
Labels: approved, lgtm, size/S

#539 bump master branch to 4.0.0 for future release
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/certmanager/cert_cr.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: approved, lgtm, size/M

#543 update secretshare and webhook image for future release
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#542 update secretshare and webhook image for release 3.9
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/S

#544 update sc pre-check warning msg
  controllers/common/util.go
Labels: approved, lgtm, size/XS

#548 add minKubeVersion
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/Makefile.common.mk
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#550 replace 3.8.0
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#551 update kubeVersion to 1.19.0
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#553 revert master branch to 3.9.0 for cd release
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/certmanager/cert_cr.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: approved, lgtm, size/M

#554 update replace from 3.8.1 to 3.8.0
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#555 add perrmission for validating webhook
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/constant/webhook.go
  testdata/deploy/role.yaml
  testdata/deploy/role.yaml.bak
Labels: approved, lgtm, size/XS

#545 add crossplane & cloud operator installation to cs-operator
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/bootstrap/init.go
  controllers/constant/crossplane.go
  controllers/constant/ibmcloud.go
Labels: approved, lgtm, size/L

#556 prioritize the dev catalogsource
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/common/util.go
  controllers/constant/constant.go
  testdata/deploy/role.yaml
Labels: approved, lgtm, size/M
