Repository IBM/ibm-common-service-operator, pull requests merged in 2021-10, with the labels that each got.

#653 remove deprecated beta.kubernetes.io label for EDB Job
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#654 typo in EDB Job role resource name and add verbs
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#655 update fluentd size
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: lgtm, size/XS, approved

#656 set restartPolicy as OnFailure
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#657 remove version from certificate
  controllers/constant/certmanager.go
Labels: lgtm, size/XS, approved

#658 let edb operator restart after license key created
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#661 add correct subscription channel for uds
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved, ok-to-test

#608 uninstall crossplane operator & cloud operator when delete cs cr
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, size/L, approved

#675 bump to 3.6.6 for eus
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  common/scripts/next-csv.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: lgtm, approved, size/M

#692 enhance troubleshooting doc description
  controllers/goroutines/operator_status.go
Labels: lgtm, size/XS, approved
