Repository IBM/ibm-common-service-operator, pull requests merged in 2021-04, with the labels that each got.

#457 updated golang to 1.15.10 and ubi8 to 8.3-291 to remediate
  Dockerfile
Labels: approved, lgtm, size/XS

#446 SaaS deployment at resource initialization stage
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/config/.golangci.yml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/webhook.go
  controllers/render_template.go
  main.go
Labels: approved, lgtm, ok-to-test, size/L

#450 Update OperandRegistry and OperandConfig for SaaS deployment
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/lint-csv.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/render_template.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, ok-to-test, size/XL

#461 update typos in CSV
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/S

#456 create issuer and certificate
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/certmanager/cert_cr.go
  controllers/certmanager/certmanager.go
  main.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, ok-to-test, size/L

#462 add control namespace to nss CR
  controllers/common/util.go
Labels: approved, lgtm, ok-to-test, size/XS

#464 Bump version to 3.7.3
  Makefile
  OWNERS
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#465 bump version of cs webhook and secretshare
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#466 Bump annotation version
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
Labels: approved, lgtm, size/XS

#467 updated ubi8 image to 8.3-298
  Dockerfile
Labels: approved, lgtm, size/XS

#470 Common Ui size update 390 small
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
Labels: approved, lgtm, ok-to-test, size/M

#472 update owners
  OWNERS
Labels: approved, lgtm, size/XS

#471 use semver as annotation version
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/certmanager/cert_cr.go
  controllers/constant/constant.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
Labels: approved, lgtm, size/L

#474 Using the Bash Arithmetic Expansion for Evaluation
  common/scripts/upgrade_to_continuous_delivery.sh
Labels: approved, lgtm, size/XS

#477 Retry for failed cert resource deploying
  controllers/certmanager/certmanager.go
Labels: approved, lgtm, ok-to-test, size/S

#463 watching cs-maps change, validate cs-mapping and filter its cs-scope
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/constant/namespace.go
  controllers/operandconfig.go
  go.mod
  go.sum
  main.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, ok-to-test, size/XL

#476 add IAM SaaS config
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/lint-csv.sh
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/iam/iam.go
  controllers/render_template.go
  controllers/suite_test.go
  main.go
Labels: approved, lgtm, size/M

#479 restore gocyclo
  common/config/.golangci.yml
Labels: approved, lgtm, ok-to-test, size/XS

#481 lower the log level
  controllers/certmanager/certmanager.go
Labels: approved, lgtm, ok-to-test, size/XS

#482 update channel to v3
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#480 Using template to render yaml files
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/certmanager/certmanager.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/commonservice.go
  controllers/constant/namespace.go
  controllers/constant/odlm.go
  controllers/operandconfig.go
  main.go
Labels: approved, lgtm, ok-to-test, size/XXL

#486 feat: Dynamically choose catalogsource
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/constant.go
  controllers/constant/odlm.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XL

#487 fix: get packageManifest from own namespace
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: approved, lgtm, size/XS

#478 remove logging for 3.6.4
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/storageclass/storageclass.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/M

#488 fix: update crd
  bundle/manifests/operator.ibm.com_commonservices.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: approved, lgtm, size/S

#489 delete old ODLM in upgrade
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/M

#485 set manual approval for CS operators
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  common/config/.golangci.yml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, ok-to-test, size/L

#490 Create a new NSS CR managed by ODLM
  controllers/bootstrap/init.go
  controllers/constant/namespace.go
Labels: approved, lgtm, size/S

#492 enhance ODLM version check
  controllers/bootstrap/init.go
Labels: approved, lgtm, size/M

#493 only check operators created by ODLM
  controllers/bootstrap/init.go
  go.sum
Labels: approved, lgtm, size/XS

#494 Add @ZhuoxiLi to OWNERS
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#499 bump version to 3.7.4
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#497 update audit logging resource
  controllers/size/large_amd64.go
  controllers/size/medium_amd64.go
  controllers/size/small_amd64.go
Labels: approved, lgtm, size/M

#498 deploy cluster-scope in ControlNs for on-prem multi instance case
  controllers/constant/odlm.go
Labels: approved, lgtm, ok-to-test, size/XS

#483 bump version for replace image
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#500 change env var ODLM_SCOPE to ISOLATED_MODE
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
  testdata/deploy/deploy.yaml
Labels: approved, lgtm, size/L

#502 convert operator itself's catalogsource
  controllers/bootstrap/init.go
  main.go
Labels: approved, lgtm, ok-to-test, size/M

#503 apply template to ibm-common-services-cluster-admin
  controllers/constant/constant.go
Labels: approved, lgtm, size/XS
