Repository IBM/ibm-common-service-operator, pull requests merged in 2022-04, with the labels that each got.

#769 bump version to 3.18
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#770 enable multi-instance for common ui
  controllers/constant/multipleInstancesEnabled.go
Labels: size/XS, approved

#772 add license.accept field
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  common/Makefile.common.mk
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/render_template.go
Labels: lgtm, approved, size/M

#774 update CRD to remove the object check
  bundle/manifests/operator.ibm.com_commonservices.yaml
Labels: lgtm, size/XS, approved

#775 check and delete cs operator creates by OLM dependency
  common/config/.golangci.yml
  controllers/bootstrap/init.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, size/M

#777 Add License accept to install doc
  docs/install.md
Labels: lgtm, size/S, approved

#776 set cs operator to manual approval when "installPlanApproval: Automatic"
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#778 move to ICR registry
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: lgtm, approved, size/M
