Repository IBM/ibm-common-service-operator, pull requests merged in 2022-03, with the labels that each got.

#756 add turbonomic template
  turbonomic/README.md
  turbonomic/orm-audit-logging.yaml
  turbonomic/orm-auth-idp.yaml
  turbonomic/orm-auth-pap.yaml
  turbonomic/orm-auth-pdp.yaml
  turbonomic/orm-cert-manager.yaml
  turbonomic/orm-common-web-ui.yaml
  turbonomic/orm-ibm-licensing-service-instance.yaml
  turbonomic/orm-ibm-monitoring-grafana.yaml
  turbonomic/orm-icp-mongodb.yaml
  turbonomic/orm-management-ingress.yaml
  turbonomic/orm-must-gather-service.yaml
  turbonomic/orm-nginx-ingress.yaml
  turbonomic/orm-oidcclient-watcher.yaml
  turbonomic/orm-platform-api.yaml
  turbonomic/orm-policy-controller.yaml
  turbonomic/orm-secret-watcher.yaml
  turbonomic/orm-system-healthcheck-service.yaml
Labels: lgtm, size/L

#758 bump version to 3.16.1
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#759 update replace to 3.15.1
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#760 bump version to 3.17.0
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#761 bump efix versions for 3.16.2 fix
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#763 add script for upgrade of manual approval mode
  installplan_approval.sh
  operator_checker_patch.sh
Labels: lgtm, size/L

#766 Bump version to 3.19
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/odlm.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#768 clean up cluster when running script in force mode
  force-uninstall.sh
Labels: size/M
