Repository IBM/ibm-common-service-operator, pull requests merged in 2022-11, with the labels that each got.

#906 pin Bedrock services to v3.22 channel except for installer
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#907 updated digest value for license provider image
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#894 remove crossplane provider operator
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/bootstrap/init.go
  controllers/constant/crossplane.go
Labels: lgtm, size/L, approved

#911 fipsEnable should be consistent with previous name
  controllers/constant/fipsEnable.go
Labels: lgtm, size/XS, approved

#913 migrate from v1alpha1 Certs to v1 Certs
  controllers/bootstrap/init.go
  controllers/constant/certmanager.go
  controllers/goroutines/cleanup_deprecated_services.go
Labels: lgtm, size/L, approved

#909 remove existing odlm managed nss crs
  convert_to_multi_instance.sh
Labels: lgtm, size/S

#905 check that ns in cm exist, create them if they don't
  convert_to_multi_instance.sh
Labels: lgtm, size/M

#918 properly handle an op group already existing
  convert_to_multi_instance.sh
Labels: lgtm, size/S, approved

#917 handle nss deletion error when nss not present
  convert_to_multi_instance.sh
Labels: lgtm, approved, size/M

#919 goroutine enhancement
  controllers/goroutines/namespacescope.go
Labels: lgtm, approved, size/M

#922 update output messages, add version
  convert_to_multi_instance.sh
Labels: lgtm, approved, size/M

#923 tech preview of backup and restore yaml
  velero/backup/backup.yaml
  velero/backup/holdForBackupPod.yaml
  velero/restore/restore-catalog.yaml
  velero/restore/restore-commonservice.yaml
  velero/restore/restore-entitlementkey.yaml
  velero/restore/restore-iam.yaml
  velero/restore/restore-operands.yaml
  velero/restore/restore-operatorgroup.yaml
  velero/restore/restore-pull-secret.yaml
  velero/restore/restore-subscriptions.yaml
Labels: lgtm, size/L

#924 add mongodb files
  velero/backup/mongoDB/mongo-backup.sh
  velero/backup/mongoDB/mongodbbackup.yaml
  velero/restore/mongoDB/mongo-restore.sh
  velero/restore/mongoDB/mongodbrestore.yaml
  velero/restore/mongoDB/set_access.js
Labels: lgtm, size/L

#914 cleanup zen instances before conversion
  convert_to_multi_instance.sh
Labels: lgtm, size/M

#925 Automate the Mongodb Backup and Restore Steps
  backup_restore_mongo.sh
  convert_to_multi_instance.sh
  velero/backup/mongoDB/mongo-backup.sh
Labels: size/L, do-not-merge/hold

#929 New prow cluster
  common/Makefile.common.mk
Labels: lgtm, size/XS, approved

#930 New prow cluster name
  common/Makefile.common.mk
Labels: lgtm, size/XS, approved

#928 implement operandrequest webhook
  Makefile
  api/v3/commonservice_types.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/manifests/webhook-service_v1_service.yaml
  bundle/metadata/annotations.yaml
  bundle/metadata/dependencies.yaml
  common/Makefile.common.mk
  config/certmanager/certificate.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_commonservices.yaml
  config/crd/patches/webhook_in_commonservices.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/commonservice_controller_test.go
  controllers/operandconfig.go
  controllers/webhook/operandrequest/mutatingwebhook.go
  go.mod
  go.sum
  main.go
  testdata/deploy/deploy.yaml
Labels: size/XXL, lgtm, approved

#931 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#932 remove quay image build support
  Makefile
Labels: lgtm, size/XS, approved

#933 add Crossplane functionality back
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, size/L, approved

#934 add NSS ConfigMap synchronization
  controllers/goroutines/namespacescope.go
  main.go
Labels: lgtm, approved, size/M

#936 deploy certificates without IBM dependencies
  controllers/bootstrap/init.go
  controllers/constant/certmanager.go
Labels: lgtm, size/L, approved

#937 install IAM from channel v4.0
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#940 install ui from channel v4.0
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#938 reduce cluster permission
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/goroutines/cleanup_deprecated_services.go
  controllers/operandconfig.go
  main.go
Labels: lgtm, approved, size/XL

#941 drop compatibility for upgrading from cs 3.4
  controllers/bootstrap/init.go
Labels: lgtm, size/S, approved
