Repository IBM/ibm-common-service-operator, pull requests merged in 2022-05, with the labels that each got.

#779 Clean up deprecated services resources
  controllers/goroutines/cleanup_deprecated_services.go
  main.go
Labels: lgtm, size/L, approved

#780 update nss api
  controllers/goroutines/namespacescope.go
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#781 check DeletionTimestamp of the object in the cluster
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#783 add replaces back to CSV
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#786 add bluzarraga to owners
  OWNERS
Labels: lgtm, size/XS, approved

#789 bump version to 3.19.0
  OWNERS
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#790 Remove the check for secret-watcher in Project K
  controllers/bootstrap/init.go
  controllers/goroutines/check_iam.go
Labels: lgtm, size/XS, approved

#791 add licensing annotation into pre-zen-operand-config-job
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#793 Exclude red hat provided catalogsource from GetCatalogSource
  controllers/common/util.go
Labels: lgtm, size/XS, approved
