Repository IBM/ibm-common-service-operator, pull requests merged in 2022-10, with the labels that each got.

#884 Fix licensing re-install
  convert_to_multi_instance.sh
Labels: lgtm, size/S, approved

#872 apply approval mode change in control namespace
  controllers/bootstrap/init.go
  main.go
Labels: lgtm, approved, size/M

#875 keep the newest verison of NSS in controlNS
  controllers/bootstrap/init.go
Labels: lgtm, approved, size/M

#890 bump version to 3.19.6
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#891 switch channel of zen cpp operator version back to current one
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#888 crossplane cr clean for LTSR
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: lgtm, size/L, approved

#886 delete crossplane cr
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: lgtm, size/L, approved

#893 bump db2u channel to v2.2
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#892 fix fipsEnabled issue in LTSR
  controllers/operandconfig.go
  controllers/rules/resource_comparison.go
  controllers/rules/rules.go
Labels: lgtm, size/S, approved

#877 fipsEnable
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/constant/fipsEnable.go
  controllers/operandconfig.go
  controllers/render_template.go
  controllers/rules/resource_comparison.go
  controllers/rules/rules.go
Labels: lgtm, approved, size/M

#897 fix for odlm scale down
  upgrade_common_services.sh
Labels: lgtm, approved, size/M

#899 fix odlm risk for airgap upgrade
  upgrade_common_services_airgap.sh
Labels: lgtm, approved, size/M

#896 Make approval mode dynamic instead of hardcoded
  controllers/bootstrap/init.go
  controllers/constant/crossplane.go
  controllers/constant/ibmcloud.go
  controllers/constant/namespace.go
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#898 make approval mode dynamic instead of hardcoded
  controllers/bootstrap/init.go
  controllers/constant/crossplane.go
  controllers/constant/ibmcloud.go
  controllers/constant/namespace.go
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#902 added runAsNonRoot to secretshare and webhook
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
Labels: lgtm, size/XS, approved

#901 update protobuf to 1.3.2
  go.mod
Labels: lgtm, approved

#900 Re-implement online upgrade
  upgrade_common_services.sh
Labels: lgtm, size/L, approved

#903 Re-implement offline upgrade
  upgrade_common_services_airgap.sh
Labels: lgtm, size/L, approved

#904 detect zen current version
  upgrade_common_services.sh
Labels: lgtm, size/XS, approved
