Repository IBM/ibm-common-service-operator, pull requests merged in 2022-07, with the labels that each got.

#804 update channel to 3.20
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#805 Revert "Add network policy for CPNS access from CSNS"
  networkpolicy/bedrock-allow-cpns-access-from-csns.yaml
Labels: lgtm, size/S

#810 update zen cpp to channel v3.20
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#811 deploy crossplane in control ns if multi instance
  controllers/bootstrap/init.go
  controllers/constant/crossplane.go
Labels: lgtm, approved, size/M

#812 updated db2u channel from v1.1 to v2.0
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#808 compatibility clause to CS CRDs
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
Labels: lgtm, size/XS, approved

#801 update installplan
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  main.go
Labels: lgtm, approved, size/M

#815 deprecated service cleaned after OperandRegistry is updated to upgrade
  controllers/bootstrap/init.go
  controllers/goroutines/cleanup_deprecated_services.go
Labels: lgtm, approved, size/M

#818 Crossplane fix to replace 814
  controllers/bootstrap/init.go
  controllers/constant/crossplane.go
Labels: lgtm, size/L, approved

#819 install NSS in control NS for multi instance
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/namespace.go
Labels: lgtm, size/L, approved

#820 bump cs ltsr to 3.19.2
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#821 delete crossplane from control namespace
  controllers/commonservice_controller.go
Labels: lgtm, size/XS, approved

#825 create control namespace in bootstrap
  controllers/bootstrap/init.go
  main.go
Labels: lgtm, approved, size/M

#827 make createOrUpdateFromYaml generic to include control ns
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#828 Flip bool values in CompareChannel function
  controllers/bootstrap/init.go
Labels: lgtm, size/S, approved

#829 bump ltsr version to 3.19.3
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#831 script for upgrading common service to 3.20
  upgrade_common_services.sh
Labels: lgtm, size/L, approved

#834 update operand version
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: lgtm, size/S, approved

#835 fix upgrade issue for Zen
  upgrade_common_services.sh
Labels: lgtm, approved, size/M

#836 Subscription check enhancement
  controllers/bootstrap/init.go
  controllers/constant/constant.go
  main.go
Labels: lgtm, size/L, approved

#837 remove duplicate code
  controllers/bootstrap/init.go
Labels: lgtm, approved, size/M
