Repository IBM/ibm-common-service-operator, pull requests merged in 2022-02, with the labels that each got.

#739 Include network policies for Bedrock
  networkpolicy/README.md
  networkpolicy/bedrock-access-to-apicatalog-controller.yaml
  networkpolicy/bedrock-access-to-auth-idp.yaml
  networkpolicy/bedrock-access-to-auth-mongo.yaml
  networkpolicy/bedrock-access-to-auth-pap.yaml
  networkpolicy/bedrock-access-to-auth-pdp.yaml
  networkpolicy/bedrock-access-to-cert-manager-webhook.yaml
  networkpolicy/bedrock-access-to-common-audit-logging.yaml
  networkpolicy/bedrock-access-to-common-web-ui.yaml
  networkpolicy/bedrock-access-to-default-http-backend.yaml
  networkpolicy/bedrock-access-to-iam-policy-controller.yaml
  networkpolicy/bedrock-access-to-ibm-cs-webhook.yaml
  networkpolicy/bedrock-access-to-license-service-reporter.yaml
  networkpolicy/bedrock-access-to-license-service.yaml
  networkpolicy/bedrock-access-to-management-ingress.yaml
  networkpolicy/bedrock-access-to-monitoring-grafana-service.yaml
  networkpolicy/bedrock-access-to-mustgather-service.yaml
  networkpolicy/bedrock-access-to-nginx-ingress-controller.yaml
  networkpolicy/bedrock-access-to-oidcclient-watcher.yaml
  networkpolicy/bedrock-access-to-platform-api.yaml
  networkpolicy/bedrock-access-to-prometheus.yaml
  networkpolicy/bedrock-access-to-secret-watcher.yaml
  networkpolicy/bedrock-access-to-system-healthcheck-service.yaml
  networkpolicy/bedrock-access-to-thanosproxy.yaml
  networkpolicy/bedrock-allow-icpmemcached-access-from-systemhealthcheck.yaml
  networkpolicy/bedrock-allow-webhook-access-from-apiserver.yaml
  networkpolicy/install_networkpolicy.sh
  networkpolicy/sdn-ovs-dashboard-cr.yml
  networkpolicy/zen-access-to-audit-svc.yaml
  networkpolicy/zen-access-to-nginx.yaml
  networkpolicy/zen-access-to-usermgmt.yaml
  networkpolicy/zen-access-to-zen-core-api.yaml
  networkpolicy/zen-access-to-zen-core.yaml
  networkpolicy/zen-access-to-zen-meta-api.yaml
  networkpolicy/zen-access-to-zen-metastore.yaml
  networkpolicy/zen-allow-iam-config-job.yaml
Labels: size/XXL

#740 keep deprecated services unchanged in upgrade
  force-uninstall.sh
  upgrade_to_continuous_delivery_airgap.sh
Labels: lgtm, approved, size/M

#742 bump version to 3.16.0
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#743 bump version to 3.6.9
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  version/version.go
Labels: lgtm, size/S, approved

#747 add OPERATORCHECKER_MODE flag for OperatorChecker
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#749 don't update resource being deleted
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#750 use string in subscriptjion.spec.env
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#751 create secretshare CR to share namespace-scope config to openshift-re…
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#748 stop certificate creation when it is BYOC scenario
  api/v3/commonservice_types.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  common/scripts/upgrade_to_continuous_delivery_airgap.sh
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/certmanager.go
  controllers/constant/constant.go
  controllers/goroutines/certmanager.go
  controllers/goroutines/cppConfig.go
  controllers/goroutines/variables.go
  controllers/rules/resource_comparison.go
  controllers/suite_test.go
  main.go
Labels: lgtm, size/L, approved

#752 add turbo profile controller for common service
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/operandconfig.go
  controllers/render_template.go
  controllers/rules/resource_comparison.go
  controllers/rules/rules.go
Labels: lgtm, size/L, approved

#753 add cluster permission for issuer and certificate
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/goroutines/namespacescope.go
Labels: lgtm, size/S, approved

#754 deploy cert-manager CR in master namespace
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
Labels: lgtm, size/S, approved
