Repository IBM/ibm-common-service-operator, pull requests merged in 2022-09, with the labels that each got.

#860 remove catalogsource switch logic
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: lgtm, size/L, approved

#863 Trim all characters 'v' and above in versions
  upgrade_common_services.sh
  upgrade_common_services_airgap.sh
Labels: lgtm, approved, size/M

#864 bump version to 3.19.5
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#867 update secretshare and webhook
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#847 multi-instance conversion script switch mode part
  convert_to_multi_instance.sh
Labels: lgtm, size/L

#869 added yaml file for community cert-manager installation to be include…
  cert-manager.yaml
Labels: size/XXL, lgtm, approved

#876 re-install all singleton services into control ns
  convert_to_multi_instance.sh
Labels: size/M

#878 bump version for 3.22.0
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#880 Enhance version bump script for cs operator
  common/scripts/next-csv.sh
Labels: lgtm, size/L, approved

#882 add ignore not found flag to deleting operandregistry and config
  convert_to_multi_instance.sh
Labels: lgtm, size/XS, approved
