Repository IBM/ibm-common-service-operator, pull requests merged in 2022-08, with the labels that each got.

#841 create new upgrade script for airgap env
  upgrade_common_services_airgap.sh
Labels: lgtm, size/L

#843 initial multi-instance script
  convert_to_multi_instance.sh
Labels: lgtm, approved, size/M

#845 bump efix version to 3.20.1
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#842 bump version to 3.21
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#846 update sub channel, hardcode zen @3.20 for now
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/odlm.go
  testdata/deploy/deploy.yaml
Labels: lgtm, size/S, approved

#824 adding licensing annotations for pre-zen-config
  controllers/constant/odlm.go
Labels: lgtm, size/XS, needs-ok-to-test, approved

#849 add product annotation for postgresql job
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#833 Subscription check enhancement
  controllers/bootstrap/init.go
  main.go
Labels: lgtm, approved, size/M

#851 compare channel version before switch channel
  upgrade_common_services.sh
Labels: lgtm, size/M

#853 Fix bad indentation for SaaS OperandConfig
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#855 channel version check in airgap upgrade script
  upgrade_common_services.sh
  upgrade_common_services_airgap.sh
Labels: lgtm, approved, size/M

#856 exclude community catalogSource
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved
