Repository IBM/ibm-common-service-operator, pull requests merged in 2022-01, with the labels that each got.

#718 remove deprecated operators - exporter & prometheus
  controllers/constant/odlm.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  testdata/actual.yaml
  testdata/expected.yaml
Labels: size/XXL, lgtm, approved

#719 Use SaaS specified OperandRegistry
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#720 remove redis
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#711 add Crossplane Providers
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/crossplane.go
Labels: lgtm, size/L, approved

#722 remove spark
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#724 Onboard pre-zen job
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
  testdata/deploy/deploy.yaml
Labels: lgtm, size/L, approved

#723 display operator overall status in cs cr status
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/goroutines/operator_status.go
Labels: lgtm, size/S, approved

#725 update crossplane providers' subscriptions
  controllers/constant/crossplane.go
Labels: lgtm, size/XS, approved

#726 align the subscription name on deleting Crossplane
  controllers/bootstrap/init.go
  controllers/constant/crossplane.go
  controllers/goroutines/operator_status.go
Labels: lgtm, approved, size/M

#727 Don't check zen
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#728 Extend clusterRole to install Crossplane providerConfig
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, approved, size/M

#729 loop checking clustertype instead exit 1
  main.go
Labels: lgtm, size/S, approved

#730 add env into zen job
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#703 add rollback script from CD to EUS
  common/scripts/rollback_to_eus.sh
  common/scripts/upgrade_to_continuous_delivery_airgap.sh
Labels: lgtm, size/L, approved

#732 All CS CRs are inScope in single deployment
  controllers/operandconfig.go
Labels: lgtm, size/XS, approved

#731 indicate deployment mode in logs
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#734 Update Copyright to 2022
  Makefile
  api/v3/commonservice_types.go
  api/v3/groupversion_info.go
  api/v3/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/artifactory_config_docker.sh
  common/scripts/force-uninstall.sh
  common/scripts/gobuild.sh
  common/scripts/health-check.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint-csv.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/next-csv.sh
  common/scripts/quay_config_docker.sh
  common/scripts/update_catalogsource.sh
  controllers/bootstrap/init.go
  controllers/check/check_iam.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/commonservice_controller_test.go
  controllers/constant/constant.go
  controllers/constant/namespace.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  controllers/constant/yaml.go
  controllers/deploy/manager.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/storageclass/storageclass.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
  version/version.go
Labels: lgtm, approved, size/M

#735 crypto update for CVE-2020-29652
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#736 add permission to create event
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#737 bump version to 3.18
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/L, approved

#738 fix apar from GM
  controllers/constant/crossplane.go
Labels: lgtm, size/XS, approved
