Repository IBM/ibm-common-service-operator, pull requests merged in 2023-05, with the labels that each got.

#1190 make sure three cert manger pods are deleted when deactivating cp2 cert manager
  cp3pt0-deployment/common/migrate_singleton.sh
Labels: lgtm, size/S, approved

#1189 crossplane subscription check
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, approved, size/M

#1182 accept the license for cert manager, cs op, nss, and licensing based on parameter
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1191 Update default value for LICENSE_ACCEPT
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1194 Patch CommonService CR before install CS operator
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1195 change namespace name
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#1188 move uninstall singletons to after csmaps created, check for cert manager pods to be running
  isolate.sh
  rollback-multi-instance.sh
Labels: lgtm, approved, size/M

#1196 rewrite configuration status structure in CommonService CRs
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
Labels: lgtm, size/L, approved

#1199 remove WebhookConfiguration to unblock CR update
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1200 update BTS OperandRequest with ibm-im-operator included
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1204 ignore license accept in check mode
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1171 only check for iam when a zenservice has requested it
  convert_to_multi_instance.sh
Labels: lgtm, size/S, approved

#1203 update renewBefore time to 8 months
  controllers/constant/certmanager.go
Labels: lgtm, size/XS, approved

#1208 Make parameters more clear by specifying servicesNamespace as "to namespace"
  preload_data.sh
Labels: lgtm, size/XS, approved

#1209 change cert manager cr to full name
  convert_to_multi_instance.sh
  isolate.sh
  rollback-multi-instance.sh
Labels: lgtm, size/XS, approved

#1211 add flags back to parameters
  preload_data.sh
Labels: lgtm, size/S, approved

#1212 change backup image to existing mongo image
  preload_data.sh
Labels: lgtm, size/XS, approved

#1206 update install mode with manual option
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1218 sync dev with scripts
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  preload_data.sh
Labels: lgtm, approved, size/M

#1219 bump version to 3.19.12
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1220 bump version to 3.23.4
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1217 move webhook cleanup to immediately after pause
  isolate.sh
Labels: lgtm, size/XS, approved

#1216 creating EDB license key in operator namespace
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1230 wait for licensing instance to be created before accepting license
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#1231 update default cert manager source name
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/XS, approved

#1207 pre-requisite check for channel and profile size
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1225 ensure ldaps secret exists in target namespace after restore
  backup_restore_mongo.sh
  preload_data.sh
Labels: lgtm, size/S, approved

#1232 sync scripts 2023-05-12
  backup_restore_mongo.sh
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  preload_data.sh
Labels: lgtm, approved, size/M

#1234 fix syntax issue
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1214 Avoid cluster permission
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1192 Update script description to be more clear
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  isolate.sh
Labels: lgtm, approved, size/M

#1242 [3.19] update imagePullPolicy to IfNotPresent
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1241 [3.23] update imagePullPolicy to IfNotPresent
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1245 uninstall and force uninstall script
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/uninstall_tenant.sh
Labels: lgtm, size/L, approved

#1240 Enable Licensing Service Migration
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/XS, approved

#1244 skip restarting cert-manager if it not installed
  cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
Labels: lgtm, size/S, approved

#1239 Check if cert manager is deployed in the instance that it is not requested (excluded-ns edge case)
  isolate.sh
Labels: lgtm, approved, size/M

#1237 make preload data roks compatible
  preload_data.sh
Labels: lgtm, size/S, approved

#1247 move ns existence check earlier in script
  isolate.sh
Labels: lgtm, size/XS, approved

#1250 don't remove IBMLicensing singleton CR which has customisations
  isolate.sh
Labels: lgtm, size/XS, approved

#1228 Implement Concatenating OperandRegistry YAMLs
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: size/XXL, lgtm, approved

#1249 setup_tenant.sh: change --tenant-namespaces to not require entire tenant list, add --excluded-namespaces parameter
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1193 BYOCA enhancement
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, size/S, approved

#1257 exclude cp automation CatalogSource
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1255 preload: change restore image to existing mongo
  preload_data.sh
Labels: lgtm, size/XS, approved

#1256 add resource limits and requests to backup restore jobs
  preload_data.sh
Labels: lgtm, size/S, approved

#1258 retry patch commonservice cr for webhook issue
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1261 Cover corner case for fresh install without CRD
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1262 match admin pass to original
  preload_data.sh
Labels: lgtm, size/XS, approved

#1260 Patch finalizer for licensing OperandBindInfo
  cp3pt0-deployment/common/migrate_singleton.sh
  isolate.sh
Labels: lgtm, size/S, approved

#1254 Bug/58774: finalizer needs to be removed for licensing OperandBindInfo
  cp3pt0-deployment/common/migrate_singleton.sh
  isolate.sh
Labels: lgtm, size/S, approved

#1263 clean up the resources when services ns is changed
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/certmanager.go
Labels: lgtm, approved, size/M

#1264 Bug/58774 properly backup/restore LicenseService CR at upgrade
  cp3pt0-deployment/common/migrate_cp2_licensing.sh
  cp3pt0-deployment/common/migrate_singleton.sh
  isolate.sh
Labels: lgtm, size/M

#1266 redirect output to a log file
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  cp3pt0-deployment/uninstall_tenant.sh
  isolate.sh
  preload_data.sh
Labels: lgtm, size/L, approved

#1269 make sed command compatible with both macOS and Linux
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#1271 Creating and updating common-service-maps when reconciling master CS CR
  controllers/commonservice_controller.go
  main.go
Labels: lgtm, approved, size/M

#1213 edit odlm sub in place
  convert_to_multi_instance.sh
  isolate.sh
  rollback-multi-instance.sh
Labels: lgtm, size/L, approved

#1246 Initial upload of CP3 network policies
  cp3-networkpolicy/README.md
  cp3-networkpolicy/ingress/cert-manager/allow-webhook-access-from-apiserver.yaml
  cp3-networkpolicy/ingress/cert-manager/bedrock-access-to-cert-manager-webhook.yaml
  cp3-networkpolicy/ingress/license-service/bedrock-access-to-license-service-reporter.yaml
  cp3-networkpolicy/ingress/license-service/bedrock-access-to-license-service.yaml
  cp3-networkpolicy/ingress/operators/access-to-edb-postgres-webhooks.yaml
  cp3-networkpolicy/ingress/operators/access-to-ibm-common-service-operator.yaml
  cp3-networkpolicy/ingress/operators/access-to-zen-meta-api.yaml
  cp3-networkpolicy/ingress/operators/allow-webhook-access-from-apiserver.yaml
  cp3-networkpolicy/ingress/services/access-to-common-web-ui.yaml
  cp3-networkpolicy/ingress/services/access-to-edb-postgres.yaml
  cp3-networkpolicy/ingress/services/access-to-icp-mongodb.yaml
  cp3-networkpolicy/ingress/services/access-to-platform-auth-service.yaml
  cp3-networkpolicy/ingress/services/access-to-platform-identity-management.yaml
  cp3-networkpolicy/ingress/services/access-to-platform-identity-provider.yaml
  cp3-networkpolicy/ingress/services/zen-access-to-audit-svc.yaml
  cp3-networkpolicy/ingress/services/zen-access-to-nginx.yaml
  cp3-networkpolicy/ingress/services/zen-access-to-usermgmt.yaml
  cp3-networkpolicy/ingress/services/zen-access-to-zen-core-api.yaml
  cp3-networkpolicy/ingress/services/zen-access-to-zen-core.yaml
  cp3-networkpolicy/ingress/services/zen-access-to-zen-minio.yaml
  cp3-networkpolicy/ingress/services/zen-access-to-zen-volumes.yaml
  cp3-networkpolicy/ingress/services/zen-access-to-zen-watchdog.yaml
  cp3-networkpolicy/ingress/services/zen-allow-iam-config-job.yaml
  cp3-networkpolicy/install_networkpolicy.sh
Labels: lgtm, approved, size/XL

#1265 Uninstall ODLM from servicesNs in all SoD scenario
  controllers/bootstrap/init.go
Labels: lgtm, size/S, approved

#1268 Bug/58774: re-fix of license service migration with customisation preserved
  cp3pt0-deployment/common/migrate_cp2_licensing.sh
  cp3pt0-deployment/common/migrate_singleton.sh
Labels: lgtm, size/S, approved

#1273 move debug1 function to utils.sh
  cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
  cp3pt0-deployment/common/migrate_cp2_licensing.sh
  cp3pt0-deployment/common/migrate_singleton.sh
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  cp3pt0-deployment/uninstall_tenant.sh
  isolate.sh
  preload_data.sh
Labels: lgtm, approved, size/M

#1274 check for ibmlicensing resource to exist before backup
  isolate.sh
Labels: lgtm, size/XS, approved

#1275 add 4.0.0 tag back to related images
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1276 wait for namespace-scope cm to match expected value after isolation
  isolate.sh
Labels: lgtm, approved, size/M

#1267 Enhance force uninstallation
  cp3pt0-deployment/uninstall_tenant.sh
Labels: lgtm, size/S, approved

#1278 fix scale down function for csv and deployment missing
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#1279 fix typo
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1280 support both bash and Bourne shell
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#1277 align name of cp3 mongodb operator with im operator
  controllers/constant/odlm.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: lgtm, approved, size/XL

#1282 rename related images
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1259 Generalize copy function, add more customization resources to copy over
  preload_data.sh
Labels: lgtm, approved, size/M

#1283 Update ImagePullPolicy to IfNotPresent
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  testdata/deploy/deploy.yaml
Labels: lgtm, size/XS, approved

#1284 Add label selector to filter out cloned CS CRs
  controllers/bootstrap/init.go
  controllers/operandconfig.go
Labels: lgtm, size/S, approved

#1287 update go to latest for twistlock scan
  Dockerfile
Labels: lgtm, size/XS, approved

#1291 copy oidc secret
  preload_data.sh
Labels: lgtm, size/XS, approved

#1289 change where comma is set to sidestep issue
  isolate.sh
Labels: size/S, approved
