Repository IBM/ibm-common-service-operator, pull requests merged in 2023-06, with the labels that each got.

#1293 add platform-auth-idp cm to copied over resources
  preload_data.sh
Labels: lgtm, size/XS, approved

#1290 always call wait for certmanager function
  isolate.sh
Labels: lgtm, approved, size/M

#1294 check cs operator version in all namespaces in isolate.sh
  isolate.sh
Labels: lgtm, size/S, approved

#1296 update edb license job digest
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1299 update the placement for -A and remove regular exp
  isolate.sh
Labels: lgtm, size/XS, approved

#1300 Check if IBMLicensing CRD exists or not
  isolate.sh
Labels: lgtm, size/XS, approved

#1303 Check if IBMLicensing CRD exists or not (#1300)
  isolate.sh
Labels: lgtm, size/XS, approved, do-not-merge/hold

#1302 check for cs op and odlm to be scaled after failure
  isolate.sh
Labels: lgtm, approved, size/M

#1305 check for cs op and odlm to be scaled after failure (#1302)
  isolate.sh
Labels: size/M, do-not-merge/hold

#1310 bump version to 3.19.13
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1309 bump version to 3.23.5
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1308 z specific changes to preload process
  preload_data.sh
Labels: lgtm, approved, size/XL

#1311 z specific changes to preload process (#1308)
  preload_data.sh
Labels: approved, size/XL, do-not-merge/hold

#1297 [LTSR] allow multiple opbi
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1298 [323] allow multiple opbi
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1312 [CS LTSR] "disconnected" annotation for assessment
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1313 [CS 323] "disconnected" annotation for assessment
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1314 Update EDB License Image
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1226 cs operator should laways deploy certmanager cr if crd exist
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, approved, size/M

#1316 fix bug in conversion script
  convert_to_multi_instance.sh
Labels: lgtm, size/XS, approved

#1317 [BD 4.1] specify namespace for Cert Manager checking
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1318 creating namespaces in pre-req
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1319 Update go to 1.20.5
  Dockerfile
Labels: lgtm, size/XS, approved

#1320 update go to 1.20.5
  Dockerfile
Labels: lgtm, size/XS, approved

#1321 bump up version to 4.1.0
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1323 Update golang image to bullseye base
  Dockerfile
Labels: lgtm, size/XS, approved

#1286 [Bedrock 4.1] "disconnected" annotation for certification assessment
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1322 [4.1] Make podrestart label more accurate
  controllers/cert-manager/podrefresh_controller.go
Labels: lgtm, size/S, approved

#1326 [Fixpack 323] Update EDB License Image
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1327 [LTSR] Update EDB License Image
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1324 Update golang image to bullseye base
  Dockerfile
Labels: lgtm, size/XS, approved

#1325 Update golang image to bullseye base
  Dockerfile
Labels: lgtm, size/XS, approved

#1328 Update channel to v4.1
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: lgtm, size/S, approved

#1329 remove internal URL for lint error
  cp3pt0-deployment/uninstall_tenant.sh
Labels: lgtm, size/XS, approved

#1288 [Bedrock 4.1] Implement Concatenating OperandConfig YAMLs
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1334 Remove additional space to fix yaml format issue
  controllers/size/large_ppc64le.go
Labels: lgtm, size/XS, approved

#1332 fix bug in conversion script
  convert_to_multi_instance.sh
Labels: lgtm, size/XS, approved

#1330 Update backup and restore mongo script to work on ROKS and Z
  backup_restore_mongo/backup_restore_mongo.sh
  backup_restore_mongo/mongo-backup.sh
  backup_restore_mongo/mongo-restore.sh
  backup_restore_mongo/mongodbbackup-z.yaml
  backup_restore_mongo/mongodbbackup.yaml
  backup_restore_mongo/mongodbrestore-z.yaml
  backup_restore_mongo/mongodbrestore.yaml
  backup_restore_mongo/pvc.yaml
  backup_restore_mongo/set_access.js
  preload_data.sh
  velero/backup/mongoDB/README.md
  velero/backup/mongoDB/mongo-backup.sh
  velero/restore/mongoDB/README.md
Labels: lgtm, approved, size/XL

#1238 only wait for iam if it's requested during rollback
  convert_to_multi_instance.sh
  rollback-multi-instance.sh
Labels: lgtm, approved, size/M

#1335 updated go version to 1.20.5
  Dockerfile
Labels: lgtm, size/XS, approved
