Repository IBM/ibm-common-service-operator, pull requests merged in 2023-02, with the labels that each got.

#1007 bump management ingress operator to v4.0 channel
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1008 port cert-rotation from Bedrock cert-manager
  .gitignore
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/podrefresh_controller.go
  controllers/cert-manager/suite_test.go
  controllers/cert-manager/v1_add_label_controller.go
  go.mod
  go.sum
  main.go
Labels: size/XXL, lgtm, approved

#1011 remove zen APIKey from OperandConfig
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1010 removed unnecessary stringify
  controllers/constant/commonservice.go
  controllers/constant/constant.go
  controllers/constant/crossplane.go
  controllers/constant/ibmcloud.go
  controllers/constant/namespace.go
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1012 discontinue management-ingress, audit logging and ingress-nginx
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1006 [future] support numeric ns
  controllers/constant/certmanager.go
  controllers/constant/constant.go
  controllers/constant/crossplane.go
  controllers/constant/namespace.go
  controllers/constant/odlm.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  docs/cloudpak-integration.md
Labels: lgtm, size/L, approved

#1013 remove nss synchronization with OperatorGroup
  controllers/bootstrap/init.go
  controllers/constant/namespace.go
  main.go
Labels: lgtm, approved, size/M

#1014 mark tombstone for cert-manager
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#974 use fullname with api name for oc get commands
  upgrade_common_services.sh
Labels: lgtm, size/S, approved

#982 [airgap upgrade] use fullname for oc get commands
  upgrade_common_services_airgap.sh
Labels: lgtm, size/S, approved

#1015 update cache for AllNamespace Installation mode
  controllers/bootstrap/init.go
  main.go
Labels: lgtm, size/S, approved

#1016 bump MongoDB channel to v4.0
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1017 [ltsr upgrade] enhance upgrade script with all channels switched
  upgrade_common_services_ltsr.sh
Labels: lgtm, approved, size/XL

#1018 remove CSV dependency on ODLM, instead installing ODLM in runtime
  bundle/metadata/dependencies.yaml
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1019 remove redundant components
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/podrefresh_controller.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/constant/crossplane.go
  controllers/constant/secretshare.go
  controllers/constant/yaml.go
  controllers/goroutines/operator_status.go
Labels: lgtm, approved, size/XL

#1020 create ibm-cpp-config configmap in servicesNamespace
  controllers/bootstrap/init.go
  controllers/goroutines/cppConfig.go
  main.go
Labels: lgtm, size/S, approved

#1021 Update status check on deployed services
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, size/S, approved

#1022 Delete upgrade_common_services_future.sh
  upgrade_common_services_future.sh
Labels: lgtm, size/L, approved

#1025 add cs operator and odlm in nss annotation
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1028 port ltsr into online and offline upgrade scripts
  upgrade_common_services.sh
  upgrade_common_services_airgap.sh
Labels: lgtm, size/L, approved

#1031 create common service maps with cp3.0 installation
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/constant.go
  main.go
Labels: lgtm, approved, size/M

#1030 update pkg for twistlock
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#1032 Decouple licensing operator installation from ODLM
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1023 [CP3.0] reimplement operandrequest mutating webhook
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/manifests/webhook-service_v1_service.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/common/cache.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/webhooks/operandrequest/mutatingwebhook.go
  controllers/webhooks/operator_webhooks.go
  controllers/webhooks/reconciler.go
  controllers/webhooks/rules.go
  controllers/webhooks/webhook_register.go
  main.go
Labels: size/XXL, lgtm, approved

#1033 support advance topology by copying default CommonService CR to each watch_namespace
  Makefile
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/bootstrap/init.go
  controllers/common/cache.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/constant/webhook.go
  controllers/webhooks/operator_webhooks.go
  controllers/webhooks/reconciler.go
  main.go
Labels: size/XXL, lgtm, approved

#1034 mark tombstone for monitoring-grafana operator
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1037 add new entry for ibm-platformui-operator
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1038 update pkg for twistlock
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#1039 remove existing references on v3.x operator
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1041 set resourceVersion before updating an CR
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#1040 add new entry for im-operator-v4.0 in size and rules
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: lgtm, approved, size/XL

#1035 mark tombstone for zen, iam operators
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#967 Update conversion process to make it more fail tolerant and increase stability
  backup_restore_mongo.sh
  convert_to_multi_instance.sh
  rollback-multi-instance.sh
  uninstall-dedicated-cs-instance.sh
Labels: lgtm, approved, size/XL

#1043 open nginx ingress to every ns
  networkpolicy/zen-access-to-nginx.yaml
Labels: lgtm, size/XS, approved

#1044 mark tombstone for ibm-healthcheck-operator
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1046 Update cp3pt0 deployment folder
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/XL

#1048 Update common-service-maps ConfigMap
  controllers/common/util.go
  main.go
Labels: lgtm, approved, size/M
