Repository IBM/ibm-common-service-operator, pull requests merged in 2023-04, with the labels that each got.

#1120 rename dafaultAdminUser in CommonService CR
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/render_template.go
Labels: lgtm, approved, size/M

#1122 Remove cert manager subscription check
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1125 update licensing operator pkg name
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#1128 remove "-app" for licensing csv check
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1121 change update strategy to recreate
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#1133 change update strategy to recreate in ltsr
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#1132 disable webhook in cncf
  controllers/commonservice_controller.go
  main.go
Labels: lgtm, size/S, approved

#1134 ensure isolated mode value is true in ODLM subscription
  isolate.sh
Labels: approved, size/M

#1130 Create backup_preload_mongo.sh
  backup_preload_mongo.sh
Labels: size/XXL, lgtm, approved

#1135 exclude its WATCH_NAMESPACE from existing common-service-maps entry, and create new entry
  controllers/common/util.go
Labels: lgtm, approved, size/M

#1129 Create isolate.sh
  isolate.sh
Labels: lgtm, approved, size/XL

#1127 share ibm-cpp-config to all WATCH_NAMESPACE
  controllers/bootstrap/init.go
  controllers/constant/constant.go
  controllers/goroutines/cppConfig.go
  controllers/goroutines/variables.go
  main.go
Labels: lgtm, approved, size/M

#1137 remove check for control namespace in isolate.sh
  isolate.sh
Labels: lgtm, size/XS, approved

#1140 bump version of Db2U up to v3.2 channel for 3.19.x
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1139 bump version of Db2U up to v3.2 channel for CS 3.23.x
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1123 add new networkpolicy
  networkpolicy/bedrock-access-to-ibm-common-service-operator.yaml
Labels: lgtm, size/S, approved

#1143 bump CS to 3.23.3
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1113 BYOC support without label
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, approved, size/M

#1141 Pass in a correct source name for cert manager argument
  cp3pt0-deployment/migrate_singleton.sh
Labels: lgtm, size/S, approved

#1136 use existing mongo images
  backup_preload_mongo.sh
Labels: lgtm, size/S, approved

#1147 migrate_singleton.sh should exit script and return error
  cp3pt0-deployment/migrate_singleton.sh
Labels: lgtm, size/XS, approved

#1146 continue to run the in-place upgrade script even the sub was updated
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, approved, size/M

#1114 add replicas check
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1144 add checks for existing cs maps
  isolate.sh
Labels: lgtm, size/L, approved

#1148 update go to 1.20.3
  Dockerfile
Labels: lgtm, size/XS, approved

#1153 migrate to aws 323
  common/Makefile.common.mk
Labels: lgtm, size/XS, approved

#1154 migrate to aws cp3
  common/Makefile.common.mk
Labels: lgtm, size/XS, approved

#1155 migrate to aws ltsr
  common/Makefile.common.mk
Labels: lgtm, size/XS, approved

#1157 remove ca label in cs-webhook-certificate
  controllers/constant/certmanager.go
Labels: lgtm, size/XS, approved

#1158 remove webhook and secretshare alongside other singletons
  convert_to_multi_instance.sh
  isolate.sh
Labels: lgtm, approved, size/M

#1159 check if podpreset exists to prevent script failures
  convert_to_multi_instance.sh
  isolate.sh
Labels: lgtm, size/S, approved

#1160 re-enable the size configuration for new CommonUI component
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: lgtm, size/L, approved

#1162 throw out error when webhook server fail to set up
  controllers/webhooks/operator_webhooks.go
  main.go
Labels: lgtm, size/XS, approved

#1156 isolated script idempotency
  csmaps_utils.sh
  isolate.sh
Labels: lgtm, approved, size/XL

#1163 remove exit code for webhook server
  controllers/webhooks/operator_webhooks.go
  main.go
Labels: lgtm, size/XS, approved

#1165 Revert change on CNCF support webhook
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/certmanager.go
  controllers/webhooks/operator_webhooks.go
  controllers/webhooks/webhookreconciler.go
  main.go
Labels: lgtm, size/L, approved

#1167 uninstall singletons immediately after pause
  isolate.sh
Labels: lgtm, size/XS, approved

#1168 remove iam migration job
  cp3pt0-deployment/common/cloudpak3-iam-migration-job.yaml
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, approved, size/M

#1166 yq not able to read json input causing line 633 to fail
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1170 update error message for licensing
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1161 Update Rollback script to be the reverse of the conversion script
  backup_restore_mongo.sh
  rollback-multi-instance.sh
Labels: lgtm, size/L, approved

#1164 Consolidate migrate_singleton.sh and setup_singleton.sh script
  cp3pt0-deployment/common/migrate_singleton.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/L, approved

#1172 support CP2 and CP3 Licensing co-existence
  cp3pt0-deployment/common/migrate_singleton.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#1174 make licensing migration optional
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1173 fixed isolate.sh to properly exclude namespaces
  isolate.sh
Labels: lgtm, size/XS, approved

#1169 deny updating in non master CommonService CR
  controllers/webhooks/commonservice/validatingwebhook.go
Labels: lgtm, approved, size/M

#1175 update licensing ns for migration
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/XS, approved

#1119 remove iam status check and ibm-common-services-status configmap
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/force-uninstall.sh
  common/scripts/rollback_to_eus.sh
  config/rbac/role.yaml
  controllers/goroutines/check_iam.go
  main.go
  testdata/README.md
  testdata/deploy/role.yaml
  testdata/deploy/role.yaml.bak
Labels: lgtm, size/L, approved

#1177 retry the subscription patch operation for 5 times
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, approved, size/M

#1178 parse install mode command-line argument
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/XS, approved

#1179 licensing-enhancement
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#1151 cleanup based on feedback
  backup_preload_mongo.sh
Labels: lgtm, size/S, approved

#1184 Revert "cleanup based on feedback"
  backup_preload_mongo.sh
Labels: lgtm, size/S, approved

#1185 update the replicas in a deployment section of CSV
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/L, approved

#1181 license acceptance idling changes
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/commonservice_controller.go
  controllers/constant/constant.go
Labels: lgtm, approved, size/M

#1187 tweaks based on CPD feedback
  isolate.sh
Labels: lgtm, size/XS, approved

#1186 preload config initial commit
  backup_preload_mongo.sh
  preload_data.sh
Labels: size/XXL, lgtm, approved
