Repository IBM/ibm-common-service-operator, pull requests merged in 2023-12, with the labels that each got.

#1666 Enable and Disable CS CR reconciliation in self-isolation
  controllers/common/util.go
  controllers/scopewatcher_controller.go
Labels: lgtm, approved, size/M

#1660 use new mongo image with new mongorestore and mongodump tools that utilize ssl on power/z clusters
  preload_data.sh
Labels: lgtm, size/L, approved

#1658 remove `service` namespace in secretshare default cr yaml
  controllers/constant/secretshare.go
Labels: lgtm, size/XS, approved

#1618 preload_data check yq version
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  cp3pt0-deployment/uninstall_tenant.sh
  isolate.sh
  preload_data.sh
Labels: lgtm, approved, size/M

#1669 remove `service` namespace in secretshare default cr yaml (#1658)
  controllers/constant/secretshare.go
Labels: lgtm, size/XS, approved

#1671 v3 operator update cs map to latest tenant namespaces during self-isolation process
  controllers/common/util.go
  controllers/scopewatcher_controller.go
Labels: lgtm, approved, size/M

#1665 Re-construct CP2 tenant scope in self-isolation
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/L, approved

#1672 Skip reconciliation if CR is not in tenant scope
  controllers/commonservice_controller.go
Labels: lgtm, size/XS, approved

#1670 Skip reconciliation if CR is not in tenant scope
  controllers/commonservice_controller.go
Labels: lgtm, size/XS, approved

#1674 [323] Enable and Disable CS CR reconciliation in self-isolation
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/L, approved

#1675 move csmap update to the end of self-isolation process
  controllers/scopewatcher_controller.go
Labels: lgtm, approved, size/M

#1667 Delete Crossplane, webhook, and secretshare deployment
  controllers/bootstrap/init.go
  controllers/goroutines/cleanup_deprecated_services.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/L, approved

#1679 [323] clean up resources
  controllers/bootstrap/init.go
  controllers/goroutines/cleanup_deprecated_services.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/L, approved

#1678 Update isolation condition
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/L, approved

#1680 Backup and Migrate Licensing Data
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/goroutines/cleanup_deprecated_services.go
  controllers/goroutines/operator_status.go
  controllers/operandconfig.go
  controllers/scopewatcher_controller.go
Labels: lgtm, approved, size/XL

#1681 Sync release-323 branch with LTSR branch
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/goroutines/cleanup_deprecated_services.go
  controllers/goroutines/operator_status.go
  controllers/operandconfig.go
  controllers/scopewatcher_controller.go
Labels: lgtm, approved, size/XL

#1659 Add Keycloak truststore configuration option
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1686 Revert "Bump version to 4.4.0"
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/odlm.go
  controllers/constant/serviceLabel.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/deploy/deploy.yaml
  testdata/expected.yaml
  version/version.go
Labels: lgtm, approved, size/XL

#1684 Isolate License Service Reporter during self-isolation
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/L, approved

#1687 [323] Isolate License Service Reporter during self-isolation (#1684)
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/L, approved

#1688 Trigger CR reconciliation with mapping ConfigMap
  controllers/commonservice_controller.go
Labels: lgtm, size/S, approved

#1689 Update excluded namespace list before removing nss CRs managed by ODLM
  controllers/common/util.go
  controllers/scopewatcher_controller.go
Labels: lgtm, approved, size/M

#1690 [LTSR] cherry pick from release-323
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/scopewatcher_controller.go
Labels: lgtm, approved, size/M

#1696 update UID and resourceVersion when restoring LS CRs
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, size/S, approved

#1697 set UID and resrouceVersion (#1696)
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, size/S, approved

#1698 avoid overwriting CS CR
  controllers/operandconfig.go
Labels: lgtm, size/XS, approved

#1699 [efix] fix: get extreme value on resources field when spec field does not exist
  controllers/operandconfig.go
Labels: lgtm, approved, size/M

#1695 fix: get extreme value on resources field when spec field does not exist
  controllers/operandconfig.go
Labels: lgtm, approved, size/M

#1702 Add managedByCsOperator label for ConfigMap
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#1703 Add managedByCsOperator label for ConfigMap
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#1705 create empty common-service-maps ConfigMap to add label when ConfigMap does not exist
  controllers/common/util.go
  main.go
Labels: lgtm, approved, size/M

#1700 change delete api call based on feedback from zen
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/XS, approved

#1701 change delete api based on feedback from zen
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/XS, approved

#1708 initial keycloak theme
  hack/cs-keycloak-theme.jar
  hack/keycloak-themes/META-INF/keycloak-themes.json
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_en.properties
  hack/keycloak-themes/theme/cs-keycloak/login/resources/css/styles.css
  hack/keycloak-themes/theme/cs-keycloak/login/theme.properties
Labels: lgtm, size/L, approved

#1710 added permissions explicitly for cloud-native-postgresql-image-list c…
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1713 added permissions explicitly for cloud-native-postgresql-image-list c……… (#1710)
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1714 updates to keycloak theme and jar
  hack/cs-keycloak-theme.jar
  hack/keycloak-themes/theme/cs-keycloak/login/resources/css/styles.css
Labels: lgtm, size/S, approved

#1715 support zip for jar and add ico
  hack/cs-keycloak-theme.jar
  hack/keycloak-themes/META-INF/MANIFEST.MF
  hack/keycloak-themes/theme/cs-keycloak/login/resources/img/favicon.ico
Labels: lgtm, size/XS, approved

#1719 version bump for LTSR 3.23.12
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1718 bump version for LTSR 3.19.20
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1720 support keycloak globalization
  hack/cs-keycloak-theme.jar
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_de.properties
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_es.properties
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_fr.properties
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_it.properties
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_ja.properties
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_ko.properties
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_pt_BR.properties
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_zh_CN.properties
  hack/keycloak-themes/theme/cs-keycloak/login/messages/messages_zh_TW.properties
  hack/keycloak-themes/theme/cs-keycloak/login/resources/css/styles.css
  hack/keycloak-themes/theme/cs-keycloak/login/theme.properties
Labels: lgtm, size/M

#1722 update zen channel to 4.4
  controllers/constant/odlm.go
Labels: size/XS, approved

#1716 Update the zen 4 BR process
  velero/restore/zen/zen-restore-job.yaml
  velero/schedule/zen-backup-deployment.yaml
  velero/schedule/zen4-br-scripts.yaml
  velero/schedule/zen4-role.yaml
  velero/schedule/zen4-rolebinding.yaml
  velero/schedule/zen4-sa.yaml
Labels: approved, size/XL

#1717 Overhaul zen 4 BR, match scripts-dev
  velero/restore/zen/zen-restore-job.yaml
  velero/schedule/zen-backup-deployment.yaml
  velero/schedule/zen4-br-scripts.yaml
  velero/schedule/zen4-role.yaml
  velero/schedule/zen4-rolebinding.yaml
  velero/schedule/zen4-sa.yaml
Labels: approved, size/XL
