Repository IBM/ibm-common-service-operator, pull requests merged in 2023-03, with the labels that each got.

#1051 Exclude cloned CommonService CR from being copied in AllNamespace Mode
  controllers/bootstrap/init.go
Labels: lgtm, approved, size/M

#1050 fix webhook ns selector for all namespaces mode
  controllers/webhooks/reconciler.go
Labels: lgtm, size/S, approved

#1049 add validating webhook for CommonService cr
  controllers/webhooks/commonservice/validatingwebhook.go
  controllers/webhooks/reconciler.go
Labels: lgtm, size/L, approved

#1053 enhance creation of csmaps for multiple RequestNs
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: lgtm, approved, size/M

#1054 remove validatingwebhookconfig
  controllers/webhooks/webhookreconciler.go
  main.go
Labels: lgtm, size/S, approved

#1047 add fail to check
  convert_to_multi_instance.sh
Labels: lgtm, size/XS, approved

#1056 update IM OperandRequest in OperandConfig template
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1058 Introduce private catalog flag
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#1059 refresh operatorNs and servicesNs for each loop
  controllers/goroutines/check_iam.go
Labels: lgtm, size/XS, approved

#1055 update backup and restore with zen licensing and cert-manager
  velero/backup/backup.yaml
  velero/backup/cert-manager/label-cert-manager.sh
  velero/backup/genericBackupRestorePod.yaml
  velero/backup/licensing/label-licensing-configmaps.sh
  velero/backup/mongoDB/mongo-backup.sh
  velero/backup/mongoDB/pvc.yaml
  velero/backup/zen/zen_backup_job.yaml
  velero/backup/zen/zen_backup_pvc.yaml
  velero/restore/mongoDB/mongo-restore.sh
  velero/restore/mongoDB/set_access.js
  velero/restore/restore-cert-manager.yaml
  velero/restore/restore-data.yaml
  velero/restore/restore-licensing.yaml
  velero/restore/restore-zen.yaml
  velero/restore/zen/zen-restore-job.yaml
Labels: lgtm, size/L

#1063 bump operator version to 3.23.2
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1062 bump operator version to 3.19.10
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1065 update secretshare and webhook
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
Labels: lgtm, size/S, approved

#1067 revert license and management ingress channel to v3.23
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1057 update script to refresh zenservice after conversion
  convert_to_multi_instance.sh
Labels: lgtm, approved, size/M

#1066 Migrate License Service CMs during conversion process
  convert_to_multi_instance.sh
Labels: lgtm, approved, size/M

#1068 fix metadata.name for metastore-backup-cron-job
  networkpolicy/egress/zen-egress-zen-metastore-backup-cron-job.yaml
Labels: lgtm, size/XS, approved

#1069 restart auth idp pod after restore
  backup_restore_mongo.sh
Labels: lgtm, size/XS, approved

#1070 feat: Remove Db2U from IBM common services
  controllers/constant/odlm.go
Labels: lgtm, size/XS, needs-ok-to-test, approved

#1074 cleanup previous commit
  convert_to_multi_instance.sh
Labels: lgtm, size/XS, approved

#1072 replace supportStatus by installMode: no-op in OperandRegistry CRD
  common/config/.golangci.yml
  controllers/common/cache.go
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1076 Update setup_tenant.sh to temporary unblock test
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1075 de-activate cp2.0 cert-manager and migrate Licensing Service Data
  cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
  cp3pt0-deployment/common/migrate_cp2_licensing.sh
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/L, approved

#1081 update go to 1.20.2
  Dockerfile
Labels: lgtm, size/XS, approved

#1071 Separate backup, restore, and cleanup processes
  backup_restore_mongo.sh
Labels: lgtm, size/L, approved

#1083 generate pre-zen job under operator namespace
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1079 change how cs op sub is found and updated
  convert_to_multi_instance.sh
Labels: lgtm, approved, size/M

#1080 cleanup cp2.0 webhook,secretshare and crossplane
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, approved, size/M

#1084 config_cscr in watch_namespaces
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, approved, size/M

#1085 rename multi instance conversion to cpfs utils
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1091 remove Audit Logging from OperandConfig
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1093 rename commonui to ibm-idp-config-ui-operator in CP3.0
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1089 update packages for twistlock
  go.mod
  go.sum
Labels: lgtm, size/S, approved

#1088 update packages for twistlock
  go.mod
  go.sum
Labels: lgtm, size/S, approved

#1090 add catalogsource label for cert mgr and licensing
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#1096 update IM OpConfig
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1098 change default catalog name
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1094 update go mod to 1.20
  controllers/common/util.go
  go.mod
Labels: lgtm, size/XS, approved

#1095 update go mod to 1.20
  controllers/common/util.go
  go.mod
Labels: lgtm, size/XS, approved

#1077 add some condition check
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1101 provide custom namespace for cert manager and licensing operators
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, approved, size/M

#1103 update csmaps when operator ns is the same as cs ns
  controllers/common/util.go
Labels: lgtm, size/S, approved

#1102 Modification of CP3.0 Install Script for Separation of Permissions
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/L, needs-ok-to-test, approved

#1082 migrate to cp3pt0
  cp3pt0-deployment/common/authorize-namespace.sh
  cp3pt0-deployment/common/cloudpak3-iam-migration-job.yaml
  cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
  cp3pt0-deployment/common/migrate_cp2_licensing.sh
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_singleton.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: size/XXL, lgtm, approved

#1106 add sleep back
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1109 fix indent issue in ibm-cpp-config ConfigMap
  cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
Labels: lgtm, size/XS, approved

#1110 set ControlNs to cs-control when csmaps creating
  controllers/bootstrap/init.go
  controllers/common/util.go
  main.go
Labels: lgtm, size/XS, approved

#1112 Enhance migrate_tenant script
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/S, approved

#1115 remove certmanager finalizer when it is stuck
  cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
Labels: lgtm, size/XS, approved

#1117 Specify a default admin username for IM/IAM
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/constant/defaultAdminUser.go
  controllers/render_template.go
Labels: lgtm, approved, size/M
