Repository IBM/ibm-common-service-operator, pull requests merged in 2023-01, with the labels that each got.

#960 Remove extra space in list of nss managed operator
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#961 Remove extra space in list of nss managed operator
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#958 Update the synchronization between NSS ConfigMap and OperatorGroup
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/namespace.go
  controllers/goroutines/namespacescope.go
  main.go
Labels: lgtm, size/L, approved

#959 support separation of duties - configure through default CR
  Makefile
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/commonservice.go
  controllers/constant/constant.go
  controllers/constant/ibmcloud.go
  controllers/constant/odlm.go
  controllers/goroutines/check_iam.go
  controllers/goroutines/cleanup_deprecated_services.go
  controllers/goroutines/cppConfig.go
  controllers/goroutines/namespacescope.go
  controllers/goroutines/operator_status.go
  controllers/operandconfig.go
  controllers/webhook/operandrequest/mutatingwebhook.go
  main.go
Labels: size/XXL, lgtm, approved

#963 remove operator waiting to unblock cert creation
  controllers/bootstrap/init.go
Labels: lgtm, size/L, approved

#962 wait for cert-manager v1 crd to be ready
  controllers/bootstrap/init.go
  controllers/constant/certmanager.go
Labels: lgtm, size/S, approved

#965 Update template render for NSS ConfigMap
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#968 Add faked multi entry for IAM/IM
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#970 Tolerate customized subscription config
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#971 Tolerate customized subscription config
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#964 check v1alpha1 crd
  controllers/bootstrap/init.go
  controllers/constant/certmanager.go
Labels: lgtm, size/S, approved

#966 integrate crd checking into cleanup function in CD
  controllers/bootstrap/init.go
Labels: lgtm, size/S, approved

#972 update controller-filter-cache version in ltsr
  controllers/commonservice_controller.go
  controllers/operandconfig.go
  go.mod
  go.sum
Labels: lgtm, approved, size/XL

#976 Related image path updated
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#975 support numeric ns installation
  controllers/constant/certmanager.go
  controllers/constant/commonservice.go
  controllers/constant/constant.go
  controllers/constant/crossplane.go
  controllers/constant/ibmcloud.go
  controllers/constant/namespace.go
  controllers/constant/odlm.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  docs/cloudpak-integration.md
Labels: lgtm, size/L, approved

#977 update zen channel to v4.0
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#980 convert type of onPremMultipleDeploy back to bool
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#978 [future] related image path updated
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#981 [ltsr] related image path updated
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#983 remove PAP, PDP, oidc client watcher and iam onboarding job
  controllers/constant/odlm.go
  controllers/goroutines/variables.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: size/XXL, lgtm, approved

#984 remove secret watcher, and policy controller
  controllers/constant/odlm.go
  controllers/goroutines/variables.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: lgtm, size/L, approved

#985 update cert manager and mongodb channel
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#987 revert mongodb channel back to v3.23
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#986 update go to 1.19.4
  Dockerfile
Labels: lgtm, size/XS, approved

#988 new artifactory image endpoint (cs operator)
  .github/workflows/ocp.yaml
  Dockerfile
  Makefile
  common/scripts/artifactory_config_docker.sh
  testing.md
Labels: lgtm, size/S, approved

#989 [ltsr] new artifactory image endpoint (cs operator)
  .github/workflows/ocp.yaml
  Dockerfile
  Makefile
  common/scripts/artifactory_config_docker.sh
  testing.md
Labels: lgtm, size/S, approved

#990 [ltsr] support numeric ns installation
  controllers/constant/certmanager.go
  controllers/constant/commonservice.go
  controllers/constant/constant.go
  controllers/constant/crossplane.go
  controllers/constant/ibmcloud.go
  controllers/constant/namespace.go
  controllers/constant/odlm.go
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  docs/cloudpak-integration.md
Labels: lgtm, size/L, approved

#991 rm rh marketplace operator from operand registry
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#993 remove iam jobs
  controllers/constant/odlm.go
  controllers/goroutines/check_iam.go
  controllers/goroutines/variables.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: lgtm, size/L, approved

#994 IM subscription check
  controllers/goroutines/check_iam.go
Labels: lgtm, size/S, approved

#992 [future] new artifactory image endpoint (cs operator)
  .github/workflows/ocp.yaml
  Dockerfile
  Makefile
  common/scripts/artifactory_config_docker.sh
  testing.md
Labels: lgtm, size/S, approved

#1000 bump version to 3.23.1
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#997 bump licensing operator to v4.0 channel
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#998 update AllNamespaces Installations Mode
  controllers/bootstrap/init.go
  controllers/constant/constant.go
  controllers/goroutines/operator_status.go
  controllers/webhook/operandrequest/mutatingwebhook.go
Labels: lgtm, approved, size/M

#999 discontinue platform-api and cert-manager
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1001 include OperandBindinfo for Zen
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1004 add leaf-refresh opt-in label to cs-ca-certificate-secret
  controllers/constant/certmanager.go
Labels: lgtm, size/XS, approved

#1005 pick up cert-manager from v3.23 via OperandRequest
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#995 add oidc-client-registration job check
  controllers/goroutines/check_iam.go
  controllers/goroutines/variables.go
Labels: lgtm, approved, size/M
