Repository IBM/ibm-common-service-operator, pull requests merged in 2023-08, with the labels that each got.

#1405 change registryNamespace back to default on rollback
  rollback-multi-instance.sh
  uninstall-dedicated-cs-instance.sh
Labels: lgtm, size/S, approved

#1404 [4.2] using fully qualified sub resource name
  convert_to_multi_instance.sh
  cp3pt0-deployment/common/utils.sh
  force-uninstall.sh
  health-check.sh
  operator_checker_patch.sh
  rollback-multi-instance.sh
  rollback_to_eus.sh
  uninstall-dedicated-cs-instance.sh
  upgrade_to_continuous_delivery.sh
  upgrade_to_continuous_delivery_airgap.sh
Labels: lgtm, approved, size/M

#1389 [4.2] detection of OCP cluster type
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
Labels: lgtm, approved, size/M

#1406 bump version to 4.2.0
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1306 Verify master and copied CommonService CR status
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/S, approved

#1411 bump fixpack to 3.23.7
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1410 Bump LTSR to 3.19.15
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1394 Add label and comment for sync PR
  .github/workflows/open_pr_for_review.yml
Labels: lgtm, size/S, approved

#1400 Changes required for BR on 4.x
  velero/backup/licensing/label-licensing-configmaps.sh
  velero/restore/restore-configmap.yaml
  velero/schedule/schedule-common-services.yaml
Labels: lgtm, approved, size/M

#1385 Configure IM MongoDB storageClass via CS CR
  controllers/constant/storageclass.go
Labels: lgtm, size/S, approved

#1413 [CD] Apply PreserveUnknownFields to CS CR status
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
Labels: lgtm, size/XS, approved

#1414 [LTSR] Apply PreserveUnknownFields to CS CR status
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
Labels: lgtm, size/S, approved

#1416 new entries of operators and services with suffix -v4.2
  controllers/constant/odlm.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: size/XXL, lgtm, approved

#1418 restart the webhook pod after deleting config
  convert_to_multi_instance.sh
Labels: lgtm, size/XS, approved

#1420 check for WaitForFirstConsumer bind mode
  preload_data.sh
Labels: lgtm, size/S, approved

#1422 [LTSR] update conversion image with latest tag
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1425 [323] update conversion image with latest tag
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1423 Support picking default channel from bundle
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1426 [CD] update conversion image with latest tag
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#1412 Support simple topology upgrade from v3.x to v4.x
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/S, approved

#1428 remove wait for ibm-common-service-webhook service
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1395 [4.2] olm based webhook on cs-operator
  Makefile
  api/v3/commonservice_types.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/webhook-service_v1_service.yaml
  bundle/metadata/annotations.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/goroutines/waitToCreateCsCR.go
  controllers/webhooks/commonservice/validatingwebhook.go
  controllers/webhooks/operandrequest/mutatingwebhook.go
  controllers/webhooks/operator_webhooks.go
  controllers/webhooks/rules.go
  controllers/webhooks/webhook_register.go
  controllers/webhooks/webhookreconciler.go
  main.go
Labels: size/XXL, lgtm, approved

#1430 KeyCloak Integration on ODLM
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1432 update iam-custom-hostname tag to latest
  cs-onprem-tenant-config.sh
Labels: lgtm, size/XS, approved

#1437 Update info statements
  convert_to_multi_instance.sh
Labels: lgtm, size/XS, approved

#1436 updated descriptions in CRD fields
  Makefile
  api/v3/commonservice_types.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
Labels: lgtm, size/L, approved

#1438 Initial commit for cpfs plugin
  README.md
  kubectl-cpfs
Labels: lgtm, size/L, approved

#1439 introduce initMongoDB into Authentication CR
  controllers/constant/odlm.go
  controllers/rules/rules.go
  testdata/actual.yaml
  testdata/expected.yaml
Labels: lgtm, size/L, approved

#1304 CS operator handles scoping changes
  api/v3/commonservice_types.go
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  main.go
Labels: lgtm, approved, size/M

#1427 add ephemeral-storage request to container
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#1443 Skip LS CatalogSource check when it's not enabled
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved
