Repository IBM/ibm-common-service-operator, pull requests merged in 2023-11, with the labels that each got.

#1574 grant packagemanifest permission to namespace scope operator
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/S, approved

#1576 Update OperandConfig with value reference
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1579 new volumesnapshots resources permission from cloud-native-postgresql
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/S, approved

#1582 script enahcements (catalogsource correction error msg + cert-manager smoke test namespace)
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1578 Update image used for mongo BR containers for SSL support on Power and Z
  velero/backup/mongoDB/mongo-backup.sh
  velero/backup/mongoDB/mongodbbackup.yaml
  velero/restore/mongoDB/mongo-restore.sh
  velero/restore/mongoDB/mongodbrestore.yaml
  velero/restore/zen/zen5-restore-job.yaml
  velero/schedule/mongodb-backup-deployment-z.yaml
  velero/schedule/mongodb-backup-deployment.yaml
Labels: lgtm, size/L, approved

#1581 sync br files to script dev changes
  velero/backup/cert-manager/label-cert-manager.sh
  velero/backup/mongoDB/mongo-backup.sh
  velero/backup/mongoDB/mongodbbackup.yaml
  velero/restore/mongoDB/mongo-restore.sh
  velero/restore/mongoDB/mongodbrestore.yaml
  velero/restore/zen/zen5-restore-job.yaml
  velero/schedule/mongodb-backup-deployment-z.yaml
  velero/schedule/mongodb-backup-deployment.yaml
  velero/schedule/zen5-backup-deployment.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
  velero/schedule/zen5-clusterrole.yaml
  velero/schedule/zen5-clusterrolebinding.yaml
Labels: lgtm, approved, size/XL

#1583 Expose postgresql Image list via ConfigMap
  controllers/bootstrap/init.go
  controllers/constant/cloudNativePostgresql.go
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1577 enable all namespace mode migration
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/L, approved

#1584 update grpc pkg
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#1585 Enable customized configuration for OperandConfig resources[*] array field
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manager/manager.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/odlm.go
  controllers/operandconfig.go
  controllers/render_template.go
Labels: lgtm, approved, size/XL

#1562 Add storage class configuration for EDB-Keycloak
  controllers/constant/storageclass.go
Labels: lgtm, size/XS, approved

#1565 Handle EDB and Keycloak profile sizes
  controllers/constant/odlm.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, size/L, approved

#1586 add default admin creds to backup
  velero/backup/cert-manager/label-cert-manager.sh
Labels: lgtm, size/S, approved

#1587 add default admin creds to backup
  velero/backup/cert-manager/label-cert-manager.sh
Labels: lgtm, size/S, approved

#1589 fix target ns check for all namespace mode
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/XS, approved

#1590 implement Keycloak BindInfo via template reference
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, approved, size/XL

#1591 delete webhook configuration when cs pod down
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/S, approved

#1593 grant zen parallel job permission to Namespace Scope
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/S, approved

#1595 add two more secrets to backup
  velero/backup/cert-manager/label-cert-manager.sh
Labels: lgtm, size/S, approved

#1594 add two more secrets to backup
  velero/backup/cert-manager/label-cert-manager.sh
Labels: lgtm, size/S, approved

#1597 Missing . in objectRef path
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1598 update zen extension logic based on feedback
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/S, approved

#1599 update zen extension logic based on feedback
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/S, approved

#1605 bump version for 3.23.10
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1604 bump version for 3.19.18
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1607 Update default Keycloak realm name to follow the Cloud Pak naming convention
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1606 Patch multipleInstancesEnabled false for ManagementIngress CR to avoid cp-console change
  isolate.sh
Labels: lgtm, size/L, approved

#1608 create nss configmap in cs namespace for all ns upgrade
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/S, approved

#1611 Create default CR even services Ns does not exist for all namespace mode, move services Ns check into reconciliation logic
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/operandconfig.go
  controllers/webhooks/commonservice/validatingwebhook.go
Labels: lgtm, approved, size/M

#1613 remove redhat-operators from excluded list
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1612 fixed licensing upgrade regression caused by opreq
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1615 fixed upgrade_operator not deleting opreq label
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1610 Update Zen extension logic to capture extensions before backup, standardize some values across files
  velero/backup/mongoDB/mongodbbackup.yaml
  velero/restore/mongoDB/mongo-restore.sh
  velero/restore/mongoDB/mongodbrestore.yaml
  velero/schedule/mongodb-backup-deployment.yaml
  velero/schedule/mongodb-backup-pvc.yaml
  velero/schedule/zen-backup-deployment.yaml
  velero/schedule/zen-backup-pvc.yaml
  velero/schedule/zen5-backup-deployment.yaml
  velero/schedule/zen5-backup-pvc.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
  velero/schedule/zen5-clusterrolebinding.yaml
  velero/schedule/zen5-sa.yaml
Labels: lgtm, size/L, approved

#1619 update grpc pkg
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#1620 update grpc
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#1617 match scripts dev commits
  velero/backup/mongoDB/mongodbbackup.yaml
  velero/restore/mongoDB/mongo-restore.sh
  velero/restore/mongoDB/mongodbrestore.yaml
  velero/schedule/mongodb-backup-deployment.yaml
  velero/schedule/mongodb-backup-pvc.yaml
  velero/schedule/zen-backup-deployment.yaml
  velero/schedule/zen-backup-pvc.yaml
  velero/schedule/zen5-backup-deployment.yaml
  velero/schedule/zen5-backup-pvc.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
  velero/schedule/zen5-clusterrolebinding.yaml
  velero/schedule/zen5-sa.yaml
Labels: lgtm, size/L, approved

#1623 fixed opreq-control label not being deleted
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1627 changed opreq-control label removal implementation
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#1625 remove duplicate code
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/S, approved

#1626 remove duplicate code
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/S, approved

#1632 skip mgmt_ingress CR check when it does not exist
  isolate.sh
Labels: lgtm, size/XS, approved

#1639 update cluster role to role and remove some permissions
  velero/schedule/zen5-role.yaml
  velero/schedule/zen5-rolebinding.yaml
Labels: lgtm, size/S, approved

#1640 update cluster role to role and remove some permissions
  velero/schedule/zen5-role.yaml
  velero/schedule/zen5-rolebinding.yaml
Labels: lgtm, size/S, approved

#1636 change when housekeeping command is run
  velero/schedule/mongodb-backup-deployment.yaml
  velero/schedule/zen-backup-deployment.yaml
  velero/schedule/zen5-backup-deployment.yaml
Labels: lgtm, size/XS, approved

#1637 change when housekeeping command is run
  velero/schedule/mongodb-backup-deployment.yaml
  velero/schedule/zen-backup-deployment.yaml
  velero/schedule/zen5-backup-deployment.yaml
Labels: lgtm, size/XS, approved

#1642 remove invalid option in script
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/XS, approved

#1643 remove invalid option in script
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/XS, approved

#1644 bump version 3.19.19
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1645 version bump 3.23.11
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1646 resolve syntax error, change check command
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/XS, approved

#1647 resolve syntax error, change check command
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/XS, approved

#1651 Bump version to 4.3.1
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1638 align default EDB keycloak size profiles with starterset
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1631 Update installer License short link
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  docs/install.md
Labels: lgtm, size/S, approved

#1649 change message from error to warning for more consistent results
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, approved, size/M

#1650 change message from error to warning for more consistent results
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, approved, size/M

#1653 Bump version to 4.4.0
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/odlm.go
  controllers/constant/serviceLabel.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/deploy/deploy.yaml
  testdata/expected.yaml
  version/version.go
Labels: lgtm, approved, size/XL

#1652 Remove multiInstance template
  controllers/constant/multipleInstancesEnabled.go
  controllers/render_template.go
Labels: lgtm, approved, size/M

#1654 Clean webhook, secretshare and zen reference and unused code
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/next-csv.sh
  config/manager/manager.yaml
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
  controllers/goroutines/cleanup_deprecated_services.go
  controllers/goroutines/namespacescope.go
  controllers/goroutines/operator_status.go
  controllers/goroutines/variables.go
  go.mod
  go.sum
  testdata/deploy/deploy.yaml
Labels: lgtm, approved, size/XL

#1655 Add default realm security settings
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1664 [323] Introduce basic maintenance mode in CS operator
  controllers/commonservice_controller.go
  controllers/recocile_pause.go
Labels: lgtm, approved, size/M

#1662 [LTSR] Introduce basic maintenance mode in CS operator
  controllers/commonservice_controller.go
  controllers/recocile_pause.go
Labels: lgtm, approved, size/M

#1661 introduce basic maintenance mode into CS operator
  controllers/commonservice_controller.go
  controllers/recocile_pause.go
Labels: lgtm, approved, size/M

#1663 Create a dedicate controller for self-isolation
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/L, approved
