Repository IBM/ibm-common-service-operator, pull requests merged in 2023-07, with the labels that each got.

#1285 Update dependabot.yml
  .github/dependabot.yml
Labels: lgtm, size/S, approved

#1337 Fix NSS Patch waiting condition
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1336 Preview mode for setup tenant script
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/L, approved

#1338 Update Github Actions for scripts
  .github/workflows/approve_for_sync_up.yml
  .github/workflows/open_pr_for_review.yml
  .github/workflows/shell_linter.yml
Labels: lgtm, size/L, approved

#1340 Onboard IAM script for customizing hostname
  cs-onprem-tenant-config.sh
Labels: lgtm, size/L, approved

#1341 [Scripts Branch] Onboard IAM script for customizing hostname
  cs-onprem-tenant-config.sh
Labels: lgtm, size/L, approved

#1342 Patch channel and catalogsource for 4.1 upgrade
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/S, approved

#1347 update channels for all operators with suffix v4.0 pointing to v4.1 in OperandRegistry
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1301 enhance singleton script to handle all cases
  cp3pt0-deployment/common/migrate_singleton.sh
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: size/L, approved, do-not-merge/hold

#1349 migrate tenant adoption on singleton enhancement
  cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
  cp3pt0-deployment/common/migrate_cp2_licensing.sh
  cp3pt0-deployment/common/migrate_singleton.sh
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  cp3pt0-deployment/uninstall_tenant.sh
  isolate.sh
Labels: lgtm, size/L, approved

#1352 Remove SecretShare for ibm-cpp-config in isolation
  isolate.sh
Labels: lgtm, size/S, approved

#1351 Update help text to be more clear, provide docs
  cp3pt0-deployment/common/authorize-namespace.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  cp3pt0-deployment/uninstall_tenant.sh
  isolate.sh
  preload_data.sh
Labels: lgtm, size/L, approved

#1356 new entries of operators and services with suffix -v4.1
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: size/XXL, lgtm, approved

#1331 Cleanup scritp enhancement
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/uninstall_tenant.sh
Labels: lgtm, size/L, approved, ok-to-test

#1360 Preserve CR Configurations during the upgrade
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1361 support upgrade for simple and all namespaces mode
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1362 [3.23] change update strategy to recreate
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#1365 bump version for 3.23.6
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1364 bump version for 3.19.14
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1366 removed all wildcard permissions
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: lgtm, size/L, approved

#1368 add delete permission on cert for SOD
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: lgtm, size/XS, approved

#1367 Remediate NSS CSV Injector propagation issue
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/L, approved

#1373 Add NSS restart label when patching the deployment
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1370 don't copy oidc credential
  preload_data.sh
Labels: lgtm, size/XS, approved

#1375 add wait timeout for delete
  cp3pt0-deployment/uninstall_tenant.sh
Labels: lgtm, size/S, approved

#1376 Wait for CSV shown up in subscription status
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#1354 support CatalogSource correction in setup_singleton and setup_tenant script
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/L, approved

#1379 check singleton catalogsrouce in their own ns
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1380 update go, logrus for twistlock 3.19.14
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#1381 update go, logrus for 3.23.6
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#1371 change channel along with subscription
  convert_to_multi_instance.sh
Labels: lgtm, size/XS, approved

#1386 init checker_tool
  checker_tool/check_cpfs.sh
Labels: lgtm, size/S, approved

#1393 [323] detection of OCP cluster type
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  common/Makefile.common.mk
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
Labels: lgtm, size/L, approved

#1390 [LTSR] detection of OCP cluster type
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  common/Makefile.common.mk
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
Labels: lgtm, size/L, approved

#1392 [4.1] Update image tag to 4.0.0
  cs-onprem-tenant-config.sh
Labels: lgtm, size/XS, approved

#1391 [4.0] Update image tag to 4.0.0
  cs-onprem-tenant-config.sh
Labels: lgtm, size/XS, approved

#1397 mitigate intra-channel upgrade
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/S, approved

#1387 Update operand requests' registryNamespace value to reflect new cs instance namespace
  convert_to_multi_instance.sh
Labels: lgtm, approved, size/M
