Repository IBM/ibm-common-service-operator, pull requests merged in 2023-10, with the labels that each got.

#1514 Add Keycloak BindInfo to OperandConfig
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1516 Mapping CS and NSS version with awk binary
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1521 add ephemeral storage limit to operandConfig rule
  controllers/rules/rules.go
Labels: lgtm, approved, size/M

#1522 support helm and RH cert manager validation
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/L, approved

#1523 enable leaf certificate for Keycloak
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1517 Install keycloak in serviceNs for All Ns mode
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1529 remove Keycloak initial admin bind info
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1525 Fix for isolation LSR when it is corrupted
  cp3pt0-deployment/common/migrate_singleton.sh
  cp3pt0-deployment/migrate_tenant.sh
  isolate.sh
Labels: lgtm, approved, size/M

#1531 add necessary files for velero br on z
  velero/backup/mongoDB/mongo-backup.sh
  velero/restore/mongoDB/mongo-restore.sh
  velero/schedule/mongodb-backup-deployment-z.yaml
  velero/schedule/prep-mongo-br-z.sh
Labels: lgtm, approved, size/XL

#1530 add necessary files for velero br on z
  velero/backup/mongoDB/mongo-backup.sh
  velero/restore/mongoDB/mongo-restore.sh
  velero/schedule/mongodb-backup-deployment-z.yaml
  velero/schedule/prep-mongo-br-z.sh
Labels: lgtm, approved, size/XL

#1532 bump CS LTSR version to 3.19.17
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1533 bump CS 3.23 to 3.23.9
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1499 Update FailurePolicy for MutatingWebhook
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  controllers/webhooks/operandrequest/mutatingwebhook.go
Labels: lgtm, size/XS, approved

#1540 Move KeyCloak BindInfo and Setup job to OperatorNs
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1543 update go mod to use go 1.21
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#1544 update go mod to use go 1.21
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#1545 authorize nss log improvement
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#1550 add labels to zen5 permissions, add errexit to zen5 scripts
  velero/schedule/zen5-br-scripts-cm.yaml
  velero/schedule/zen5-clusterrole.yaml
  velero/schedule/zen5-clusterrolebinding.yaml
  velero/schedule/zen5-sa.yaml
Labels: lgtm, approved, size/M

#1547 update yq path
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1552 increase time for waiting CSV to bypass CatalogSource connection issue
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1548 label cert-manager.io specific resources and custom route secrets
  velero/backup/cert-manager/label-cert-manager.sh
Labels: lgtm, approved, size/M

#1453 fixed make manifests to have good CRD
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
Labels: lgtm, approved, size/M

#1549 label cert-manager.io specific resources and custom route secrets
  velero/backup/cert-manager/label-cert-manager.sh
Labels: lgtm, approved, size/M

#1551 add labels to zen5 permissions, add errexit to zen5 scripts
  velero/schedule/zen5-br-scripts-cm.yaml
  velero/schedule/zen5-clusterrole.yaml
  velero/schedule/zen5-clusterrolebinding.yaml
  velero/schedule/zen5-sa.yaml
Labels: lgtm, approved, size/M

#1539 label services
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/serviceLabel.go
  controllers/operandconfig.go
  controllers/render_template.go
Labels: lgtm, size/L, approved

#1541 add support for nss reduced rbac
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: size/XXL, lgtm, approved

#1554 onboard RHBK packagemanifest
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1556 add reduced rbac for nss in operator namespace
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/S, approved

#1553 wait for deployments to fully scale down
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, approved, size/M

#1558 Remove wildcard permisisons
  Makefile
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/commonservice_controller.go
Labels: lgtm, approved, size/XL

#1563 set default channel of cert-manager as v4.2
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1566 added permissions for cert-manager resources
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/commonservice_controller.go
Labels: lgtm, approved, size/M

#1569 Remove wildcard
  Makefile
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/commonservice_controller.go
Labels: lgtm, approved, size/XL

#1567 bump up zen restore timeout, add error handling for custom secrets
  velero/backup/cert-manager/label-cert-manager.sh
  velero/schedule/zen5-backup-deployment.yaml
Labels: lgtm, approved, size/M

#1568 bump up zen restore timeout, add error handling for custom secrets
  velero/backup/cert-manager/label-cert-manager.sh
  velero/schedule/zen5-backup-deployment.yaml
Labels: lgtm, approved, size/M

#1560 update wait for deployments to scale down
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/S, approved

#1559 update wait for deployments to scale down
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/XS, approved

#1571 Add a default realm for sharing
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1519 Zen extension update script
  velero/backup/cert-manager/label-cert-manager.sh
  velero/schedule/zen5-backup-deployment.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
  velero/schedule/zen5-clusterrole.yaml
Labels: lgtm, size/L, approved

#1573 new entries of operators and services with suffix -v4.3
  controllers/constant/fipsEnable.go
  controllers/constant/odlm.go
  controllers/constant/serviceLabel.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: lgtm, approved, size/XL
