Repository IBM/ibm-common-service-operator, pull requests merged in 2024-03, with the labels that each got.

#1821 Enable keycloak token-exchange
  controllers/commonservice_controller.go
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1813 setup singleton ensures cm-maps created
  cp3pt0-deployment/common/migrate_singleton.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/L, approved

#1822 Update size for common-service-db
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, size/L, approved

#1825 check copied resrouces
  preload_data.sh
Labels: lgtm, size/S, approved

#1827 increase wait time for cert and issuer
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1829 Adding additional error handling to the scripts
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  cp3pt0-deployment/uninstall_tenant.sh
  isolate.sh
  preload_data.sh
Labels: lgtm, approved, size/M

#1831 create/update NSS CR before updating NSS operator
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/XS, approved

#1834 Revert errtrace and nounset
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  cp3pt0-deployment/uninstall_tenant.sh
  preload_data.sh
Labels: lgtm, size/S, approved

#1828 create temporary files in /tmp
  cp3pt0-deployment/common/delegate_cp2_cert_manager.sh
  cp3pt0-deployment/common/migrate_cp2_licensing.sh
  cp3pt0-deployment/common/utils.sh
  isolate.sh
  preload_data.sh
Labels: lgtm, approved, size/M

#1839 Extend the time to wait for CS CR readiness
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1842 Improve error handling
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  cp3pt0-deployment/uninstall_tenant.sh
Labels: lgtm, size/S, approved

#1845 Remove problematic code to reduce error
  preload_data.sh
Labels: lgtm, size/XS, approved

#1844 Upgrade db2u operator channel to v5.
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1846 [323] Upgrade db2u operator channel to v5
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1851 update error handling in preload_data.sh
  preload_data.sh
Labels: lgtm, size/XS, approved

#1853 Enhance dumplog to support multiple pods
  preload_data.sh
Labels: lgtm, size/S, approved

#1849 [323] Update EDB License Image
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1850 [LTSR] Update EDB License Image
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1848 Pick up EDB 1.18.10
  controllers/constant/cloudNativePostgresql.go
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1847 [4.5] Pick up EDB 1.18.10
  controllers/constant/cloudNativePostgresql.go
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1833 [Cherry-pick 323] Continue isolation when the resource is not found
  Makefile
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/recocile_pause.go
Labels: lgtm, size/L, approved

#1832 Continue isolation when the resource is not found
  Makefile
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/recocile_pause.go
Labels: lgtm, size/L, approved

#1855 update velero post hook annotation
  velero/schedule/keycloak/keycloak-backup-deployment.yaml
  velero/schedule/schedule-common-services.yaml
Labels: lgtm, size/XS, approved

#1857 Add cert-manger and AudiLogging CRs back to OperandConfig
  common/scripts/lint-csv.sh
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1860 Add retry for CatalogSource validation
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#1863 Add retry logic to wait for namespaces list in NSS configmap to be updated
  isolate.sh
Labels: lgtm, approved, size/M

#1865 Fix for when LSR CR name is unset
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#1868 Preload IM client credentials for admin
  preload_data.sh
Labels: lgtm, size/XS, needs-ok-to-test, approved

#1870 add Keycloak as the owner of KeycloakRealmImport
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1867 separate wal storage and increase storage volume
  controllers/constant/odlm.go
  controllers/constant/storageclass.go
Labels: lgtm, size/XS, approved

#1871 additional carbon updates for cs keycloak theme
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_de.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_en.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_es.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_fr.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_it.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_ja.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_ko.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_pt_BR.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_zh_CN.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_zh_TW.properties
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles.css
  hack/keycloak-themes/theme/cloudpak/login/resources/img/login-header.svg
Labels: lgtm, size/L, approved

#1859 Disable the installation of MongoDB starting from 4.6.
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1873 fix cacheing of style files
  hack/keycloak-themes/README.md
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles460.css
  hack/keycloak-themes/theme/cloudpak/login/theme.properties
Labels: lgtm, size/XS, approved

#1874 Delete NSS resources by patching finalizer
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1876 Adding new fields for 1.22 default compatibility
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1877 translated strings for keycloak theme
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_de.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_es.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_fr.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_it.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_ja.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_ko.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_pt_BR.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_zh_CN.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_zh_TW.properties
Labels: lgtm, approved, size/M

#1878 add Apache Flink entry into OperandRegistry
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1879 Bump default channel to v4.6 and increase waiting time
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_tenant.sh
  isolate.sh
Labels: lgtm, size/S, approved

#1881 Valero/OADP support for Keycloak's EDB
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1858 workaround for Keycloak and IM EDB BR
  velero/restore/common-service-db/cs-db-restore-job.yaml
  velero/restore/keycloak/keycloak-restore-job.yaml
Labels: lgtm, size/L, approved

#1886 update keycloak realm for banner
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1883 Remove default size profile and instance from OperandConfig template
  controllers/constant/odlm.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, approved, size/M

#1889 quote array value for annotations
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved
