Repository IBM/ibm-common-service-operator, pull requests merged in 2024-07, with the labels that each got.

#2056 [4.0-4.5] spectrum fusion example recipe
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml
Labels: lgtm, approved, size/XL

#2069 [4.8] Add EDB License secret into Cluster CR description
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2081 Add more debug info on subscription during install and upgrade
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#2076 added ibm-account-iam-operator to registry
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2083 skip clean control namespace in rerun
  cp3pt0-deployment/uninstall_tenant.sh
Labels: lgtm, approved, size/M

#2085 Update events permission in nss managed role
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, approved, size/M

#2044 Create Spectrum Fusion recipe for License Service Reporter
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Labels: lgtm, size/L, approved

#2086 edit tmp files instead of actual so the script can be rerun multiple times
  velero/schedule/deploy-br-resources.sh
Labels: lgtm, size/L, approved

#2087 Overwrite nss managed role during upgrade
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/S, approved

#1221 match migrate lic function to what is in isolate script
  convert_to_multi_instance.sh
Labels: lgtm, approved, size/M

#2094 update events permission
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/S, approved

#2095 specify data copied over in preload data script
  preload_data.sh
Labels: lgtm, size/XS, approved

#2091 Runtime Data Sync using Spectrum Fusion
  velero/schedule/deploy-br-resources.sh
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-clusterrole.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-deployment.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-services-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-services-rolebinding.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
  velero/spectrum-fusion/recipes/4.8-example-csdb-sync-recipe.yaml
  velero/spectrum-fusion/recipes/4.8-example-zen-sync-recipe.yaml
  velero/spectrum-fusion/templates/cs-db-sync-restore-template.yaml
  velero/spectrum-fusion/templates/zen-sync-restore-template.yaml
Labels: lgtm, approved, size/XL

#2098 add datasync changes to scripts branch
  velero/schedule/deploy-br-resources.sh
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-clusterrole.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-deployment.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-services-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-services-rolebinding.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
  velero/spectrum-fusion/recipes/4.8-example-csdb-sync-recipe.yaml
  velero/spectrum-fusion/recipes/4.8-example-zen-sync-recipe.yaml
  velero/spectrum-fusion/templates/cs-db-sync-restore-template.yaml
  velero/spectrum-fusion/templates/zen-sync-restore-template.yaml
Labels: lgtm, approved, size/XL

#2099 Bump operator version to 4.6.5
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#2100 rename account-iam operator to user mgmt operator
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2101 add setup tenant job to scripts branch
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-configmap.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-pvc.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-rolebinding.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-sa.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-serv-tethered-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-serv-tethered-rolebinding.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job.yaml
Labels: lgtm, approved, size/XL

#2102 changed user-management-operator channel from alpha to v0.1
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2088 enhancement on cp2 resources cleanup
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#2092 fix contorl_ns not found
  cp3pt0-deployment/common/cleanup_cp2_control.sh
Labels: lgtm, size/S, approved

#2090 annotate Mongo PV on ROKS
  preload_data.sh
Labels: lgtm, size/S, approved

#2104 bumped version from 4.8 to 4.9
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/odlm.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#2105 Add WebsphereLiberty Operator into OperandRegistry
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2106 BTS version suffix
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2107 BTS version suffix in CD
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2108 update older mongo restore scripts
  backup_restore_mongo.sh
  velero/restore/mongoDB/mongo-restore.sh
Labels: lgtm, size/XS, approved
