Repository IBM/ibm-common-service-operator, pull requests merged in 2024-12, with the labels that each got.

#2317 Refresh Recipe by removing setup tenant job
  velero/backup/common-service/label-common-service.sh
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns-multi-zen.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Labels: lgtm, size/L, approved

#2322 cleanup cs-control
  cp3pt0-deployment/common/cleanup_cp2_control.sh
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/S, approved

#2311 Refresh Recipe by removing setup tenant job
  velero/backup/common-service/label-common-service.sh
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns-multi-zen.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Labels: lgtm, size/L, approved

#2329 Bump Common UI version to 4.7
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2327 suspend go routines until operator cache is ready
  controllers/goroutines/cleanup_resources.go
  controllers/goroutines/operator_status.go
  controllers/goroutines/waitToCreateCsCR.go
  main.go
Labels: lgtm, size/S, approved

#2331 Bump cs version to 4.6.10
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#2319 add on-error annotation for Velero hooks
  velero/schedule/common-service-db/cs-db-backup-deployment.yaml
  velero/schedule/keycloak/keycloak-backup-deployment.yaml
  velero/schedule/license_service_reporter/lsr-backup-deployment.yaml
  velero/schedule/mongodb-backup-deployment.yaml
  velero/schedule/zen-backup-deployment.yaml
  velero/schedule/zen5-backup-deployment.yaml
Labels: lgtm, size/S, approved

#2332 update name of external db config cm
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
Labels: lgtm, size/XS, approved

#2333 start go routines after cs controller manager setup
  controllers/goroutines/cleanup_resources.go
  controllers/goroutines/operator_status.go
  controllers/goroutines/waitToCreateCsCR.go
  main.go
Labels: lgtm, size/S, approved
