Repository IBM/ibm-common-service-operator, pull requests merged in 2024-08, with the labels that each got.

#2112 [CD] add version suffix entry for EDB 1.22
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2113 [SC2] add version suffix entry for EDB 1.22
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2115 update licensing catalogsource ns
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#2117 update licensing and cert-manager catalogsource namespace in migrate
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#2119 remove extra fi in the script
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#2121 fix $region is empty issue
  preload_data.sh
Labels: lgtm, size/XS, approved

#2110 [CD] Move CPP Config into reconciliation
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/configurationCollector/collector.go
  controllers/configurationcollector/collector.go
  controllers/goroutines/cppConfig.go
  controllers/goroutines/waitToCreateCsCR.go
  main.go
Labels: lgtm, size/L, approved

#2111 [SC2] Move CPP Config into reconciliation
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/configurationCollector/collector.go
  controllers/configurationcollector/collector.go
  controllers/goroutines/cppConfig.go
  controllers/goroutines/waitToCreateCsCR.go
  main.go
Labels: lgtm, size/L, approved

#2123 Use jsonpath to check the status for mongodb pod
  preload_data.sh
Labels: lgtm, size/XS, approved

#2125 add rerun parameter
  preload_data.sh
Labels: lgtm, size/XS, approved

#2127 Rerun preload
  preload_data.sh
Labels: lgtm, approved, size/M

#2109 iaf networkpolicies
  cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operand.yaml
  cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operator.yaml
  cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operand.yaml
  cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operator.yaml
  cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operand.yaml
  cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operator.yaml
  cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operand.yaml
  cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operator.yaml
  cp3-networkpolicy/install_networkpolicy.sh
Labels: lgtm, size/L, approved

#2130 add networkpolicy for flink and opensearch
  cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operand.yaml
  cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operator.yaml
  cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operand.yaml
  cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operator.yaml
  cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operand.yaml
  cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operator.yaml
  cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operand.yaml
  cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operator.yaml
  cp3-networkpolicy/install_networkpolicy.sh
Labels: lgtm, size/L, approved

#2133 Cleanup preload
  preload_data.sh
Labels: lgtm, approved, size/M

#2135 Add redis operator in OperandRegistry
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2114 Add user management bindinfo
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#2136 Add user management CR
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#2141 update user-mgmt operator channel in opreg
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2131 [CD] add HA configuration for csdb
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2132 [SC2] Commonservice-db HA configuration
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2148 Bump sc2 stream to 4.6.6
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#2143 add securityContext .seccompProfile field
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#2145 add securityContext .seccompProfile field
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS, approved

#2155 chech operq-control label
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#2158 hide error message in retry
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#2152 upgrade cs-operator in tethered-namespaces
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#2160 updated base image to ubi9
  Dockerfile
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint_go.sh
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2159 updated base image to ubi9
  Dockerfile
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint_go.sh
  go.mod
Labels: lgtm, approved, size/M

#2161 set packagemanifest name
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#2154 update cs module version to v4
  api/v3/commonservice_types.go
  controllers/bootstrap/init.go
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/commonservice_controller_test.go
  controllers/configurationcollector/collector.go
  controllers/deploy/manager.go
  controllers/goroutines/cleanup_resources.go
  controllers/goroutines/operator_status.go
  controllers/goroutines/waitToCreateCsCR.go
  controllers/operandconfig.go
  controllers/operatorconfig.go
  controllers/recocile_pause.go
  controllers/render_template.go
  controllers/render_template_test.go
  controllers/suite_test.go
  controllers/webhooks/commonservice/validatingwebhook.go
  controllers/webhooks/operandrequest/mutatingwebhook.go
  go.mod
  main.go
Labels: lgtm, size/L, approved

#2163 update cs-operator description
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/S, approved

#2164 update cs-operator description in SC2
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/S, approved

#2168 added opreg entry for dev test new keycloak
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2167 remove whole storageClassName field in pvc on ROKs env
  preload_data.sh
Labels: lgtm, size/S, approved

#2169 add permissions for zenextension finalizer
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/XS, approved

#2165 [SC2] bump keycloak to 24 and add fallback channel 22
  common/scripts/lint_go.sh
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2172 [CD] add EDB License Job for entry EDB 1.22
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#2173 [SC2] add EDB License Job for entry EDB 1.22
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#2166 [CD] bump keycloak to 24 and add fallback channel 22
  common/scripts/lint_go.sh
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2151 Bump EDB used by IM to stable-v1.22 channel
  controllers/constant/cloudNativePostgresql.go
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved
