Repository IBM/ibm-common-service-operator, pull requests merged in 2024-11, with the labels that each got.

#2285 [CD] Update ODLM CRs after ODLM is upgraded to desired version (#2280)
  controllers/bootstrap/init.go
  controllers/bootstrap/init_test.go
  controllers/commonservice_controller.go
Labels: lgtm, approved, size/M

#2287 updated turbo profile controller to handle data.resource
  controllers/operandconfig.go
Labels: lgtm, approved, size/M

#2290 updated actions/upload-artifact to v4
  .github/workflows/shell_linter.yml
Labels: lgtm, size/XS, approved

#2273 exclude internal generated operandrequest from Backup/Restore
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, size/S, approved

#2294 add common-web-ui-config cm to labeling script
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, size/XS, approved

#2295 common-web-ui ORMs
  turbonomic/README.md
  turbonomic/operands/orm-common-web-ui.yaml
  turbonomic/operators/orm-ibm-commonui-operator.yaml
Labels: size/M

#2292 turbonomic ORM for ibm-cert-manager
  turbonomic/operands/cert-manager.yml
Labels: lgtm, approved, size/M

#2298 exclude internal generated operandrequest from Backup/Restore (#2273)
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, size/S, approved

#2299 Bump up version to 4.6.9
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#2293 remove EDB configmap cluster permission
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: lgtm, size/S, approved

#2300 removed existing operator ORMs since cannot hardcode CSV name
  turbonomic/operators/im-operator.yml
  turbonomic/operators/orm-ibm-commonui-operator.yaml
Labels: lgtm, approved, size/M

#2266 [SC2] new entry for event-v5.1
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2288 Make mongo manual br scripts more consistently set storage class
  backup_restore_mongo.sh
  velero/backup/mongoDB/mongo-backup.sh
Labels: lgtm, approved, size/M

#2302 Clean MongoDB preload ConfigMap when the local MongoDB instance is owned by CR
  controllers/goroutines/cleanup_resources.go
Labels: lgtm, approved, size/M

#2305 add related permission for MongoDB cleanup in post DB migration
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/L, approved

#2301 script to apply ORM files
  turbonomic/install_orm.sh
  turbonomic/operands/cert-manager.yaml
  turbonomic/operands/im-auth-service.yaml
  turbonomic/operands/im-platform-idmgmt.yaml
  turbonomic/operands/im-platform-idprovider.yaml
  turbonomic/operands/orm-common-web-ui.yaml
Labels: lgtm, size/L, approved

#2304 ILS-166 Egress for ibm-license-service-reporter
  cp3-networkpolicy/egress/license-service-reporter-manually/ibm-license-service-reporter-oidc-egress.yaml
  cp3-networkpolicy/egress/license-service-reporter-manually/ibm-license-service-reporter-operator-k8s-cncf-egress.yaml
  cp3-networkpolicy/egress/license-service-reporter/bedrock-egress-ibm-license-service-reporter-operator.yaml
Labels: lgtm, needs-ok-to-test, approved, size/M

#2307 isolate script should check if cert manager is requested before isolation
  isolate.sh
Labels: lgtm, approved, size/M

#2313 Add nodeAffinity for Postgres operator, and add new entry cloud-native-postgresql-v1.22
  controllers/constant/odlm_operatorconfig.go
  controllers/operatorconfig.go
Labels: lgtm, approved, size/M

#2310 External DB BR enablement
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/L, approved

#2315 Use Reader.Get() to retrieve the resource outside of cache scope
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved

#2316 Use Reader.Get() to retrieve the resource outside of cache scope (#2315)
  controllers/bootstrap/init.go
Labels: lgtm, size/XS, approved
