Repository IBM/ibm-common-service-operator, pull requests merged in 2024-04, with the labels that each got.

#1890 Add global hugepage support for IM and EDB
  Makefile
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/common/util_test.go
  controllers/constant/constant.go
  controllers/constant/hugepages.go
  controllers/render_template.go
  controllers/render_template_test.go
  controllers/webhooks/commonservice/validatingwebhook.go
  controllers/webhooks/commonservice/validatingwebhook_test.go
  go.mod
Labels: lgtm, approved, size/XL

#1891 Add permission for operatorconfig for Minimal RBAC
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/XS, approved

#1894 Update Cluster CR used by IM to be forwards compatible
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1887 Upgrade DB2 operator channel to v5.2
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1888 Upgrade DB2 operator channel to v5.2
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1895 Create .status.conditions in CommonService CRD
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
Labels: lgtm, size/L, approved

#1896 Create OperatorConfig for EDB when specified
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/odlm.go
  controllers/constant/odlm_operatorconfig.go
  controllers/operatorconfig.go
  go.mod
  go.sum
Labels: lgtm, size/L, approved

#1893 Delete crossplane CR by patching finalizer
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, approved, size/M

#1899 correct typo
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#1905 update common-service-db resources for large size on x86
  controllers/size/large_amd64.go
Labels: lgtm, size/S, approved

#1906 Update CRD to be forward compatible
  api/v3/commonservice_types.go
  api/v3/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  go.mod
  go.sum
Labels: lgtm, size/S, approved

#1907 add yq argument and version check
  cp3pt0-deployment/migrate_tenant.sh
  isolate.sh
  preload_data.sh
Labels: lgtm, approved, size/M

#1908 Removing ping
  cs-onprem-tenant-config.sh
Labels: lgtm, size/XS, needs-ok-to-test, approved

#1912 add cpfs annotation info for EDB Cluster CR
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1913 Enhance to prevent error messages
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, approved, size/M

#1915 reference cpfs version in Keycloak pod template
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1916 Resolve replica number reversion issue
  controllers/operandconfig.go
Labels: lgtm, size/S, approved

#1917 condition check for OperandRegistry version comparison
  controllers/bootstrap/init.go
Labels: lgtm, size/S, approved

#1919 annotate Keycloak pod with theme version instead of CPFS version
  Makefile
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/bootstrap/init.go
  controllers/constant/keycloakThemes.go
  controllers/constant/odlm.go
  hack/keycloak-themes/Makefile
  testdata/deploy/deploy.yaml
Labels: lgtm, size/L, approved

#1920 Remove hardcoded source for Zen operator
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1921 Ensure that DeletionTimestamp exists before patching the finalizers
  controllers/bootstrap/init.go
Labels: lgtm, size/S, approved

#1922 keep restart labels backward compatible with CPFS v3
  controllers/cert-manager/podrefresh_controller.go
Labels: lgtm, size/S, approved

#1927 remove wait for job function leftover from keycloak
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
Labels: lgtm, approved, size/M

#1931 Update network policy for CS 4.6
  cp3-networkpolicy/egress/generic/deny-all-egress.yaml
  cp3-networkpolicy/egress/generic/egress-allow-same-namespace.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-allow-k8s-services.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-allow-services-namespace.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-allow-k8s-services.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-allow-operator-ns.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-platform-auth-service.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-platform-identity-management.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-platform-identity-provider.yaml
  cp3-networkpolicy/egress/services/zen-egress-nginx.yaml
  cp3-networkpolicy/egress/services/zen-egress-usermgmt.yaml
  cp3-networkpolicy/egress/services/zen-egress-zen-metastoredb-init-job.yaml
  cp3-networkpolicy/egress/services/zen-egress-zen-metastoredb.yaml
  cp3-networkpolicy/egress/services/zen-egress-zen-minio.yaml
  cp3-networkpolicy/ingress/generic/allow-from-openshift-ingress.yaml
  cp3-networkpolicy/ingress/generic/deny-all-ingress.yaml
  cp3-networkpolicy/ingress/generic/ingress-allow-same-namespace.yaml
  cp3-networkpolicy/ingress/services/access-to-services-from-operator-namespace.yaml
Labels: lgtm, size/L, approved

#1926 [4.6.1, 4.7] Support mini RBAC in authorize namespace script
  cp3pt0-deployment/common/authorize-namespace.sh
Labels: lgtm, approved, size/M

#1925 [4.6.1] Check if third party cert-manger deployed before applying catalogsource
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, approved, size/M

#1918 add restore singleton subscription
  velero/backup/backup.yaml
  velero/restore/restore-singleton-subscriptions.yaml
  velero/restore/restore.sh
  velero/schedule/schedule-common-services.yaml
Labels: lgtm, approved, size/M

#1935 add singleton subsciption to br process
  velero/restore/restore-singleton-subscriptions.yaml
  velero/schedule/schedule-common-services.yaml
Labels: lgtm, size/S, approved

#1930 revert cpfs utils image to 4.5 to match repo
  velero/backup/zen/zen5_backup_job.yaml
  velero/restore/common-service-db/cs-db-restore-job.yaml
  velero/restore/keycloak/keycloak-restore-job.yaml
  velero/restore/zen/zen-restore-job.yaml
  velero/restore/zen/zen5-restore-job.yaml
  velero/schedule/common-service-db/cs-db-backup-deployment.yaml
  velero/schedule/keycloak/keycloak-backup-deployment.yaml
Labels: lgtm, size/S, approved

#1902 add velero plugin based labels, clarify labels
  velero/schedule/schedule-common-services.yaml
Labels: lgtm, size/S, approved

#1937 add keycloak label to schedule
  velero/schedule/schedule-common-services.yaml
Labels: lgtm, size/XS, approved

#1938 Bump to 4.6.1 for CPFS 4.6.1 release
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#1941 Provide custom namespace for LSR
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#1943 Bump sc2 stream to 4.6.2
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#1939 Bump 4.7.0 for CPFS 4.7.0 release
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1932 [Dev Branch] Update network policy for CS 4.6
  cp3-networkpolicy/egress/generic/deny-all-egress.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-allow-to-apiserver.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-allow-to-dns-default.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-iam-operator.yaml
  cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-operator.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-common-web-ui.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-edb-postgres.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-icp-mongodb.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-oidc-client-registration.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-platform-auth-service.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-platform-identity-management.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-platform-identity-provider.yaml
  cp3-networkpolicy/egress/zen/zen-egress-iam-config-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-nginx-tester.yaml
  cp3-networkpolicy/egress/zen/zen-egress-nginx.yaml
  cp3-networkpolicy/egress/zen/zen-egress-usermgmt-ensure-tables-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-usermgmt.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-core-api.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-core-create-tables-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-core-pre-requisite-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-core.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-metastore-backup-cron-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-metastoredb-init-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-metastoredb.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-minio-create-buckets-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-minio.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-pre-requisite-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-validate-metastore-edb-connection-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-watcher.yaml
  cp3-networkpolicy/ingress/generic/deny-all-ingress.yaml
  cp3-networkpolicy/ingress/zen/access-to-edb-postgres.yaml
  cp3-networkpolicy/ingress/zen/zen-access-to-audit-svc.yaml
  cp3-networkpolicy/ingress/zen/zen-access-to-nginx.yaml
  cp3-networkpolicy/ingress/zen/zen-access-to-usermgmt.yaml
  cp3-networkpolicy/ingress/zen/zen-access-to-zen-core-api.yaml
  cp3-networkpolicy/ingress/zen/zen-access-to-zen-core.yaml
  cp3-networkpolicy/ingress/zen/zen-access-to-zen-minio.yaml
  cp3-networkpolicy/ingress/zen/zen-access-to-zen-volumes.yaml
  cp3-networkpolicy/ingress/zen/zen-access-to-zen-watchdog.yaml
  cp3-networkpolicy/ingress/zen/zen-allow-iam-config-job.yaml
  cp3-networkpolicy/install_networkpolicy.sh
Labels: lgtm, approved, size/XL

#1944 [4.7] fix checkbox on new user panel
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  hack/keycloak-themes/README.md
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles470.css
  hack/keycloak-themes/theme/cloudpak/login/theme.properties
  testdata/deploy/deploy.yaml
Labels: lgtm, size/S, approved

#1945 Update net pkg for security vulnerability
  go.mod
  go.sum
Labels: lgtm, size/S, approved

#1946 match dev to scripts, add oidc rerun command
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
Labels: lgtm, approved, size/M

#1947 add rerun oidc job command
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
Labels: lgtm, size/XS, approved

#1940 Add cherry-pick workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cherry-pick.yaml
Labels: lgtm, approved, size/M, backport release-sc2

#1901 add velero plugin to im edb cluster config by default
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1954 fix: making sure pods get the backup label
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1955 update mongorestore command for multiple hosts
  velero/restore/mongoDB/mongo-restore.sh
  velero/restore/mongoDB/mongodbrestore.yaml
  velero/schedule/mongodb-backup-deployment.yaml
Labels: lgtm, size/XS, approved
