Repository IBM/ibm-common-service-operator, pull requests merged in 2024-06, with the labels that each got.

#2019 update go build version
  Dockerfile
Labels: lgtm, size/XS, approved

#2021 remove the generic pod definition
  velero/backup/genericBackupRestorePod.yaml
Labels: lgtm, size/S, approved

#2022 skip CatalogSource validating if there is no IBM Cert Manager installed
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved

#2023 Add info functions
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, approved, size/M

#2024 Add info functions
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, approved, size/M

#2030 update go build version
  Dockerfile
Labels: lgtm, size/XS, approved

#2032 Add StatusMonitoredServices annotations to OperandRegistry
  api/v3/commonservice_types.go
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#2033 Add StatusMonitoredServices annotations to OperandRegistry
  api/v3/commonservice_types.go
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#2034 bumped version from 4.7.0 to 4.8.0
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#2026 63639
  velero/schedule/zen-backup-deployment.yaml
  velero/schedule/zen4-br-scripts.yaml
  velero/schedule/zen5-backup-deployment.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/L, approved

#2035 Cpfs util job
  velero/schedule/deploy-br-resources.sh
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-deployment.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-configmap.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-pvc.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-rolebinding.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-sa.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-serv-tethered-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job-serv-tethered-rolebinding.yaml
  velero/spectrum-fusion/cpfs-util-resources/setup-tenant-job.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
Labels: lgtm, size/L, approved

#2031 Add release-sc2 branch to dependabot
  .github/dependabot.yml
Labels: lgtm, size/XS, approved

#2040 Allow cpfs pods to establish DNS connection
  cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-operator.yaml
  cp3-networkpolicy/egress/license-service-reporter/bedrock-egress-ibm-license-service-reporter-operator.yaml
  cp3-networkpolicy/egress/license-service/bedrock-egress-ibm-licensing-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-cloud-native-postgresql.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-egress-create-postgres-license-config.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-bts-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-common-service-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-commonui-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-events-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-iam-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-mongodb-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-namespace-scope-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-operand-deployment-lifecycle-manager.yaml
  cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-operator.yaml
  cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-setup-job.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-rhbk-operator.yaml
Labels: lgtm, size/L, approved

#2041 Allow cpfs pods to establish DNS connection
  cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-operator.yaml
  cp3-networkpolicy/egress/license-service-reporter/bedrock-egress-ibm-license-service-reporter-operator.yaml
  cp3-networkpolicy/egress/license-service/bedrock-egress-ibm-licensing-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-cloud-native-postgresql.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-egress-create-postgres-license-config.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-bts-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-common-service-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-commonui-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-events-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-iam-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-mongodb-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-ibm-namespace-scope-operator.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-operand-deployment-lifecycle-manager.yaml
  cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-operator.yaml
  cp3-networkpolicy/egress/operators/zen-egress-ibm-zen-setup-job.yaml
  cp3-networkpolicy/egress/services/bedrock-egress-rhbk-operator.yaml
Labels: lgtm, size/L, approved

#2015 specify dump location with emptyDir volume
  preload_data.sh
Labels: lgtm, size/XS, approved

#2047 Upgrade IM to 4.7 for CS 4.8
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2045 Security Updates for June '24 LTSR release
  go.mod
  go.sum
Labels: lgtm, approved, size/XL

#2046 update pkgs for security update
  go.mod
  go.sum
Labels: lgtm, approved, size/XL

#2042 Wait for operator pod ready only when its subscription exists before patching CS CR
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#2051 Bump version to 4.6.4
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#2052 update go-restful to 3.10
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#2053 update go restful to 3.10 for 3.23 branch
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#2054 Update EDB License Job image for LTSR
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2055 Update EDB License Job image for LTSR
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2043 Add label to the license service reporter resources
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, approved, size/M

#2036 Label the CommonService CRD so it can be selected for backup
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
Labels: lgtm, size/XS

#2037 Label the CommonService CR so it can be selected for backup
  controllers/constant/constant.go
Labels: lgtm, size/XS

#2048 Add BR label to cs cr by default
  controllers/constant/constant.go
Labels: size/XS, approved

#2058 Add label to the license service reporter resources (#2043)
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, approved, size/M

#2057 add br label to crd by default
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
Labels: lgtm, size/XS, approved

#2060 Create Spectrum Fusion recipe for License Service Reporter
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Labels: lgtm, size/L, approved

#2063 fix for unbound variable when namespace-scope cm is missing
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#2064 increase waiting time for operator upgrade and installation
  cp3pt0-deployment/common/utils.sh
Labels: lgtm, size/XS, approved

#2067 Improve the error msg for private catalogsource validating
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/XS, approved
