Repository IBM/ibm-common-service-operator, pull requests merged in 2024-01, with the labels that each got.

#1724 add Opensearch entry into Operand Registry
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1706 Licensing - covering LSR sender scenario 61539
  cp3pt0-deployment/common/migrate_singleton.sh
  isolate.sh
Labels: lgtm, needs-ok-to-test, approved, size/M

#1725 Update YQ and OC path
  cp3pt0-deployment/uninstall_tenant.sh
  isolate.sh
Labels: lgtm, size/S, approved

#1726 rename theme to cloudpak
  hack/cloudpak-theme.jar
  hack/cs-keycloak-theme.jar
  hack/keycloak-themes/META-INF/keycloak-themes.json
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_de.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_en.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_es.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_fr.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_it.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_ja.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_ko.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_pt_BR.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_zh_CN.properties
  hack/keycloak-themes/theme/cloudpak/login/messages/messages_zh_TW.properties
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles.css
  hack/keycloak-themes/theme/cloudpak/login/resources/img/favicon.ico
  hack/keycloak-themes/theme/cloudpak/login/theme.properties
Labels: lgtm, size/XS, approved

#1729 Remove cert-manager API dependency
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/S, approved

#1730 revert changes to account for z and power binaries
  preload_data.sh
Labels: lgtm, size/L, approved

#1727 Theme updates
  hack/cloudpak-theme.jar
  hack/keycloak-themes/.gitignore
  hack/keycloak-themes/META-INF/MANIFEST.MF
  hack/keycloak-themes/META-INF/keycloak-themes.json
  hack/keycloak-themes/Makefile
  hack/keycloak-themes/README.md
  hack/keycloak-themes/theme/cloudpak/account/theme.properties
  hack/keycloak-themes/theme/cloudpak/admin/theme.properties
  hack/keycloak-themes/theme/cloudpak/common/resources/img/favicon.ico
  hack/keycloak-themes/theme/cloudpak/common/resources/img/logo.svg
  hack/keycloak-themes/theme/cloudpak/email/theme.properties
Labels: lgtm, size/L, approved

#1732 Patching mgmtIngress CR only when converting from shared to dedicated mode
  convert_to_multi_instance.sh
  isolate.sh
Labels: lgtm, approved, size/M

#1734 Resolve issue with WaitForFirstConsumer volumeBindingMode
  preload_data.sh
Labels: lgtm, approved, size/M

#1733 update csv count and add error messages
  isolate.sh
Labels: lgtm, size/S, approved

#1737 Integerate Keycloak theme
  Dockerfile
  Makefile
  api/v3/commonservice_types.go
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/constant/keycloakThemes.go
  controllers/constant/odlm.go
  hack/keycloak-themes/Makefile
Labels: lgtm, size/L, approved

#1738 downgrade zen channel back to v4.3
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1629 CSV spec descriptors to improve rendering and usability
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/L, approved

#1736 disable cert-manager related functions
  controllers/bootstrap/init.go
  main.go
Labels: lgtm, size/L, approved

#1739 Fix bug in theme - switch from cloud-pak to cloudpak name
  hack/keycloak-themes/theme/cloudpak/account/theme.properties
  hack/keycloak-themes/theme/cloudpak/admin/theme.properties
Labels: lgtm, size/XS, approved

#1740 Update preview dir path to support multi non-root user
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_singleton.sh
  cp3pt0-deployment/setup_tenant.sh
  isolate.sh
Labels: lgtm, size/XS, approved

#1743 Reference EDB License Secret from OperatorNamespace
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1748 fix lint error for KeyCloak CR
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1747 updated opcon so Keycloak uses OCP certs
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1749 Handle Keycloak upgrade to refresh cs-keycloak-tls-secret
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1744 delete LSR ConfigMap from Pak ns during isolation
  isolate.sh
Labels: lgtm, size/XS, approved

#1753 grant new zen operator permission to nss operator
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/S, approved

#1751 Suppress error messages
  isolate.sh
Labels: lgtm, size/XS, approved

#1752 Overwrite the resource field when default rule is not specified
  controllers/operandconfig.go
Labels: lgtm, size/S, approved

#1754 Update Keycloak Service name in BindInfo ConfigMap
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1755 fixed cert-manager crd check
  main.go
Labels: lgtm, size/XS, approved

#1756 added cert label to keycloak cert secret
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1758 theme updates for keycloak errors, etc
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles.css
Labels: lgtm, approved, size/M

#1759 Add common to the list of theme types so it works in jar format
  hack/keycloak-themes/META-INF/keycloak-themes.json
Labels: lgtm, size/XS, approved

#1723 Create Backup and Restore process for license service reporter
  velero/restore/restore-lsr-data.yaml
  velero/restore/restore-lsr.yaml
  velero/schedule/license_service_reporter/lsr-backup-deployment.yaml
  velero/schedule/license_service_reporter/lsr-backup-pvc.yaml
  velero/schedule/license_service_reporter/lsr-br-scripts-cm.yaml
  velero/schedule/license_service_reporter/lsr-role.yaml
  velero/schedule/license_service_reporter/lsr-rolebinding.yaml
  velero/schedule/license_service_reporter/lsr-sa.yaml
  velero/schedule/schedule-common-services.yaml
Labels: lgtm, size/L, approved

#1763 [LTSR] automatically update cs maps with adding operator and master namespace into a new entry
  controllers/common/util.go
  main.go
Labels: lgtm, approved, size/M

#1761 update for licesning case with spec.sender set during self-isolation
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/scopewatcher_controller.go
Labels: lgtm, approved, size/M

#1765 [323] Cherry pick two PRs from release-ltsr
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/scopewatcher_controller.go
  main.go
Labels: lgtm, size/L, approved

#1766 add service id secrets to cert manager script
  velero/backup/cert-manager/label-cert-manager.sh
Labels: lgtm, size/S, approved

#1769 migrate licensing configmaps in self-isolation
  controllers/common/util.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/S, approved

#1770 [323] migrate licensing configmaps in self-isolation
  controllers/common/util.go
  controllers/scopewatcher_controller.go
Labels: lgtm, size/S, approved

#1771 Set key token when creating the LSR secret
  cp3pt0-deployment/common/migrate_singleton.sh
  isolate.sh
Labels: lgtm, size/S, approved

#1774 set scc privileged to false for webhook and secretshare
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
Labels: lgtm, size/XS, approved

#1773 set scc privileged to false for webhook and secretshare
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
Labels: lgtm, size/XS, approved

#1775 Update isolate.sh
  isolate.sh
Labels: lgtm, size/XS, approved

#1778 Bump CS operator to 4.5.0
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1780 Always return true for rm command
  hack/keycloak-themes/Makefile
Labels: lgtm, size/XS, approved

#1782 [4.5] Deploy CNPG operator, config EDB server and create tls certificate CR
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1781 Enable storageClass configuration for EDB wal
  controllers/constant/storageclass.go
Labels: lgtm, size/XS, approved

#1783 [4.5] Config two certificates for Zen and IM by ODLM
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M
