Repository IBM/ibm-common-service-operator, pull requests merged in 2024-09, with the labels that each got.

#2178 fix typo in finalizers
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/XS, approved

#2176 [CD] update odlm package version to get latest CRD version with channel fallback
  go.mod
  go.sum
Labels: lgtm, size/XS, approved

#2181 add fallback channels for EDB operator
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2185 Addon egress network policy
  cp3-networkpolicy/egress/zen/zen-egress-zen-remote-svc-inst-status-cron-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-svc-inst-status-cron-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-watchdog-create-tables-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-watchdog-post-requisite-job.yaml
  cp3-networkpolicy/egress/zen/zen-egress-zen-watchdog-pre-requisite-job.yaml
Labels: lgtm, needs-ok-to-test, approved, size/M

#2186 added new flag to indicate whether service is user managed
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/common/util.go
  controllers/operatorconfig.go
Labels: lgtm, approved, size/M

#2188 styling update for keycloak24
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles470.css
Labels: lgtm, size/XS, approved

#2187 obfuscate metrics secret values
  preload_data.sh
Labels: lgtm, size/XS, approved

#2191 cherrypick 64765
  preload_data.sh
Labels: lgtm, size/XS, approved

#2157 Automate running backups and restores w/ fusion
  br-testing-automation/auto-br.sh
  br-testing-automation/env.properties
  br-testing-automation/fusion-backup-setup.sh
  velero/spectrum-fusion/templates/sf-backup.yaml
  velero/spectrum-fusion/templates/sf-restore.yaml
Labels: lgtm, size/L, approved

#2195 update style version after updating theme file
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  hack/keycloak-themes/README.md
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles490.css
  hack/keycloak-themes/theme/cloudpak/login/theme.properties
  testdata/deploy/deploy.yaml
Labels: lgtm, size/S, approved

#2190 check length of operatorsStatus in OperandRegistry to trigger the CR reconciliation
  controllers/commonservice_controller.go
Labels: lgtm, size/XS, approved

#2197 [CD] add BTS with version in operandconfig
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2201 bump up version to 4.6.7
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#2199 Use Unstructured obj to copy CR to other ns
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/recocile_pause.go
Labels: lgtm, approved, size/M

#2203 Re-create NSS CR after NSS operator upgrade in migration
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/XS, approved

#2198 [SC2] Add new entry for BTS with version in operandconfig
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2196 updated theming for rhbk24
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  hack/keycloak-themes/README.md
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles467.css
  hack/keycloak-themes/theme/cloudpak/login/theme.properties
  testdata/deploy/deploy.yaml
Labels: lgtm, size/S, approved

#2200 [SC2] Use Unstructured obj to copy CR to other ns
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: lgtm, approved, size/M

#2205 Bump Keycloak to 24 for SC2 stream
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2206 using`ibm-licensing-service-instance` deployment to ensure the exact namespace
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#2210 keycloak styling updates
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles467.css
Labels: lgtm, approved, size/M

#2180 stop labeling opconfig, platform-auth-idp cm, label nss
  velero/backup/common-service/env.properties
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, approved, size/M

#2211 keyckoak theme updates
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles467.css
Labels: lgtm, size/S, approved

#2212 [SC2] apply customized user-profile for keycloak-24
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#2214 Fix format error
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#2213 bumpup version to 4.10
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/odlm.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#2218 keycloak theme updates for 4.10
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  hack/keycloak-themes/README.md
  hack/keycloak-themes/theme/cloudpak/login/resources/css/styles4100.css
  hack/keycloak-themes/theme/cloudpak/login/theme.properties
  testdata/deploy/deploy.yaml
Labels: lgtm, approved, size/M

#2219 [CD] apply customized user-profile for keycloak-24
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#2220 Add new entry at the end of array to bypass ODLM limitation on object update
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2221 [CD] Add new entry at the end of array to bypass ODLM limitation on object update
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2222 updated common-service EDB to 1.22
  controllers/constant/cloudNativePostgresql.go
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2215 add service account to mongo br resources
  velero/backup/mongoDB/mongo-backup.sh
  velero/restore/mongoDB/mongo-restore.sh
  velero/restore/mongoDB/mongodbrestore.yaml
  velero/schedule/mongodb-backup-deployment.yaml
Labels: lgtm, size/XS, approved

#2216 add service account to mongo BR resources
  velero/backup/mongoDB/mongo-backup.sh
  velero/restore/mongoDB/mongo-restore.sh
  velero/restore/mongoDB/mongodbrestore.yaml
  velero/schedule/mongodb-backup-deployment.yaml
Labels: lgtm, size/XS, approved

#2209 reduce the number of certs and secrets labeled to just cs-ca and zen-…
  velero/backup/cert-manager/label-cert-manager.sh
Labels: lgtm, size/S, approved

#2225 Add fallback channels for EDB operator
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2193 [4.10] support instana_user to connect to db
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2227 Add optional fields for Keycloak CR
  controllers/constant/odlm.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  go.mod
  go.sum
Labels: lgtm, size/L, approved

#2229 Update size limit for shared EDB
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, approved, size/M

#2230 Update go module
  go.mod
  go.sum
Labels: lgtm, size/XS, approved
