Repository IBM/ibm-common-service-operator, pull requests merged in 2024-10, with the labels that each got.

#2217 Fix fusion script/recipe issue found in SERT testing
  br-testing-automation/env.properties
  br-testing-automation/fusion-backup-setup.sh
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Labels: lgtm, size/S, approved

#2223 Enable labeling scripts to be run via job
  br-testing-automation/env.properties
  velero/backup/cert-manager/label-cert-manager-job.yaml
  velero/backup/cert-manager/label-cert-manager-role.yaml
  velero/backup/cert-manager/label-cert-manager-rolebinding.yaml
  velero/backup/cert-manager/label-cert-manager-sa.yaml
  velero/backup/cert-manager/label-cert-manager.sh
  velero/backup/common-service/env.properties
  velero/backup/common-service/label-bedrock-job.yaml
  velero/backup/common-service/label-bedrock-role.yaml
  velero/backup/common-service/label-bedrock-rolebinding.yaml
  velero/backup/common-service/label-bedrock-sa.yaml
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, approved, size/XL

#2234 Update ui operator channel to 4.6
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2235 Revert "Bump golang from 1.23.0-bullseye to 1.23.2-bullseye"
  Dockerfile
Labels: lgtm, size/XS

#2239 Update channels comparison
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#2242 waiting for licensing instance deployment
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#2245 Correct permissions and nss cm namespace in labeling script
  velero/backup/common-service/label-bedrock-role.yaml
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, size/XS, approved

#2248 Revert "Bump golang from 1.23.0-bullseye to 1.23.1-bullseye"
  Dockerfile
Labels: size/XS

#2228 sync scripts branch with scripts-dev
  velero/backup/cert-manager/label-cert-manager.sh
  velero/backup/common-service/env.properties
  velero/backup/common-service/label-common-service.sh
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns-multi-zen.yaml
Labels: lgtm, approved, size/XL

#2250 CD - Move to bookworm golang image
  Dockerfile
Labels: lgtm, size/XS, approved

#2251 SC2 - Move to bookworm golang
  Dockerfile
Labels: lgtm, size/XS, approved

#2249 added configuration for instana metrics collection
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  controllers/constant/instanaEnable.go
  controllers/render_template.go
Labels: lgtm, approved, size/M

#2238 Add optional fields for Keycloak CR
  controllers/constant/odlm.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  go.mod
  go.sum
Labels: lgtm, size/L, approved

#2254 [SC2] Make spec field optional in the serviceConfig section in CS CR
  api/v3/commonservice_types.go
Labels: lgtm, size/XS, approved

#2253 make spec field optional in the serviceConfig section in CS CR
  api/v3/commonservice_types.go
Labels: lgtm, size/XS, approved

#2256 Use 2 replicas for Keycloak EDB on starterset
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, size/XS, approved

#2257 Use 2 replicas for Keycloak EDB on starterset (#2256)
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, size/XS, approved

#2237 label length limited to 64 characters
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#2261 Add support for Keycloak 24/re-encrypt Route
  controllers/constant/odlm.go
Labels: lgtm, size/XS, needs-ok-to-test, approved

#2262 [SC2] Add support for Keycloak 24/re-encrypt Route (#2261)
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2263 label-length-limitation
  controllers/bootstrap/init.go
  controllers/common/util.go
Labels: lgtm, size/S, approved

#2264 Odlm subcheck and label length in CD
  controllers/bootstrap/init.go
  controllers/bootstrap/init_test.go
  controllers/common/util.go
  go.mod
Labels: lgtm, size/L, approved

#2265 [CD] new entry for event-v5.1
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2259 remove velero addon and cold backup annotations
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2268 [SC2] add opreq-control label for EDB License Job
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2269 [CD] add opreq-control label for EDB License Job
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2270 [scripts dev] change when the database dir cleanup takes place
  velero/schedule/common-service-db/cs-db-backup-deployment.yaml
Labels: lgtm, size/XS, approved

#2271 [scripts] change when the database dir cleanup takes place
  velero/schedule/common-service-db/cs-db-backup-deployment.yaml
Labels: lgtm, size/XS, approved

#2246 update flink and opensearch networkpolicy port
  cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operand.yaml
  cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operand.yaml
  cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operator.yaml
  cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operand.yaml
  cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operator.yaml
  cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operand.yaml
  cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operator.yaml
Labels: lgtm, approved, size/M

#2255 update flink and opensearch networkpolicy port
  cp3-networkpolicy/egress/flink/bedrock-egress-ibm-flink-operand.yaml
  cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operand.yaml
  cp3-networkpolicy/egress/opensearch/bedrock-egress-ibm-opensearch-operator.yaml
  cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operand.yaml
  cp3-networkpolicy/ingress/flink/bedrock-access-to-ibm-flink-operator.yaml
  cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operand.yaml
  cp3-networkpolicy/ingress/opensearch/bedrock-access-to-ibm-opensearch-operator.yaml
Labels: lgtm, approved, size/M

#2272 Revert "Update size limit for shared EDB"
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, approved, size/M

#2252 conditionally wait for ibm-licensing-instance
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#2275 Pick up EDB 1.22.7 images for CS 4.10
  controllers/constant/cloudNativePostgresql.go
Labels: lgtm, size/S, approved

#2274 Pick up EDB 1.22.7 images for release 4.6.8
  controllers/constant/cloudNativePostgresql.go
Labels: lgtm, size/S, approved

#2278 Add meta api deployment in zen/platformUI entries
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#2279 Update zen deployment meta api ns
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#2267 Clean up v3 leftover resources
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/constant/constant.go
  main.go
Labels: lgtm, size/L, approved

#2281 Clean up v3 leftover resources (#2267)
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/constant/constant.go
  main.go
Labels: lgtm, size/L, approved

#2282 Fix meta api namespace typo
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2283 Meta api entry cherry-pick
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#2277 Clean up Turbonomic folder to store new orm files
  turbonomic/README.md
  turbonomic/orm-audit-logging.yaml
  turbonomic/orm-auth-idp.yaml
  turbonomic/orm-auth-pap.yaml
  turbonomic/orm-auth-pdp.yaml
  turbonomic/orm-cert-manager.yaml
  turbonomic/orm-common-web-ui.yaml
  turbonomic/orm-ibm-licensing-service-instance.yaml
  turbonomic/orm-ibm-monitoring-grafana.yaml
  turbonomic/orm-icp-mongodb.yaml
  turbonomic/orm-management-ingress.yaml
  turbonomic/orm-must-gather-service.yaml
  turbonomic/orm-nginx-ingress.yaml
  turbonomic/orm-oidcclient-watcher.yaml
  turbonomic/orm-platform-api.yaml
  turbonomic/orm-policy-controller.yaml
  turbonomic/orm-secret-watcher.yaml
  turbonomic/orm-system-healthcheck-service.yaml
Labels: lgtm, size/L, approved

#2280 Update ODLM CRs after ODLM is upgraded to desired version
  controllers/bootstrap/init.go
  controllers/bootstrap/init_test.go
  controllers/commonservice_controller.go
Labels: lgtm, approved, size/M
