Repository IBM/ibm-common-service-operator, pull requests merged in 2024-02, with the labels that each got.

#1784 Create IM and Zen ConfigMap and OperandBindInfo
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1785 Update service endpoint for EDB
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1777 Bump default channel to v4.5
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1793 Bump LTSR to 3.19.21
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1794 Bump 323 stream to 3.23.13
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1798 Updating cs-onprem-tenant-config.sh
  cs-onprem-tenant-config.sh
Labels: lgtm, needs-ok-to-test, approved, size/M

#1797 Automatically clean up NSS CRs and operator in Simple TP or All ns mode
  api/v3/finalizer.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/recocile_pause.go
Labels: lgtm, size/L, approved

#1801 Check OprandRegistry and NSS resources CRD in fresh deployment
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
Labels: lgtm, approved, size/M

#1805 minimal RBAC file updated for NSS CRs cleaned up by CS operator
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/S, approved

#1802 Remove hard requirement to install core service from the same Catalog as CS/ODLM, as the preparation for catalog separation
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#1804 Enable customization for common-service-db Cluster CR
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, size/L, approved

#1807 Check OperandRegistry when checking no-op operators
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
Labels: lgtm, approved, size/M

#1808 bump version to 4.4.1
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#1796 Create a ConfigMap `mongodb-preload-endpoint` for IM to connect with MongoDB instance in original namespace
  preload_data.sh
Labels: lgtm, size/S, approved

#1803 LSR CR name consolidate in migration scenario
  cp3pt0-deployment/common/migrate_singleton.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, size/S, approved

#1812 Enable StorageClass configuration for common-service-db
  controllers/constant/storageclass.go
Labels: lgtm, size/XS, approved

#1815 Check scoped namespaces from nss ConfigMap instead of watch_namespace
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/webhooks/commonservice/validatingwebhook.go
Labels: lgtm, approved, size/M

#1816 Bump CS operator to 4.5.0 for efix
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/odlm.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1817 Bump CS operator to v4.6.0
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/odlm.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1818 Pin the ODLM channel at v4.3 for CS 4.6+
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/XS, approved

#1819 Removed im request in OperandConfig
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved
