Repository IBM/ibm-common-service-operator, pull requests merged in 2024-05, with the labels that each got.

#1952 [scripts-dev] Update network policy
  cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-cainjector.yaml
  cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-operator.yaml
  cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-webhook.yaml
  cp3-networkpolicy/egress/license-service-reporter/bedrock-egress-ibm-license-service-reporter-operator.yaml
  cp3-networkpolicy/egress/license-service/bedrock-egress-ibm-licensing-operator.yaml
  cp3-networkpolicy/egress/license-service/bedrock-egress-ibm-licensing-service-instance.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-allow-to-apiserver.yaml
  cp3-networkpolicy/ingress/cert-manager/allow-webhook-access-from-apiserver.yaml
  cp3-networkpolicy/ingress/license-service-reporter/bedrock-access-to-license-service-reporter.yaml
  cp3-networkpolicy/ingress/operators/allow-webhook-access-from-apiserver.yaml
  cp3-networkpolicy/install_networkpolicy.sh
Labels: lgtm, size/L, approved

#1953 [scripts] Update network policy
  cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-cainjector.yaml
  cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-operator.yaml
  cp3-networkpolicy/egress/cert-manager/bedrock-egress-ibm-cert-manager-webhook.yaml
  cp3-networkpolicy/egress/license-service-reporter/bedrock-egress-ibm-license-service-reporter-operator.yaml
  cp3-networkpolicy/egress/license-service/bedrock-egress-ibm-licensing-operator.yaml
  cp3-networkpolicy/egress/license-service/bedrock-egress-ibm-licensing-service-instance.yaml
  cp3-networkpolicy/egress/operators/bedrock-egress-allow-to-apiserver.yaml
  cp3-networkpolicy/ingress/cert-manager/allow-webhook-access-from-apiserver.yaml
  cp3-networkpolicy/ingress/license-service-reporter/bedrock-access-to-license-service-reporter.yaml
  cp3-networkpolicy/ingress/operators/allow-webhook-access-from-apiserver.yaml
  cp3-networkpolicy/install_networkpolicy.sh
Labels: lgtm, size/L, approved

#1956 Update pkgs for security vulnerabilities for 4.6.2
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#1958 removed internal OperandRequest from edb-keycloak
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1950 [4.6.2] EDB max connection config
  controllers/constant/odlm.go
  controllers/operandconfig.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, approved, size/M

#1949 EDB max connection configuration
  controllers/constant/odlm.go
  controllers/operandconfig.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, approved, size/M

#1960 updated channels for IM, commonui, and zen
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1965 [4.6.2] Pick up EDB 1.18.12
  controllers/constant/cloudNativePostgresql.go
Labels: lgtm, size/S, approved

#1964 [4.7] Pick up EDB operand Images from CASE 4.25.0
  controllers/constant/cloudNativePostgresql.go
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1962 update mongo sed command to work with mutliple entries per line
  velero/schedule/deploy-br-resources.sh
Labels: lgtm, size/XS, approved

#1951 Fix zen extension cleanup logic
  velero/schedule/zen5-backup-deployment.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/XS, approved

#1966 [4.6.2] removed internal OperandRequest from edb-keycloak
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#1963 add velero annotation and cpfs lbr labels by default to cs db cluster cr
  controllers/constant/odlm.go
Labels: lgtm, size/S, approved

#1971 Update ODLM CRs after ODLM has a minor version upgrade
  controllers/bootstrap/init.go
  controllers/bootstrap/init_test.go
  controllers/constant/odlm.go
  controllers/recocile_pause.go
  go.mod
  go.sum
Labels: lgtm, size/L, approved

#1967 Updated min RBAC role
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: size/XXL, lgtm, approved

#1972 Remove wildcard from nss-managed-bedrock-core-role.yaml
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/S, approved

#1970 [4.6.2] Add IM 4.4 and 4.5 entries in FipsEnable template
  controllers/constant/fipsEnable.go
Labels: lgtm, size/S, approved

#1973 Update ODLM and NSS package to v4 and remove unnecessary cert manager package dependency
  controllers/bootstrap/init.go
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/certmanager.go
  controllers/constant/odlm.go
  controllers/operatorconfig.go
  controllers/webhooks/commonservice/validatingwebhook.go
  controllers/webhooks/operandrequest/mutatingwebhook.go
  go.mod
  go.sum
  main.go
Labels: lgtm, size/L, approved

#1980 parameterized yq and oc variables
  cp3pt0-deployment/common/authorize-namespace.sh
  cp3pt0-deployment/common/cleanup_cp2_control.sh
  cp3pt0-deployment/common/migrate_singleton.sh
  cp3pt0-deployment/common/utils.sh
  cp3pt0-deployment/setup_singleton.sh
Labels: lgtm, approved, size/M

#1976 update oidc rerun logic, correct bug
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
  velero/schedule/keycloak/keycloak-br-script-cm.yaml
Labels: lgtm, approved, size/M

#1979 [SC2] Update EDB new license image
  controllers/constant/cloudNativePostgresql.go
Labels: lgtm, size/XS, approved

#1987 cherry pick 1973 for security vulnerabilities
  controllers/bootstrap/init.go
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/certmanager.go
  controllers/constant/odlm.go
  controllers/operatorconfig.go
  controllers/webhooks/commonservice/validatingwebhook.go
  controllers/webhooks/operandrequest/mutatingwebhook.go
  go.mod
  go.sum
  main.go
Labels: lgtm, size/L, approved

#1961 Created new entries for IM, CommonUi, and Zen
  controllers/constant/fipsEnable.go
  controllers/constant/odlm.go
  controllers/constant/serviceLabel.go
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
  docs/cloudpak-integration.md
  testdata/actual.yaml
  testdata/expected.yaml
Labels: lgtm, approved, size/XL

#1978 Update EDB new license image
  controllers/constant/cloudNativePostgresql.go
Labels: lgtm, size/XS, approved

#1988 Update indentation issue in OperandRegistry
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1989 Add endpoint cs-db-rw into dnsNames
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1994 add keycloak BR label for OADP
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1995 Update indentation in OperandConfig
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#1996 bump version to 3.19.22
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1997 bump to version 3.23.14
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  controllers/constant/secretshare.go
  controllers/constant/webhook.go
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#1957 Introduce Condition object into CommonService CR status
  api/v3/commonservice_types.go
  controllers/bootstrap/init.go
  controllers/cert-manager/certificaterefresh_controller.go
  controllers/cert-manager/podrefresh_controller.go
  controllers/cert-manager/v1_add_label_controller.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/goroutines/waitToCreateCsCR.go
Labels: lgtm, size/L, approved

#1999 replace xargs with tr and sed
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/XS, approved

#1998 consolidate annotations for EDB Cluster CR
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2003 remove offline specific velero backup annotation
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2002 remove velero offline backup annotation
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2007 change mongo node grabbing to be more consistent
  preload_data.sh
Labels: lgtm, size/XS, approved

#2006 Bump version to 4.6.3
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#1992 [4.6.3] add endpoint cs-db-rw into dnsNames
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2009 Wait for cs pod ready before configuring CS CR
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, approved, size/M

#2013 label some additional certificates, un-label a zen secret
  velero/backup/cert-manager/label-cert-manager.sh
Labels: lgtm, approved, size/M

#2005 Automatically label resources
  velero/backup/common-service/env.properties
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, size/L, approved

#2004 spectrum fusion updates
  velero/schedule/common-service-db/cs-db-backup-deployment.yaml
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
  velero/schedule/keycloak/keycloak-backup-deployment.yaml
  velero/schedule/license_service_reporter/lsr-backup-deployment.yaml
  velero/schedule/zen5-backup-deployment.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
  velero/spectrum-fusion/application.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-br-configmap.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-clusterrole.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-clusterrolebinding.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-deployment.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-pvc.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-rolebinding.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-sa.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-serv-tethered-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-serv-tethered-rolebinding.yaml
  velero/spectrum-fusion/policy.yaml
  velero/spectrum-fusion/policy_assignment.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Labels: size/XXL, lgtm, approved

#2017 copy over SF changes from scripts-dev
  velero/schedule/common-service-db/cs-db-backup-deployment.yaml
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
  velero/schedule/keycloak/keycloak-backup-deployment.yaml
  velero/schedule/license_service_reporter/lsr-backup-deployment.yaml
  velero/schedule/zen5-backup-deployment.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
  velero/spectrum-fusion/application.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-br-configmap.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-clusterrole.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-clusterrolebinding.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-deployment.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-pvc.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-rolebinding.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-sa.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-serv-tethered-role.yaml
  velero/spectrum-fusion/cpfs-util-resources/cpfs-util-serv-tethered-rolebinding.yaml
  velero/spectrum-fusion/policy.yaml
  velero/spectrum-fusion/policy_assignment.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Labels: size/XXL, lgtm, approved

#2018 Automatically label resources (#2005)
  velero/backup/common-service/env.properties
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, size/L, approved
