Repository IBM/ibm-common-service-operator, pull requests merged in 2025-02, with the labels that each got.

#2361 updated helm chart version to 4.11.0
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  helm/templates/operator-deployment.yaml
  helm/values.yaml
Labels: lgtm, size/S, approved

#2362 changed from using Chart.AppVersion to values.yaml
  helm/templates/operator-deployment.yaml
  helm/values.yaml
Labels: lgtm, size/XS, approved

#2363 added CommonService CR to helm chart
  helm/templates/cr.yaml
  helm/templates/operator-deployment.yaml
  helm/values.yaml
Labels: lgtm, size/S, approved

#2365 updated helm template to work with CICD automation
  helm-cluster-scoped/values.yaml
  helm/templates/operator-deployment.yaml
  helm/values.yaml
Labels: lgtm, size/S, approved

#2366 comment out values for transition to global values file
  helm-cluster-scoped/values.yaml
  helm/templates/cr.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: lgtm, approved, size/M

#2369 remove cluster rbac
  helm-cluster-scoped/templates/cluster-rbac.yaml
  helm/templates/rbac.yaml
Labels: lgtm, size/L, approved

#2368 Update OWNERS with my Id
  OWNERS
Labels: lgtm, size/XS, approved

#2367 Update OWNERS with my ID
  OWNERS
Labels: lgtm, size/XS, approved

#2375 updated ODLM to channel v4.4 for CD
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2376 Removed EDB image list created by cs operator for non-olm case
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
Labels: lgtm, size/S, approved

#2377 Bump up version for sc2
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#2371 Enable granting permission for token exchange (#2345)
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2378 Update ODLM channel with v4.4 for CPFS v4.11
  cp3pt0-deployment/migrate_tenant.sh
Labels: lgtm, size/S, approved

#2373 added new postgres parameter max_slot_wal_keep_size CD
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2364 refactor cs-operator to enable common-service controller
  controllers/bootstrap/init.go
  controllers/common/util.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/deploy/manager.go
  controllers/goroutines/no_olm_operator_status.go
  main.go
Labels: lgtm, size/L, approved

#2382 Add label to helm generated resources
  helm-cluster-scoped/templates/cluster-rbac.yaml
  helm-cluster-scoped/templates/crd.yaml
  helm-cluster-scoped/values.yaml
  helm/templates/cr.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: lgtm, size/S, approved

#2383 commit to re-run CI build
  README.md
Labels: lgtm, size/XS, approved

#2387 Create all role and rolebindings in each namespace
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: lgtm, approved, size/M

#2379 create olm -> no olm migration chart in master branch
  bedrock-migration/.helmignore
  bedrock-migration/Chart.yaml
  bedrock-migration/templates/adopt-cs-cr.yaml
  bedrock-migration/templates/adopt-nss-cr.yaml
  bedrock-migration/templates/bedrock-migration-job.yaml
  bedrock-migration/templates/rbac.yaml
  bedrock-migration/values.yaml
Labels: size/L, approved

#2390 check mongo statefulset
  preload_data.sh
Labels: lgtm, size/S, approved

#2389 Add corresponding metadata to pass RH certification
  Dockerfile
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/next-csv.sh
  config/ibm-common-service-operator.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#2393 Remove non-OLM env from OLM bundle
  Makefile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manager/non-olm-env-patch.yaml
Labels: lgtm, approved, size/M

#2337 Enhance Keycloak 26 pod scheduling and startup probe configurations
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#2395 Enhance Keycloak 26 pod scheduling
  controllers/constant/odlm.go
Labels: lgtm, approved, size/M

#2397 scale down mongodb operator
  preload_data.sh
Labels: lgtm, size/XS, approved

#2399 Generate EDB config template for all EDB service versions using
  api/v3/commonservice_types.go
  controllers/bootstrap/init.go
  controllers/constant/odlm.go
Labels: lgtm, size/L, approved

#2400 updated version to 4.12.0
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/ibm-common-service-operator.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  helm/templates/operator-deployment.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#2374 added new postgres parameter max_slot_wal_keep_size SC2
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2404 Support shared buffer values for common service db cluster
  controllers/rules/rules.go
  controllers/size/large_amd64.go
  controllers/size/large_ppc64le.go
  controllers/size/large_s390x.go
  controllers/size/medium_amd64.go
  controllers/size/medium_ppc64le.go
  controllers/size/medium_s390x.go
  controllers/size/small_amd64.go
  controllers/size/small_ppc64le.go
  controllers/size/small_s390x.go
  controllers/size/starterset_amd64.go
  controllers/size/starterset_ppc64le.go
  controllers/size/starterset_s390x.go
Labels: lgtm, size/S, approved

#2403 Support shared buffer values for common service db cluster
  internal/controller/rules/rules.go
  internal/controller/size/large_amd64.go
  internal/controller/size/large_ppc64le.go
  internal/controller/size/large_s390x.go
  internal/controller/size/medium_amd64.go
  internal/controller/size/medium_ppc64le.go
  internal/controller/size/medium_s390x.go
  internal/controller/size/small_amd64.go
  internal/controller/size/small_ppc64le.go
  internal/controller/size/small_s390x.go
  internal/controller/size/starterset_amd64.go
  internal/controller/size/starterset_ppc64le.go
  internal/controller/size/starterset_s390x.go
Labels: lgtm, size/S, approved

#2406 Fixed reference value for imageRegistryNamespaceOperator
  helm/templates/operator-deployment.yaml
Labels: lgtm, size/XS, approved

#2407 updated migration chart to version 0.0.0
  bedrock-migration/Chart.yaml
  bedrock-migration/templates/bedrock-migration-job.yaml
  bedrock-migration/values.yaml
Labels: lgtm, size/S, approved

#2408 increas timeout limit and cleanup resource in rerun
  preload_data.sh
Labels: lgtm, size/XS, approved

#2411 move operator status check into reconciliation loop
  api/v3/commonservice_types.go
  controllers/bootstrap/init.go
  controllers/bootstrap/init_test.go
  controllers/commonservice_controller.go
  controllers/constant/constant.go
  controllers/goroutines/cleanup_resources.go
  controllers/goroutines/operator_status.go
  main.go
Labels: lgtm, approved, size/XL

#2412 Add restore-nss.yaml file
  velero/backup/common-service/label-common-service.sh
  velero/restore/restore-nss.yaml
Labels: lgtm, size/L, approved

#2414 Add shared_buffers to comparable keys and normalize resource quantity formats
  controllers/operandconfig.go
  controllers/rules/resource_comparison.go
Labels: lgtm, approved, size/M

#2415 Bump up service operator version for CS 4.12
  internal/controller/constant/odlm.go
Labels: lgtm, approved, size/M
