Repository IBM/ibm-common-service-operator, pull requests merged in 2025-03, with the labels that each got.

#2416 changed migration chart name from bedrock-migration to cpfs-migration
  bedrock-migration/Chart.yaml
Labels: lgtm, size/XS, approved

#2417 move operator status check into reconciliation loop
  api/v3/commonservice_types.go
  cmd/main.go
  internal/controller/bootstrap/init.go
  internal/controller/bootstrap/init_test.go
  internal/controller/commonservice_controller.go
  internal/controller/constant/constant.go
  internal/controller/goroutines/cleanup_resources.go
  internal/controller/goroutines/operator_status.go
  internal/controller/no_olm_commonservice_controller.go
Labels: lgtm, approved, size/XL

#2418 [CD] Add shared_buffers to comparable keys and normalize resource quantity formats (#2414)
  internal/controller/operandconfig.go
  internal/controller/rules/resource_comparison.go
Labels: lgtm, approved, size/M

#2419 changed tetheredNamespace to tetheredNamespaces
  bedrock-migration/templates/rbac.yaml
  bedrock-migration/values.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: lgtm, size/XS, approved

#2422 add nss field to schedule
  velero/schedule/schedule-common-services.yaml
Labels: lgtm, size/XS, approved

#2425 Add Postgres services in non-olm bootstrap
  api/v3/zz_generated.deepcopy.go
  internal/controller/bootstrap/init.go
Labels: lgtm, size/S, approved

#2426 handle error returning
  internal/controller/commonservice_controller.go
  internal/controller/no_olm_commonservice_controller.go
Labels: lgtm, size/S, approved

#2427 bump cs-operator to 4.6.12
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, size/S, approved

#2394 Script updates for BR of no olm install
  velero/backup/common-service/label-common-service.sh
  velero/restore/no-olm/restore-cluster-scope.yaml
  velero/restore/no-olm/restore-im-ns-charts.yaml
  velero/restore/no-olm/restore-installer-ns-charts.yaml
  velero/restore/no-olm/restore-namespace-scope.yaml
  velero/restore/no-olm/restore-zen-ns-chart.yaml
  velero/schedule/schedule-common-services.yaml
  velero/schedule/zen5-br-scripts-cm.yaml
  velero/schedule/zen5-role.yaml
Labels: lgtm, size/L, approved

#2430 Refactor reconciliation logic for operand registry and add support for ODLM managed subscriptions triggering reconciliation
  internal/controller/commonservice_controller.go
  internal/controller/constant/constant.go
Labels: lgtm, size/S, approved

#2432 added cpfs specific imagePullPrefix, use global if empty
  helm/templates/operator-deployment.yaml
  helm/values.yaml
Labels: lgtm, size/XS, approved

#2433 appended operator ns to cluster rbac names helm chart
  helm-cluster-scoped/templates/cluster-rbac.yaml
  helm-cluster-scoped/values.yaml
Labels: lgtm, size/S, approved

#2434 updated helm chart to remove NSS dependency
  helm/templates/operator-deployment.yaml
Labels: lgtm, size/S, approved

#2435 added new labels variable to values
  helm/templates/cr.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
Labels: lgtm, size/S, approved

#2440 add op namespace value to each cluster scoped resource name
  velero/backup/common-service/label-common-service.sh
Labels: lgtm, size/S, approved

#2437 Enable dynamic backchannel and hostnamev configuration in OperandConfig
  internal/controller/constant/odlm.go
Labels: lgtm, approved, size/M

#2442 add permissions to delete and patch nss cr
  bedrock-migration/templates/bedrock-migration-job.yaml
  bedrock-migration/templates/rbac.yaml
Labels: lgtm, size/S, approved

#2443 Skip no-op operators when retrieving operator status
  internal/controller/bootstrap/init.go
Labels: lgtm, size/XS, approved

#2338 Enhance Keycloak 26 truststore file and sa certs import
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/controller/bootstrap/init.go
  internal/controller/common/util.go
  internal/controller/constant/odlm.go
Labels: lgtm, size/L, approved

#2410 Remove truststore startup script for keycloak 24 and 26
  api/v3/commonservice_types.go
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/controller/bootstrap/init.go
  internal/controller/common/util.go
  internal/controller/constant/odlm.go
Labels: lgtm, size/L, approved

#2446 Enhancement on EnsureLabels function
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/ibm-common-service-operator.yaml
  config/rbac/role.yaml
  helm/templates/rbac.yaml
  internal/controller/bootstrap/init.go
  internal/controller/common/util.go
Labels: lgtm, approved, size/M

#2448 Remove image list cm and edb config secret during migration
  bedrock-migration/templates/adopt-cs-cr.yaml
  bedrock-migration/templates/bedrock-migration-job.yaml
  bedrock-migration/templates/rbac.yaml
Labels: lgtm, size/S, approved

#2447 [SC2] Enhancement on EnsureLabels function
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/bootstrap/init.go
  internal/controller/common/util.go
Labels: lgtm, approved, size/M

#2449 add cpfs.imagePullPrefix, remove nss roles
  bedrock-migration/templates/bedrock-migration-job.yaml
  bedrock-migration/templates/rbac.yaml
Labels: lgtm, size/S, approved

#2431 update min rbac permissions for edb 1.25
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, approved, size/M

#2456 Adopt postgresql operator to 1.25.1 for CS 4.6.12
  internal/controller/constant/odlm.go
Labels: lgtm, size/XS, approved

#2457 Adopt postgres operator to 1.25.1 (#2456)
  internal/controller/constant/odlm.go
Labels: lgtm, size/XS, approved

#2458 Add new permissions required for Postgres 1.25.1
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/XS, approved

#2451 preload-data cleanup enhancement
  preload_data.sh
Labels: lgtm, size/L, approved

#2453 update net pkg to 0.36.0 for SC2 4.6.12
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2455 Implement dynamic default and fallback channels for operators in OperandRegistry
  internal/controller/bootstrap/init.go
  internal/controller/commonservice_controller.go
  internal/controller/configurationcollector/collector.go
  internal/controller/constant/constant.go
  internal/controller/constant/odlm.go
Labels: lgtm, size/L, approved

#2461 update fallback channels for Keycloak EDB
  internal/controller/constant/odlm.go
Labels: lgtm, size/XS, approved

#2463 Update fallback channels for Keycloak EDB (#2461)
  internal/controller/constant/odlm.go
Labels: lgtm, size/XS, approved

#2452 Update to the fusion automation scripts
  br-testing-automation/env.properties
  br-testing-automation/fusion-backup-setup.sh
  velero/spectrum-fusion/application.yaml
  velero/spectrum-fusion/policy_assignment.yaml
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns-multi-zen.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
  velero/spectrum-fusion/recipes/4.8-example-csdb-sync-recipe.yaml
  velero/spectrum-fusion/recipes/4.8-example-zen-sync-recipe.yaml
Labels: lgtm, approved, size/M

#2465 [cd] add cpfs util image in related_image
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  internal/controller/common/util.go
Labels: lgtm, size/S, approved

#2466 [SC2] add cpfs util image in related_image
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/controller/common/util.go
Labels: lgtm, size/XS, approved

#2469 Update Postgresql 1.25.1 operand image for CASE 5.15.0
  internal/controller/constant/cloudNativePostgresql.go
Labels: lgtm, size/S, approved

#2470 Update Postgresql 1.25.1 operand image for CASE 5.15.0
  internal/controller/constant/cloudNativePostgresql.go
Labels: lgtm, size/S, approved

#2468 Move customized user profile config onto additional options
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2471 Move customized user profile config under additional options
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2472 [SC2] Add must gather image in relatedImage for Catalog based mirroring
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS, approved

#2473 [CD] Add new images into relatedImages section for catalog based mirror
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/S, approved

#2474 adopt configName in OperandRegistry API
  go.mod
  go.sum
  internal/controller/constant/odlm.go
Labels: lgtm, approved, size/M

#2475 rename Keycloak conversion resources for pre-upgrade process
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2478 [SC2] add labelSelector for common-service-db in topology constraints
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2480 update net pkg to 0.36.0 for 4.12
  go.mod
  go.sum
Labels: lgtm, approved, size/M
