Repository IBM/ibm-common-service-operator, pull requests merged in 2025-04, with the labels that each got.

#2481 onboard new licensing operator - ibm-usage-metering-operator
  internal/controller/constant/odlm.go
Labels: lgtm, size/XS, approved

#2467 add `manage-cert-rotation: yes` label to cs-ca-certificate CR
  api/v3/commonservice_types.go
  config/crd/bases/operator.ibm.com_commonservices.yaml
  internal/controller/bootstrap/init.go
  internal/controller/commonservice_controller.go
  internal/controller/constant/certmanager.go
  internal/controller/no_olm_commonservice_controller.go
Labels: lgtm, approved, size/M

#2476 [CD] adopt configName in OperandRegistry API
  go.mod
  go.sum
  internal/controller/constant/odlm.go
Labels: lgtm, approved, size/M

#2483 add disableManageCertRotation field to no-olm crd templete
  bundle/manifests/operator.ibm.com_commonservices.yaml
  helm-cluster-scoped/templates/crd.yaml
Labels: lgtm, size/XS, approved

#2484 added new parameter to handle output directory for preload script
  preload_data.sh
Labels: lgtm, approved, size/M

#2462 Implement dynamic default and fallback channels for operators in Oper…
  internal/controller/bootstrap/init.go
  internal/controller/commonservice_controller.go
  internal/controller/configurationcollector/collector.go
  internal/controller/constant/constant.go
  internal/controller/constant/odlm.go
  internal/controller/no_olm_commonservice_controller.go
Labels: lgtm, size/L, approved

#2460 66195
  velero/backup/common-service/label-common-service.sh
  velero/restore/restore-licensing.yaml
  velero/restore/restore-lsr.yaml
  velero/schedule/license_service_reporter/lsr-br-scripts-cm.yaml
  velero/schedule/schedule-common-services.yaml
Labels: lgtm, approved, size/M

#2482 use annotation to create commonservice cr
  cmd/main.go
  helm/templates/cr.yaml
  helm/templates/operator-deployment.yaml
  internal/controller/bootstrap/init.go
  internal/controller/goroutines/waitToCreateCsCrNoOLM.go
Labels: lgtm, size/L, approved

#2477 [CD] rename Keycloak conversion resources for pre-upgrade process (#2475)
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2479 [CD] add labelSelector for common-service-db in topology constraints
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2487 remove last , in commonservice label template
  helm/templates/operator-deployment.yaml
Labels: lgtm, size/XS, approved

#2488 update migration chart to no longer adopt the cs cr now that cs op cr…
  bedrock-migration/templates/adopt-cs-cr.yaml
Labels: lgtm, size/XS, approved

#2490 bump cs-operator to v4.6.13
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/kustomization.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#2491 [CD] add handling for no-op mode in operator status checks
  internal/controller/bootstrap/init.go
Labels: lgtm, size/XS, approved

#2492 [SC2] add handling for no-op mode in operator status checks
  internal/controller/bootstrap/init.go
Labels: lgtm, size/XS, approved

#2493 Update EDB operand images
  internal/controller/constant/cloudNativePostgresql.go
Labels: lgtm, size/S, approved

#2489 make oidc job completion check more stable
  velero/schedule/common-service-db/cs-db-br-script-cm-4.6.10.4.11.yaml
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
Labels: lgtm, size/S, approved

#2494 [CD] Update EDB operand images
  internal/controller/constant/cloudNativePostgresql.go
Labels: lgtm, size/S, approved

#2498 Bump cs operator to 4.6.14
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/kustomization.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#2497 updated manage-cert-rotation label values
  internal/controller/bootstrap/init.go
  internal/controller/constant/certmanager.go
Labels: lgtm, size/XS, approved

#2499 4.6.14 update net and oauth pkgs for sec scan
  go.mod
  go.sum
Labels: lgtm, approved, size/M
