Repository IBM/ibm-common-service-operator, pull requests merged in 2025-01, with the labels that each got.

#2334 delete storageclass from cs cr
  preload_data.sh
Labels: lgtm, size/S, approved

#2336 update net pkg to 0.33.0
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2321 Restart auth service
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
Labels: lgtm, approved, size/M

#2340 add full DNS name to mongo certificate
  preload_data.sh
Labels: lgtm, approved, size/M

#2345 Enable granting permission for token exchange
  controllers/constant/odlm.go
Labels: lgtm, size/XS, approved

#2346 start go routines after cs controller manager setup
  main.go
Labels: lgtm, size/S, approved

#2339 Adding OLM required metadata
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/S, approved

#2348 Pick up PostgreSQL 14.15 image
  controllers/constant/cloudNativePostgresql.go
Labels: lgtm, size/XS, approved

#2349 Adding OLM required metadata (#2339)
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
Labels: lgtm, size/S, approved

#2350 Update net pkg to 0.33 for 4.6.10
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#2354 added new watsonxaiifm min rbac for zen
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/S, approved

#2353 Decouple common service operator from OLM
  controllers/bootstrap/init.go
  controllers/commonservice_controller.go
  main.go
Labels: lgtm, size/L, approved

#2352 Mongo certficate DNS name patch
  preload_data.sh
Labels: lgtm, size/L, approved

#2351 Add helm generate into makefile
  Makefile
  config/certmanager/certificate.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/ibm-common-service-operator.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/service_account/kustomization.yaml
  config/service_account/service_account.yaml
  config/webhook/service.yaml
  helm-cluster-scoped/Chart.yaml
  helm-cluster-scoped/templates/cluster-rbac.yaml
  helm-cluster-scoped/templates/cluster-webhook.yaml
  helm-cluster-scoped/templates/crd.yaml
  helm-cluster-scoped/values.yaml
  helm/Chart.yaml
  helm/templates/cr.yaml
  helm/templates/operator-deployment.yaml
  helm/templates/rbac.yaml
  helm/values.yaml
  triggerfile
Labels: size/XXL, lgtm, approved

#2358 remove crs from helm chart
  helm/templates/cr.yaml
Labels: lgtm, approved, size/M

#2359 add create certificate cr in no-olm
  controllers/commonservice_controller.go
Labels: lgtm, size/XS, approved
