Repository IBM/ibm-common-service-operator, pull requests merged in 2025-06, with the labels that each got.

#2328 Create singleton recipe for Cert Manager
  velero/backup/cert-manager/label-singleton-cert-manager-clusterrole.yaml
  velero/backup/cert-manager/label-singleton-cert-manager-job.yaml
  velero/backup/cert-manager/label-singleton-cert-manager.sh
  velero/backup/common-service/label-common-service.sh
  velero/spectrum-fusion/cert-manager/backup-restore-workflow.yaml
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.0-4.5-example-recipe-single-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns-multi-zen.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-multi-ns.yaml
  velero/spectrum-fusion/recipes/4.7-example-recipe-single-ns.yaml
Labels: lgtm, approved, size/XL

#2543 Enable user-defined catalog source and namespace in CS CR
  api/v3/commonservice_types.go
  bundle/manifests/operator.ibm.com_commonservices.yaml
  config/crd/bases/operator.ibm.com_commonservices.yaml
  internal/controller/bootstrap/init.go
  internal/controller/constant/odlm.go
  internal/controller/webhooks/commonservice/validatingwebhook.go
Labels: lgtm, size/L, approved

#2544 enhance Postgres Cluster image update function
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/bootstrap/init.go
  internal/controller/commonservice_controller.go
Labels: lgtm, approved, size/M

#2551 Bump CS version up to 4.14.0
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/ibm-common-service-operator.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  helm/templates/operator-deployment.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#2552 Bump up IM and CommonUI version for 4.14
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2532 remove backup and restore unused database
  velero/schedule/common-service-db/cs-db-br-script-cm-4.6.10.4.11.yaml
  velero/schedule/common-service-db/cs-db-br-script-cm.yaml
Labels: lgtm, size/S, approved

#2518 remove unused database
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2547 Fix error logging in ReconcileMasterCR to use correct error variable
  internal/controller/commonservice_controller.go
Labels: size/XS, approved

#2539 Clarify usage instructions for CP3.0 NetworkPolicies installation script
  cp3-networkpolicy/install_networkpolicy.sh
  networkpolicy/install_networkpolicy.sh
Labels: size/XS, approved
