Repository IBM/ibm-common-service-operator, pull requests merged in 2025-05, with the labels that each got.

#2502 updated version to 4.13.0
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/ibm-common-service-operator.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  helm/templates/operator-deployment.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#2506 update counter for iam-config-job as well
  velero/schedule/zen5-br-scripts-cm.yaml
Labels: lgtm, size/XS, approved

#2501 Update backchannel-dynamic as the first-class citizen of the Keycloak CR
  internal/controller/constant/odlm.go
Labels: lgtm, approved, size/M

#2509 Bump up IM and CommonUI versions for 4.13
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2507 added configuration to enable/disable HPA
  api/v3/commonservice_types.go
  config/crd/bases/operator.ibm.com_commonservices.yaml
  internal/controller/constant/autoScaleConfig.go
  internal/controller/render_template.go
Labels: lgtm, approved, size/M

#2511 [CD] Update backchannel-dynamic as the first-class citizen of the Keycloak…
  internal/controller/constant/odlm.go
Labels: lgtm, approved, size/M

#2512 upgrade zen default channel to v6.2
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2510 change size value location
  helm/templates/operator-deployment.yaml
  helm/values.yaml
Labels: lgtm, size/S, approved

#2504 bump up hook weight
  bedrock-migration/templates/bedrock-migration-job.yaml
  bedrock-migration/templates/rbac.yaml
Labels: lgtm, size/S, approved

#2508 Add default value 'false'
  helm/templates/operator-deployment.yaml
Labels: lgtm, size/XS, approved

#2516 Update ODLM channel to 4.5 for CPFS v4.12+
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/S, approved

#2521 add an new entry for events v5.2
  internal/controller/constant/odlm.go
Labels: lgtm, size/XS, approved

#2522 bump up version to 4.6.15
  Makefile
  README.md
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/kustomization.yaml
  config/manifests/bases/ibm-common-service-operator.clusterserviceversion.yaml
  testdata/deploy/deploy.yaml
  version/version.go
Labels: lgtm, approved, size/M

#2523 update net pkg for 4.13
  go.mod
  go.sum
Labels: lgtm, size/S, approved

#2520 Update the image digest in the Cluster CR as referenced from the ConfigMap in the PostgreSQL operator bundle
  common/scripts/lint_go.sh
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2528 updated bundle CRD with hpa toggle
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_commonservices.yaml
Labels: lgtm, size/XS, approved

#2529 [SC2] Update the image digest in the Cluster CR as referenced from the Conf…
  common/scripts/lint_go.sh
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved

#2525 [SC2] add an new entry for event 5.2
  internal/controller/constant/odlm.go
Labels: lgtm, size/XS, approved

#2530 Update NSS operator channel logic for CPFS 4.13
  cp3pt0-deployment/migrate_tenant.sh
  cp3pt0-deployment/setup_tenant.sh
Labels: lgtm, size/S, approved

#2534 Add functionality to wait for Postgres Cluster image updates before applying configuration setting
  bundle/manifests/ibm-common-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  helm/templates/rbac.yaml
  internal/controller/bootstrap/init.go
  internal/controller/commonservice_controller.go
  internal/controller/constant/cloudNativePostgresql.go
  internal/controller/constant/constant.go
Labels: lgtm, size/L, approved

#2536 Add new permission in nss managed role for Events 5.2.0
  cp3pt0-deployment/common/nss-managed-bedrock-core-role.yaml
Labels: lgtm, size/XS, approved

#2533 Remove unused database
  internal/controller/constant/odlm.go
Labels: lgtm, size/S, approved
